### ISSUE TITLE
How to catch DataProvider value into method at Runtime

### ISSUE THREAD

**Issue by antuking** [cbeust/testng#2774] opened 2022-06-08 10:03 UTC
### Expected behavior

1. Got the DataProvider value (Object[]) at Runtime to handle another task.
2. Want to re-use parallel from DataProvider feature.

### Actual behavior
Just update the Iterator for DataProvider at IDataProviderInterceptor

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
1. Having a list of device metrics (width, height, pixelRatio, userAgent) as DataProvider data class.
3. Initialize ChromeDriver with the device metrics information at ChromeOption before performing the testcase automatically.
4. The initialize step follows to Method scope.

**Comment by krmahadevan** [comment] 2022-06-08 10:52
@antuking - the latest released version if 7.6.0. Can you please try again using this and post back your findings ?

**Comment by krmahadevan** [comment] 2022-06-08 11:27
If the problem is reproducible in `7.6.0` please include a simple standalone example (that does not use selenium or any other libraries for that matter) which can be used to reproduce the problem.

**Comment by antuking** [comment] 2022-06-08 15:28
Hi @krmahadevan , here is sample code which implemented in `7.6.0`

Here is my custom IDataProviderIntercetor:
`public class MyListener implements IDataProviderInterceptor {
    @Override
    public Iterator<Object[]> intercept(Iterator<Object[]> iterator, IDataProviderMethod iDataProviderMethod,
                                        ITestNGMethod iTestNGMethod, ITestContext iTestContext) {
        Iterable<Object[]> iterable = () -> iterator;
        List<Object[]> list = StreamSupport.stream(iterable.spliterator(), false).collect(Collectors.toList());

        Test test = iTestNGMethod.getConstructorOrMethod().getMethod().getAnnotation(Test.class);
        String dataProviderName = test.dataProvider();
        if (dataProviderName != null && !dataProviderName.isEmpty()) {
            list.forEach(obj -> System.err.println(Arrays.toString(obj)));
        }

        return list.iterator();
    }
}`

Here is sample Test section
`@Listeners({ MyListener.class})
public class SampleTest {

    @BeforeClass
    public void beforeClass() {}

    @Test(dataProvider = "abc")
    public void test1(int i1, int i2, int i3) {
        System.err.println("This is a sample");
    }

    @DataProvider(name = "abc")
    public Object[][] getType() {
        return new Object[][] {
                { 1, 3, 5 },
                { 2, 4, 6 }
        };
    }
}`

#### I want to catch-up each of dataprovider value like `1, 3, 5` and do something with these stuffs. Then will do the next steps for rest of them.

**Comment by krmahadevan** [comment] 2022-06-10 03:58
> Hi @krmahadevan, do you have any update?

I am travelling right now and wont be home till the weekend. I will get to this once am back home, early next week

**Comment by krmahadevan** [comment] 2022-06-14 05:00
@antuking - Please check if the below sample answers your use case. If not, please feel free to modify the example such that it can be used to reproduce your ask.

```java
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(MyListener.class)
public class SampleTest {

  @BeforeClass
  public void beforeClass() {
  }

  @Test(dataProvider = "abc")
  public void test1(int i1, int i2, int i3) {
    System.err.println("This is a sample");
  }

  @DataProvider(name = "abc")
  public Object[][] getType() {
    return new Object[][]{
        {1, 3, 5},
        {2, 4, 6}
    };
  }
}
```

```java
import java.util.Arrays;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestResult;

public class MyListener implements IInvokedMethodListener {

  @Override
  public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
    if (method.isTestMethod()) {
      Object[] parameters = testResult.getParameters();
      System.err.println("Parameters that was passed was : " + Arrays.toString(parameters));
    }
  }
}

```

**Comment by antuking** [comment] 2022-06-14 09:18
Nice @krmahadevan, It works for me now. Thanks for your support 👍

**Comment by krmahadevan** [comment] 2022-06-14 09:19
Good to hear that. Closing this issue

**Closed by krmahadevan** 2022-06-14 09:19 UTC
