### ISSUE TITLE
testng always runs a test with shortest matching path

### ISSUE THREAD

**Issue by lukasj** [cbeust/testng#211] opened 2012-04-19 21:31 UTC
assume we have a project which has 2 tests - `b.ATest` and `a.b.ATest`

now run testng and use `-testclass a/b/ATest.java`

=> testng runs `b/Atest.java` instead

problem lies somewhere in `ClassHelper.fileToClass` and seems to be related to the use of `m_lastGoodRootIndex` field

see also related issue: http://netbeans.org/bugzilla/show_bug.cgi?id=211252

**Comment by krmahadevan** [comment] 2021-04-04 06:47
Not sure if this issue is still relevant in the latest released version of TestNG (`7.4.0` as of today) because TestNG accepts a fully qualified class name as a parameter value for `-testclass` and not file names and with fully qualified class names, I dont think we can have two classes with the same name.

So am closing this issue. If this issue is still a problem, please help share a sample that can be used to reproduce this issue.

**Closed by krmahadevan** 2021-04-04 06:47 UTC
