### ISSUE TITLE
Tests not run based on Groups when <groups> tag is at test level

### ISSUE THREAD

**Issue by QAthulhu** [cbeust/testng#2336] opened 2020-06-26 04:27 UTC
### TestNG Version
7.1.0

### Expected behavior
Only methods that match the provided Group are run

### Actual behavior
All methods in all classes are run. Groups are ignored

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```java
@Test(groups = {"foo"})
	public void testA() {
		System.out.println("foo test");
	}
	@Test(groups = {"bar"})
	public void testB() {
		System.out.println("bar test");
	}
```

test xml:
```xml
<suite name="Test suite" verbose="1" parallel="tests" thread-count="2" preserve-order="false">
	<groups>
		<run>
			<include name="foo" />
		</run>
	</groups>
	<test name="Test 1">
		<classes>
			<class name="myclass" />
		</classes>
	</test>
</suite>
```
If the groups tag is defined within the test tag, it works fine. However, I'm trying to build a test suite with multiple <tests> that are all using the same group. A workaround is simple moving the groups tag within each test but it just makes things too long/annoying when reading the test suite.

**Comment by krmahadevan** [comment] 2020-06-26 07:31
@QAthulhu - I am not able to reproduce this issue.

Test class

```java
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.Test;

public class SampleTestClass {

  @Test(groups = {"foo"})
  public void testA() {
    System.out.println("foo test");
    printSuite();
  }

  @Test(groups = {"bar"})
  public void testB() {
    System.out.println("bar test");
    printSuite();
  }

  private void printSuite() {
    System.err.println("Printing the suite being used");
    ITestResult result = Reporter.getCurrentTestResult();
    System.err.println(result.getTestContext().getCurrentXmlTest().getSuite().toXml());
  }
}

```

Suite xml 

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="SampleTestSuite" verbose="2" parallel="false" thread-count="1">
  <groups>
    <run>
      <include name="foo"/>
    </run>
  </groups>
  <test name="Test 1">
    <classes>
      <class name="com.rationaleemotions.github2336.SampleTestClass"/>
    </classes>
  </test>
</suite>
```

Execution output 

```
...
... TestNG 7.1.0 by Cédric Beust (cedric@beust.com)
...




foo test
Printing the suite being used
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="1" guice-stage="DEVELOPMENT" verbose="2" name="SampleTestSuite">
  <groups>
    <run>
      <include name="foo"/>
    </run>
  </groups>
  <test thread-count="1" verbose="2" name="Test 1">
    <classes>
      <class name="com.rationaleemotions.github2336.SampleTestClass"/>
    </classes>
  </test> <!-- Test 1 -->
</suite> <!-- SampleTestSuite -->



===============================================
SampleTestSuite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by QAthulhu** [comment] 2020-06-27 05:31
@krmahadevan thank you for your sample. It seems all tests are being run when I am running my test suite from within another test suite. I'll explain.

I run a main test suite like this:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Sanity Test Suite">
	<suite-files>
		<suite-file path="sanity-tests/suite.xml"></suite-file>
	</suite-files>
</suite>
```

The suite.xml can be your sample:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="SampleTestSuite" verbose="2" parallel="false" thread-count="1">
  <groups>
    <run>
      <include name="foo"/>
    </run>
  </groups>
  <test name="Test 1">
    <classes>
      <class name="com.rationaleemotions.github2336.SampleTestClass"/>
    </classes>
  </test>
</suite>
```

When I run the tests this way, I get this output:
```
foo test
Printing the suite being used
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="4" guice-stage="DEVELOPMENT" verbose="0" name="SampleTestSuite" parallel="tests">
  <test thread-count="4" verbose="0" name="Test 1" parallel="tests">
    <classes>
      <class name="ph.iwant.tests.authentication.SampleTestClass"/>
    </classes>
  </test> <!-- Test 1 -->
</suite> <!-- SampleTestSuite -->

bar test
Printing the suite being used
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="4" guice-stage="DEVELOPMENT" verbose="0" name="SampleTestSuite" parallel="tests">
  <test thread-count="4" verbose="0" name="Test 1" parallel="tests">
    <classes>
      <class name="ph.iwant.tests.authentication.SampleTestClass"/>
    </classes>
  </test> <!-- Test 1 -->
</suite> <!-- SampleTestSuite -->
```

I have moved the `groups` tag to the outer xml file and it has solved the problem!
Just wondering, is this the expected behavior or encouraged standard? Should I put parameters in the outer xml file as well?

**Comment by krmahadevan** [comment] 2020-07-05 15:42
@QAthulhu - TestNG is working as designed.

When you work with a suite of suites (Which is what you are using), the group definition should be present in the master group and that is what will get used for execution.

In your master suite, you dont have any group definitions created and that is why TestNG is running everything.

Closing this with resolution as **working as designed**

Relevant code snippet that you can refer to https://github.com/cbeust/testng/blob/b20ba401de49bc61795d20766f6307a8c6d5aa85/src/main/java/org/testng/xml/XmlSuite.java#L879-L888

**Closed by krmahadevan** 2020-07-05 15:42 UTC
Labels: Need: user answer, unable-to-reproduce
