### ISSUE TITLE
Getting error " Illegal reflective access by org.testng.xml.XMLParser" while adding testng xml using surefire plugin in pom.xml

### ISSUE THREAD

**Issue by jitendrakush** [cbeust/testng#2505] opened 2021-04-01 00:04 UTC
### TestNG Version
6.5.2

While adding testng xml using surefire plugin in pom.xml it is copying older version 6.5.2 into the local machine and its throwing an error and unable to complete the test

### Actual behavior
 WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.testng.xml.XMLParser (file:/C:/Users/kushw/.m2/repository/org/testng/testng/6.5.2/testng-6.5.2.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
[ERROR] WARNING: Please consider reporting this to the maintainers of org.testng.xml.XMLParser
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.01 s - in TestSuite

Please find code for pom.xml file.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>BuildManagmentMaven</groupId>
  <artifactId>MavenJava</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>My Awesome Application</name>

<build>
    <pluginManagement>
      <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
         <configuration>     				
          <suiteXmlFiles>
            <suiteXmlFile>testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration> 
      </plugin>
      </plugins>
    </pluginManagement>
  </build>
  
  <dependencies>
    
    
    
<dependency>
    <groupId>com.comcast.magic-wand</groupId>
    <artifactId>appium</artifactId>
    <version>4.0.3</version>
</dependency>
    
  
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>4.3.3</version>
    <scope>test</scope>
</dependency>
  
  
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.0.0-beta-2</version>
</dependency>
    
 							
   																													
  </dependencies>

</project>
```

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

 
### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment] 2021-04-01 02:53
@jitendrakush There is hardly any information that you have added that can help us debug this for you. 

Please do the following:

1. Try using the latest release of TestNG (`7.4.0` as of today)
2. If the problem persists then please help share a sample project that can be used to recreate the problem.

**Comment by jitendrakush** [comment] 2021-04-01 12:21
@krmahadevan, I have used latest version of TestNG (7.4.0) in my code only under dependency section but when i am including testng xml into build tag (In Surefire plugin) then its throwing error. As i have mentioned in the ticket. In the error as we can see its taking testng-6.5.2.jar and showing error.

please find below code for reference:-
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>LearnBuildManagement</groupId>
  <artifactId>LearnMaven</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>LearnMaven</name>
  <url>http://maven.apache.org</url>
  
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
         <configuration>     				
          <suiteXmlFiles>
            <suiteXmlFile>testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>  
      </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
  
    
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>4.3.3</version>
    <scope>test</scope>
</dependency>



  </dependencies>
</project>

**Comment by krmahadevan** [comment] 2021-04-01 12:29
@jitendrakush - The pom file shows that you have commented out TestNG `7.4.0` dependency.

So i am re-iterating what I had requested for earlier.

Please create a sample maven project that we can use to reproduce this problem and attach it as a dependency.

Also please let us know the output of `mvn --version` for your project (Basically need to know what JDK version you are using)

**Comment by jitendrakush** [comment] 2021-04-01 12:35
@krmahadevan When i am attaching testng latest version in dependency then its working perfectly. Only problem i am facing when i am including testng xml into surefire plugin using <configuration> tag then its throwing an error.

Please find below the details about versions.
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: E:\Work\SELENIUM\apache-maven-3.6.3\bin\..
Java version: 13.0.2, vendor: Oracle Corporation, runtime: C:\Program Files (x86)\Java\jdk-13

**Comment by krmahadevan** [comment] 2021-04-01 12:37
@jitendrakush sure. That is why I am requesting that you share a sample project so that I can reproduce the problem and find out what is going wrong.

**Comment by jitendrakush** [comment] 2021-04-01 12:59
@krmahadevan  sir i am a bit confuse about how to export my project and attach here. I am directly pasting zip file of my maven project but unable to upload it here. Could you please guide me on this.

**Comment by krmahadevan** [comment] 2021-04-01 13:02
@jitendrakush refer https://stackoverflow.com/questions/10963205/how-to-attach-file-to-a-github-issue

Just try doing the below. 

1. Create a sample project. 
2. Zip the project. 
3. Drag and drop it to the comment text box.

**Comment by jitendrakush** [comment] 2021-04-01 13:11
@krmahadevan I have attached my project in jitendrakush/MavenJava repository.

**Comment by krmahadevan** [comment] 2021-04-01 13:13
https://github.com/jitendrakush/MavenJava is it this project ?

**Comment by jitendrakush** [comment] 2021-04-01 13:15
@krmahadevan Yes :)

**Comment by krmahadevan** [comment] 2021-04-01 13:16
@jitendrakush if you were creating a repo u could have pushed code directly into GitHub instead of pushing a zip variant of it.

**Comment by jitendrakush** [comment] 2021-04-01 13:18
@krmahadevan heartly sorry for making you in trouble but i am not aware about this. Now onwards i will follow the approach you mentioned.

**Comment by jitendrakush** [comment] 2021-04-01 13:37
@krmahadevan i have pushed my code in this repository " jitendrakush/Test "
Thank you.

**Comment by krmahadevan** [comment] 2021-04-01 14:12
@jitendrakush 

I tried with your project and I am not able to reproduce the problem (I have cleaned up your pom file) I also noticed that you are using all junit annotations for your `@Test`. Please fix them.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>BuildManagmentMaven</groupId>
  <artifactId>MavenJava</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>My Awesome Application</name>

  <properties>
    <java.version>1.8</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
  </properties>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.0.0-M5</version>
          <configuration>            <!-- integration of surefire plugin with Using testng XML file  -->
            <suiteXmlFiles>
              <suiteXmlFile>testng.xml</suiteXmlFile>
            </suiteXmlFiles>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>7.4.0</version>
    </dependency>
  </dependencies>
</project>
```

Here's the output

```
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ MavenJava ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 3 source files to /Users/krmahadevan/Downloads/MavenJava/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ MavenJava ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
deleteTwitter
postJira
BrowserAutomation
elementsUi
IosApp
NativeAndroidApp
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.731 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.053 s
[INFO] Finished at: 2021-04-01T19:40:00+05:30
```

**Comment by krmahadevan** [comment] 2021-04-01 14:24
@jitendrakush - An example of your tests using JUnit annotations is [here](https://github.com/jitendrakush/Test/blob/master/MavenJava/src/test/java/BuildManagmentMaven/AppiumTest.java#L3)

**Comment by krmahadevan** [comment] 2022-01-07 06:32
Closing this issue since there has been no further update from the user on this.

**Closed by krmahadevan** 2022-01-07 06:32 UTC
Labels: Need: user answer, Need: sample
