### ISSUE TITLE
Priority combined with method dependencies cannot be run in a bunch

### ISSUE THREAD

**Issue by Tikani** [cbeust/testng#1794] opened 2018-05-18 10:43 UTC
### TestNG Version
6.14.3

### Expected behavior
Methods, marked with @Test(priority=N, dependsOnMethods={X,Y,Z,...}) must ALL be run, according to the following directives in testng.xml (as below)

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Request INT" verbose="3">
    <test name="RequestInt">
        <classes>
            <class name="requestIntNew.AddingApprover"/>
            <class name="requestIntNew.RejectOrderByManagerOrApprover"/>
            <class name="requestIntNew.DelegateTaskByApprover"/>
        </classes>
    </test>
</suite>
```
i.e. all test methods in all test classes are marked in the way mentioned above.

### Actual behavior
In IntelliJ IDEA only the first method (which has only _priority=1_ and does not have dependencies on other methods) is executed.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

```java
@ContextConfiguration(classes = SpringConfiguration.class)
public class AddingApprover extends AbstractTestNGSpringContextTests 
{
   @Test(priority=1)
    public void createOrder()
    {
    }
    @Test(priority=2, dependsOnMethods = "createOrder")
    public void approveByManager()
    {
    }
    @Test(priority=3, dependsOnMethods = "approveByManager")
    public void addApprover()
   {
    }
}
```
Other 2 classes within a package look the same.

**Comment by krmahadevan** [comment] 2018-05-18 11:53
@Tikani - The IntelliJ TestNG plugin is not owned by the TestNG team. Do you see the same behavior when you run your test from a command line or via a build tool such as Gradle (or) Maven ?

Also please help add a bit more context. Are you saying that when you run the suite xml file, you only see `AddingApprover.createOrder()` being executed and all other methods are getting skipped ? Please clarify.

**Comment by Tikani** [comment] 2018-05-18 13:04
I can't say anything about running from console, because manual classpath setup seems very complicated because of tons of test dependencies, but as for experiment I set up maven-surefire-plugin TestNG runner and yes, I can reproduce this issue here too.
About context clarifying: yes, you are absolutely right.  Only the first methods from AddingApprover, RejectOrderByManagerOrApprover, DelegateTaskByApprover are being executed and all other methods are getting skipped.

**Comment by juherr** [comment] 2018-05-23 12:15
Are you seeing the same issue with maven?

When you say "skip", you mean "not run" or "marked as skip in reports"?

**Comment by Tikani** [comment] 2018-05-23 17:53
@juherr, yes, as I mentioned above, I set up _maven-surefire-plugin_ TestNG runner and yes, I can reproduce this issue here too.
When I say "skip", I mean "not run at all". Reports have logs only about one \@Test method (which is not annotated with _dependsOnMethods_, because it is the first (root) method in a chain of \@test methods)  executed from each class.

**Comment by juherr** [comment] 2018-05-27 19:59
@krmahadevan Are you able to reproduce with maven or IntelliJ?

**Comment by krmahadevan** [comment] 2018-05-28 02:44
@juherr - I tried using TestNG `6.14.3` and I can't reproduce this problem.
I have tried the following 
1. Create a suite xml, right click on it and run it via IntelliJ.
2. Create a Runner class (similar to what our unit tests would have) and run the test from within that in IntelliJ.
3. Create a suite xml, and run that via maven.

Here's the samples that I used:

**Test classes**

```java
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.Test;

public class AddingApprover {
  @Test(priority = 1)
  public void createOrder() {
    printer();
  }

  @Test(priority = 2, dependsOnMethods = "createOrder")
  public void approveByManager() {
    printer();
  }

  @Test(priority = 3, dependsOnMethods = "approveByManager")
  public void addApprover() {
    printer();
  }

  static void printer() {
    ITestResult result = Reporter.getCurrentTestResult();
    String classname = result.getMethod().getTestClass().getName();
    String methodname = result.getMethod().getMethodName();
    String msg = String.format("Executing %s.%s()", classname, methodname);
    System.err.println(msg);
  }
}
```
```java
import static com.rationaleemotions.github.issue1794.AddingApprover.printer;

import org.testng.annotations.Test;

public class DelegateTaskByApprover {
  @Test(priority = 1)
  public void deletegateTaskCreateOrder() {
    printer();
  }

  @Test(priority = 2, dependsOnMethods = "deletegateTaskCreateOrder")
  public void deletegateTaskApproveByManager() {
    printer();
  }

  @Test(priority = 3, dependsOnMethods = "deletegateTaskApproveByManager")
  public void delegateTaskAddApprover() {
    printer();
  }
}
```
```java
import static com.rationaleemotions.github.issue1794.AddingApprover.printer;

import org.testng.annotations.Test;

public class RejectOrderByManagerOrApprover {
  @Test(priority = 1)
  public void rejectOrderCreateOrder() {
    printer();
  }

  @Test(priority = 2, dependsOnMethods = "rejectOrderCreateOrder")
  public void rejectOrderApproveByManager() {
    printer();
  }

  @Test(priority = 3, dependsOnMethods = "rejectOrderApproveByManager")
  public void rejectOrderAddApprover() {
    printer();
  }
}
```

**Runner class**
```java
import java.util.Collections;
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

public class IssueTest {

  @Test
  public void testMethod() {
    XmlSuite xmlSuite = new XmlSuite();
    xmlSuite.setVerbose(3);
    xmlSuite.setName("1794_suite");
    XmlTest xmlTest = new XmlTest(xmlSuite);
    xmlTest.setName("1794_test");
    xmlTest.getClasses().add(new XmlClass(AddingApprover.class));
    xmlTest.getClasses().add(new XmlClass(DelegateTaskByApprover.class));
    xmlTest.getClasses().add(new XmlClass(RejectOrderByManagerOrApprover.class));
    System.err.println(xmlSuite.toXml());
    TestNG testng = new TestNG();
    testng.setXmlSuites(Collections.singletonList(xmlSuite));
    testng.run();
  }

}
```

**Suite xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite verbose="3" name="1794_suite">
  <test thread-count="5" verbose="3" name="1794_test">
    <classes>
      <class name="com.rationaleemotions.github.issue1794.AddingApprover"/>
      <class name="com.rationaleemotions.github.issue1794.DelegateTaskByApprover"/>
      <class name="com.rationaleemotions.github.issue1794.RejectOrderByManagerOrApprover"/>
    </classes>
  </test> <!-- 1794_test -->
</suite> <!-- 1794_suite -->
```

**Sample output**
```
...
... TestNG 6.14.3 by Cédric Beust (cedric@beust.com)
...
Executing com.rationaleemotions.github.issue1794.AddingApprover.createOrder()
Executing com.rationaleemotions.github.issue1794.DelegateTaskByApprover.deletegateTaskCreateOrder()
Executing com.rationaleemotions.github.issue1794.RejectOrderByManagerOrApprover.rejectOrderCreateOrder()
Executing com.rationaleemotions.github.issue1794.AddingApprover.approveByManager()

Executing com.rationaleemotions.github.issue1794.DelegateTaskByApprover.deletegateTaskApproveByManager()
Executing com.rationaleemotions.github.issue1794.RejectOrderByManagerOrApprover.rejectOrderApproveByManager()

Executing com.rationaleemotions.github.issue1794.AddingApprover.addApprover()
Executing com.rationaleemotions.github.issue1794.DelegateTaskByApprover.delegateTaskAddApprover()
===== Invoked methods
    AddingApprover.createOrder()[pri:1, instance:com.rationaleemotions.github.issue1794.AddingApprover@26a7b76d] 648525677
    DelegateTaskByApprover.deletegateTaskCreateOrder()[pri:1, instance:com.rationaleemotions.github.issue1794.DelegateTaskByApprover@4abdb505] 1253946629
    RejectOrderByManagerOrApprover.rejectOrderCreateOrder()[pri:1, instance:com.rationaleemotions.github.issue1794.RejectOrderByManagerOrApprover@7ce6a65d] 2095490653
    AddingApprover.approveByManager()[pri:2, instance:com.rationaleemotions.github.issue1794.AddingApprover@26a7b76d] 648525677
    DelegateTaskByApprover.deletegateTaskApproveByManager()[pri:2, instance:com.rationaleemotions.github.issue1794.DelegateTaskByApprover@4abdb505] 1253946629
    RejectOrderByManagerOrApprover.rejectOrderApproveByManager()[pri:2, instance:com.rationaleemotions.github.issue1794.RejectOrderByManagerOrApprover@7ce6a65d] 2095490653
    AddingApprover.addApprover()[pri:3, instance:com.rationaleemotions.github.issue1794.AddingApprover@26a7b76d] 648525677
    DelegateTaskByApprover.delegateTaskAddApprover()[pri:3, instance:com.rationaleemotions.github.issue1794.DelegateTaskByApprover@4abdb505] 1253946629
    RejectOrderByManagerOrApprover.rejectOrderAddApprover()[pri:3, instance:com.rationaleemotions.github.issue1794.RejectOrderByManagerOrApprover@7ce6a65d] 2095490653
=====
===============================================
1794_suite
Total tests run: 9, Failures: 0, Skips: 0
===============================================

Executing com.rationaleemotions.github.issue1794.RejectOrderByManagerOrApprover.rejectOrderAddApprover()

Process finished with exit code 0

```

**Comment by krmahadevan** [comment] 2018-05-30 03:12
@Tikani - Please review my sample and let me know if it differs from what you are using. If its not, please feel free to alter it and attach it here.

PS : Please exclude any third party dependency (Spring/Selenium etc., ) when you provide the sample.

**Comment by krmahadevan** [comment] 2018-05-31 13:51
ping @Tikani . Any updates ?

**Comment by Tikani** [comment] 2018-05-31 20:31
@krmahadevan sorry, i can't reproduce this issue without Spring and Selenium too. Maybe it happens because of cross-influence of them. Sorry for cosidering that it was completely TestNG's fault.

**Comment by krmahadevan** [comment] 2018-06-01 02:19
Closing this issue based on @Tikani comments.

**Closed by krmahadevan** 2018-06-01 02:19 UTC
Labels: Need: sample, Need: user answer
