### ISSUE TITLE
java.util.ConcurrentModificationException after testng upgrade to 7.0.0-beta3

### ISSUE THREAD

**Issue by hnestorova** [cbeust/testng#2095] opened 2019-06-19 08:58 UTC
### TestNG Version
7.0.0-beta3

### Expected behavior
all tests classes run successfully as with testng 16.4.3

### Actual behavior
some test classes get skipped and in Jenkins console we see:
[testng] Exception in thread "TestNG-test=X-3" Exception in thread "TestNG-test=X-2" java.util.ConcurrentModificationException
[testng] 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[testng] 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:162)
[testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
[testng] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 [testng] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 [testng] 	at java.base/java.lang.Thread.run(Thread.java:834)
[testng] java.util.ConcurrentModificationException
 [testng] 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
 [testng] 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:162)
  [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
 [testng] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 [testng] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 [testng] 	at java.base/java.lang.Thread.run(Thread.java:834)

### Test case sample
The testng xml looks like:

<suite name="Access Google" parallel="classes" thread-count="7">
	<parameter name="baseUrl" value="http://google.com"/>
	<parameter name="serverURL" value="http://PRIVATE:4444/wd/hub"/>
	<parameter name="browserName" value="internet explorer"/>

	<test verbose="1" name="Access Google" annotations="JDK">
			<classes>
			<class name="PRIVATE.tests.Google"/>
			<class name="PRIVATE.tests.Google1"/>
			<class name="PRIVATE.tests.Google2"/>
			<class name="PRIVATE.tests.Google3"/>
			<class name="PRIVATE.tests.Google4"/>
			<class name="PRIVATE.tests.Google5"/>
			<class name="PRIVATE.tests.Google6"/>
			<class name="PRIVATE.tests.Google7"/>
			<class name="PRIVATE.tests.Google8"/>
			<class name="PRIVATE.tests.Google9"/>
			<class name="PRIVATE.tests.Google10"/>
			</classes>
	</test>
	<test verbose="1" name="Access Yahoo" annotations="JDK">
			<classes>
			<class name="PRIVATE.tests1.Yahoo"/>
			<class name="PRIVATE.tests1.Yahoo1"/>
			<class name="PRIVATE.tests1.Yahoo2"/>
			</classes>
	</test>
	<listeners>
			<listener class-name="PRIVATE.tests.ScreenshotListener"/>
    </listeners>
</suite>

**Comment by krmahadevan** [comment] 2019-06-20 02:39
This is a duplicate of https://github.com/cbeust/testng/issues/2000

#2000 has been fixed. Please try again with the latest released version of TestNG viz., `7.0.0-beta5`.

PS: You may need to add a repository entry to refer to JCenter as well.

This [SO](https://stackoverflow.com/questions/44265547/how-to-properly-specify-jcenter-repository-in-maven-config) post should give you some help, if you are looking for any, with respect to specifying JCenter repository in your pom file.

**Closed by krmahadevan** 2019-06-20 02:39 UTC
