### ISSUE TITLE
TestNG 7.0.0 with scala 2.12.8

### ISSUE THREAD

**Issue by alexfel** [cbeust/testng#2185] opened 2019-10-30 06:32 UTC
### TestNG Version
> Note: only the latest version is supported

### I've just upgraded my testNG project from scala 2.11.11 to 2.12.8 with testNG 7.0.0.
I have a case of @test method in a class A that implements trait B that implements trait C and both B+C have @beforemethod methods. Before the upgrade the @beforemethod methods order was C->B->A as expected

### Actual behavior

 After the upgrade when i execute the test the order of the @beforetest methods is now mixed and executed twice
### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by alexfel** [comment] 2019-10-30 14:58
BTW, it works just fine with testNG 6.14.3. Seems like the issue is with 7.0.0

**Comment by krmahadevan** [comment] 2019-11-08 17:21
@alexfel - Do you have a sample that can be used to simulate this issue? I am not that familiar with scala, so please feel free to add any extra information that can be used (how you are running your test etc.,)

**Comment by alexfel** [comment] 2019-11-13 07:30
> @alexfel - Do you have a sample that can be used to simulate this issue? I am not that familiar with scala, so please feel free to add any extra information that can be used (how you are running your test etc.,)

Hi,
Thanks for your response.
So I’m basically having SBT Scala project within IntelliJ and just upgraded to Scala 2.12.8 from 2.11.11 and using testNG 6.14.3. (sbt.version=1.0.4)
I have a class A with @test method a1 that extends class B where class B extends/implement traits C and D that both extends base class E. C,D and E has @beforeMethod methods. When I try to update to testNG 7.0.0 and test a1 is executed - the @beforeMethods methods execution order is unexpected and even more, executed twice :/

Please assist

**Comment by juherr** [comment] 2020-01-03 18:50
@alexfel Could you tell us if the issue comes from your scala `2.11 -> 2.12` upgrade or your testng `6.14 -> 7.0` upgrade?

It looks like the behavior you describe is similar than https://github.com/cbeust/testng/issues/2209

**Comment by alexfel** [comment] 2020-01-22 16:38
> @alexfel Could you tell us if the issue comes from your scala `2.11 -> 2.12` upgrade or your testng `6.14 -> 7.0` upgrade?
> 
> It looks like the behavior you describe is similar than #2209

Sorry for the late response - 
The Scala upgrade.

**Comment by krmahadevan** [comment] 2022-01-07 07:17
Closing this issue. Please check if the problem is persistent with the latest released TestNG version (`7.5`). If the problem persists, please share a sample that can be used to reproduce the problem.

**Closed by krmahadevan** 2022-01-07 07:17 UTC
Labels: Need: sample
