### ISSUE TITLE
@BeforeClass doesn't get run on class with @Factory method -- expected behavior?

### ISSUE THREAD

**Issue by jedwards1211** [cbeust/testng#475] opened 2014-01-15 23:01 UTC
Here's a distilled version of my code: the parent class launches my GUI program in the init() method, and then the factory method creates inner test classes that access the GUI via the parent class instance.  TestNG didn't handle this how I expected; 1) did TestNG execute it properly?  2) Is there a better way for me to tie all the factory-created tests to the same GUI instance?

```java
public class TestFactory {
    @BeforeClass
    public void init() {
        System.out.println("BeforeClass");
    }

    @Factory
    public Object[] createTests() {
        System.out.println("Factory");
        return new Object[] { new Test1("GOOG"), new Test1("FB") };
    }

    public void enterSymbol(String symbol) {
        System.out.format("TestFactory %x: entering %s\n", hashCode(), symbol);
    }

    public class Test1 {
        private String  symbol;

        public Test1(String symbol) {
            this.symbol = symbol;
        }

        @Test
        public void test() {
            System.out.println("Test1(" + symbol + ")");
        }
    }
}
```

Output:

```
Factory
[TestNG] Running:
  C:\Users\james.a.edwards\AppData\Local\Temp\testng-eclipse--1490678808\testng-customsuite.xml

Test1(FB)
TestFactory 1264eab: entering FB
Test1(GOOG)
TestFactory 1264eab: entering GOOG
PASSED: test
PASSED: test
```

Expected Output:

```
BeforeClass
Factory
[TestNG] Running:
  C:\Users\james.a.edwards\AppData\Local\Temp\testng-eclipse--1490678808\testng-customsuite.xml

Test1(FB)
TestFactory 1264eab: entering FB
Test1(GOOG)
TestFactory 1264eab: entering GOOG
PASSED: test
PASSED: test
```

**Comment by krmahadevan** [comment] 2020-11-16 06:14
Closing this issue with resolution as **Working as designed** because the example shared is not a correct one. `@BeforeClass` will be executed only if the class has atleast one `@Test` method. If this is still a problem, please share a proper example that can be used to reproduce the problem.

**Closed by krmahadevan** 2020-11-16 06:14 UTC
