### ISSUE TITLE
ConcurrentModificationException when running tests concurrently 

### ISSUE THREAD

**Issue by thiagoh** [cbeust/testng#598] opened 2015-01-26 18:10 UTC
I have around five methods all of them with the following configuration 
`@Test(threadPoolSize = 4, invocationCount = 10, timeOut = 10000)`

When I run the tests I get this error

```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at org.testng.reporters.TestHTMLReporter.generateTable(TestHTMLReporter.java:78)
    at org.testng.reporters.TestHTMLReporter.generateLog(TestHTMLReporter.java:312)
    at org.testng.reporters.TestHTMLReporter.onFinish(TestHTMLReporter.java:40)
    at org.testng.TestRunner.fireEvent(TestRunner.java:1241)
    at org.testng.TestRunner.afterRun(TestRunner.java:1032)
    at org.testng.TestRunner.run(TestRunner.java:621)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

**Comment by krmahadevan** [comment] 2015-02-01 15:28
@thiagoh 
I tried recreating this issue and I haven't been able to do so.

Here's how my sample code looks like 

```java
public class TestNGIssue598 {
    public TestNGIssue598 () {
        System.out.println (
            "Working with TestNG " + TestNG.class.getProtectionDomain ().getCodeSource ().getLocation ());
    }

    @Test (threadPoolSize = 4, invocationCount = 10, timeOut = 10000)
    public void test1 () {
        System.out.println ("Running test1");
    }

    @Test (threadPoolSize = 4, invocationCount = 10, timeOut = 10000)
    public void test2 () {
        System.out.println ("Running test2");
    }

    @Test (threadPoolSize = 4, invocationCount = 10, timeOut = 10000)
    public void test3 () {
        System.out.println ("Running test3");
    }

    @Test (threadPoolSize = 4, invocationCount = 10, timeOut = 10000)
    public void test4 () {
        System.out.println ("Running test4");
    }

    @Test (threadPoolSize = 4, invocationCount = 10, timeOut = 10000)
    public void test5 () {
        System.out.println ("Running test5");
    }
}
```

Here's how my suite xml looks like 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="A Simple Suite" parallel="false" verbose="10" thread-count="2">
    <listeners>
        <listener class-name="org.testng.reporters.TestHTMLReporter"/>
    </listeners>
    <test name="A Simple Test" verbose="5">
        <classes>
            <class name="rationale.emotions.testng.TestNGIssue598"/>
        </classes>
    </test>
</suite>

```

Can you please help provide a sample that can reproduce this problem ?

I attempted at recreating this using the latest released version of TestNG viz., 6.8.17

**Comment by krmahadevan** [comment] 2017-09-20 03:13
Closing this issue because this issue is not reproducible anymore. Please re-open if its still a problem.

**Closed by krmahadevan** 2017-09-20 03:13 UTC
