### ISSUE TITLE
Getting this error whenever I try to run the testcase using TestNG version 7.0.1...Please help me out on this...

### ISSUE THREAD

**Issue by Anushapathi92** [cbeust/testng#2286] opened 2020-03-29 03:46 UTC
### TestNG Version
> Note: only the latest version is supported

[RemoteTestNG] detected TestNG version 7.0.1
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ Yes] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
package demo;

import org.testng.annotations.Test;

public class day1 {

	@Test
	public void color_Red() {
		System.out.println("Color is red");
	}
	
	@Test
	public void color_Blue() {
		System.out.println("Color is Blue");
	}
	
	@Test
	public void White() {
		System.out.println("White Color");
	}
}

**Comment by krmahadevan** [comment] 2020-03-29 04:21
Duplicate of https://github.com/cbeust/testng/issues/2223

The latest TestNG eclipse plugin should be fixing it. If this is still a problem, please file an issue in https://github.com/cbeust/testng-eclipse project which tracks Eclipse TestNG plugin issues.

**Closed by krmahadevan** 2020-03-29 04:21 UTC
