### ISSUE TITLE
Groups specified at the class level are overridden since version 6.11

### ISSUE THREAD

**Issue by gdemecki** [cbeust/testng#1446] opened 2017-06-06 04:30 UTC
### TestNG Version

6.11

### Expected behavior

I've noticed that in case:

```java
@Test(groups = "functional-tests")
public class SomeIT {

    @Test(groups = "another-group")
    public void this_method_should_be_also_part_of_the_functional_tests_group() {
        // but it's not since TestNG 6.11
    }
}
```

the method only belongs to the group called `another-group`. This breaks backward compatibility.
Was this an intentional change?

### Actual behavior

AFAIK in every TestNG version so far, groups specified at the class level are preserved when using     `@Test(groups = "some-additional-group")` at the method level.

### Is the issue reproductible on runner?

- [x ] Maven

### Test case sample

> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment] 2017-06-06 04:42
@gdemecki - Can you please help call out which version of TestNG this was working fine ? Maybe it was a discrepancy that got fixed.

I think the current behavior is what is supposed to be the correct one because method level `@Test` annotations should override class level `@Test` annotation values instead of trying to make a union of values. Currently for e.g., the `enabled=false` attribute when set at the class level, gets overridden by the same attribute at method level. So I think its correct that TestNG now does the same with the other attributes as well.

**Comment by gdemecki** [comment] 2017-06-07 09:40
Hi @krmahadevan, @juherr 

>  Can you please help call out which version of TestNG this was working fine 

TestNG version 6.9.10 and every version below.

> I think the current behavior is what is supposed to be the correct one

That's your opinion. Sorry, but my is exactly the opposite. TestNG didn't work this way before. Also JUnit old, known behaviour is exactly the opposite (sorry for this comparison).

> Currently for e.g., the `enabled=false` attribute when set at the class level, gets overridden by the same attribute at method level. 

That's a bad example, because `enabled` attribute can only have two **mutually exclusive values**: true/ false. So it's natural, that the last value *overrides* previous ones.

When it comes to attributes which can have multiple values (exactly like `groups` can), the most natural behaviour for me is to have a *union of values*. And that's not only for me, ask people around, look at the JUnit etc.
IMHO this is also the most practical behaviour, because please think what would happen if such values were not combined? Developer would have to do quite a lot of repetitive work.

And last but not least:

> Maybe it was a discrepancy that got fixed.

**Even** if it was intended & commonly agreed IMHO it's a really big change, and should not be done in a `minor` TestNG version release.

Regards

**Comment by juherr** [comment] 2017-06-07 11:51
Both behaviors are valid to me but I feel the overriding one is better because it is easier to understand/explain/implement.

> think what would happen if such values were not combined? Developer would have to do quite a lot of repetitive work.
They will have more work if they don't want it ;)

But in both cases, we should be able to work around with an IAnnotationTransformer.

BTW, if the regression is confirmed, I agree we should not change the behavior before a major version.

@krmahadevan Could you confirm the regression? If confirmed, an appropriate IAnnotationTransformer could be used by default (and skipped with a system property).

**Comment by krmahadevan** [comment] 2017-06-07 13:01
@gdemecki 

Are you sure this was broken ? I tried using the following and I am not able to reproduce this error.

Both 

- AnotherSampleClass.java and 
- SampleClass.java

reside in the package `com.rationaleemotions.github.issue1446`

```java
import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

@Test(groups = "functional-tests")
public class SampleClass {
    @Test(groups = "another-group")
    public void helloWorld() {
        ITestResult result = Reporter.getCurrentTestResult();
        List<String> actual = Arrays.asList(result.getMethod().getGroups());
        List<String> expected = Arrays.asList("functional-tests", "another-group");
        Reporter.log(result.getMethod().getMethodName() + "() belongs to " + actual + " groups.", true);
        Collections.sort(expected);
        Collections.sort(actual);
        Assert.assertEquals(actual, expected);
    }
}
```

```java
import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

@Test(groups = "functional-tests")
public class AnotherSampleClass {
    @Test(groups = "another-group")
    public void goodbyeWorld() {
        ITestResult result = Reporter.getCurrentTestResult();
        List<String> actual = Arrays.asList(result.getMethod().getGroups());
        List<String> expected = Arrays.asList("functional-tests", "another-group");
        Reporter.log(result.getMethod().getMethodName() + "() belongs to " + actual + " groups.", true);
        Collections.sort(expected);
        Collections.sort(actual);
        Assert.assertEquals(actual, expected);
    }
}
```

Suite xml is as below
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="1446_Suite" verbose="2">
    <test name="1446_Test" parallel="methods">
        <groups>
            <run>
                <include name="functional-tests"/>
            </run>
        </groups>
        <packages>
            <package name="com.rationaleemotions.github.issue1446"/>
        </packages>
    </test>
</suite>
```

**TestNG 6.11 output**

```
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...
goodbyeWorld() belongs to [another-group, functional-tests] groups.
helloWorld() belongs to [another-group, functional-tests] groups.

===============================================
1446_Suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================
```

**TestNG 6.10 output**

```
...
... TestNG 6.10 by Cédric Beust (cedric@beust.com)
...

[TestNG] Running:
  /Users/krmahadevan/githome/PlayGround/testbed/src/test/resources/1446.xml
[TestRunner] Starting executor for test 1446_Test with time out:2147483647 milliseconds.
helloWorld() belongs to [another-group, functional-tests] groups.
goodbyeWorld() belongs to [another-group, functional-tests] groups.

===============================================
1446_Suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================
```

**TestNG 6.9.13.6 output**

```
...
... TestNG 6.9.13.6 by Cédric Beust (cedric@beust.com)
...

[TestNG] Running:
  /Users/krmahadevan/githome/PlayGround/testbed/src/test/resources/1446.xml
[TestRunner] Starting executor for test 1446_Test with time out:2147483647 milliseconds.
helloWorld() belongs to [another-group, functional-tests] groups.
goodbyeWorld() belongs to [another-group, functional-tests] groups.

===============================================
1446_Suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================
```

**Comment by krmahadevan** [comment] 2017-09-21 11:04
@juherr - Do you think we can close this issue ?

**Comment by juherr** [comment] 2017-09-21 12:01
@gdemecki Please reopen the issue if you have more details to share. Currently, we are not able to reproduce the problem.

**Closed by juherr** 2017-09-21 12:01 UTC
Labels: Feature: groups

**Comment by gaponte1985** [comment] 2017-09-26 18:36
is not working for me I have 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">
  <groups>
    <run>
    <include name="Perf Testing"/>
    </run>
  </groups>
  <test name="Test">
    <packages>
      <package name="com.gateway.salesforce.testng.testcases"/>
      <package name="com.gateway.salesforce.dataObjects"/>
    </packages>
  </test> 
</suite> 


I also have a baseclass with a couple before methods

**Comment by gaponte1985** [comment] 2017-09-26 18:36
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">
  <groups>
    <run>
    <include name="Perf Testing"/>
    </run>
  </groups>
  <test name="Test">
    <packages>
      <package name="com.gateway.salesforce.testng.testcases"/>
      <package name="com.gateway.salesforce.dataObjects"/>
    </packages>
  </test> 
</suite>

**Comment by gaponte1985** [comment] 2017-09-26 18:37
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">
  <groups>
    <run>
    <include name="Perf Testing"/>
    </run>
  </groups>
  <test name="Test">
    <packages>
      <package name="com.gateway.salesforce.testng.testcases"/>
      <package name="com.gateway.salesforce.dataObjects"/>
    </packages>
  </test> 
</suite>

**Comment by gaponte1985** [comment] 2017-09-26 18:40
[testng.txt](https://github.com/cbeust/testng/files/1334490/testng.txt)

**Comment by gaponte1985** [comment] 2017-09-26 18:40
is not picking up the base class... what I can i do ?

**Comment by krmahadevan** [comment] 2017-09-27 05:27
@gaponte1985 - Please add a bit more context to the issue that you are facing (by adding sample test which can be used to reproduce the issue etc.,).

**Comment by gaponte1985** [comment] 2017-09-27 19:03
I find the soluction just group the before and after methods and add to the xml file

**Comment by gdemecki** [comment] 2017-10-04 13:27
Thanks @krmahadevan and @juherr.
I was wrong with this bug report. Groups indeed work fine. 

After deeper analysis, I've found out that my unit tests are skipped, not because of groups being overridden (what I initially thought) but due to a `priority` attribute combined with groups, which apparently got broken recently.

Sorry for this false bug report. I've opened a new one here: #1565
