### ISSUE TITLE
RetryAnalyzer doesn't work at testng 7.1.0

### ISSUE THREAD

**Issue by biletsky** [cbeust/testng#2289] opened 2020-04-01 12:31 UTC
### TestNG Version 7.1.0
> Note: only the latest version is supported

### Expected behavior
RetryAnalyzer works at testng 7.1.0 version

### Actual behavior
RetryAnalyzer dosen't work at testng 7.1.0 version

### Is the issue reproductible on runner?
If I use testng  6.9.13.6 version, then everything works . If I use @Test(retryAnalyzer = Retry.class), then everything works, but if I use listeners and testng 7.1.0, then restarting the failed tests does not work
- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

```java
public class AnnotationTransformer implements IAnnotationTransformer {

    @Override
    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor,
        Method testMethod) {
        annotation.setRetryAnalyzer(RetryAnalyzer.class);
    }

public class RetryAnalyzer implements IRetryAnalyzer {

    private int count = 0;

    @Override public boolean retry(ITestResult iTestResult) {
        if (!iTestResult.isSuccess()) {                     
            int maxTry = 2;
            if (count < maxTry) {                            
                count++;                                     
                iTestResult.setStatus(ITestResult.FAILURE); 

                iTestResult.getTestContext().getFailedTests().removeResult(iTestResult);

                return true;                                 
            } else {
                iTestResult
                    .setStatus(ITestResult.FAILURE);
            }
        } else {
            iTestResult
                .setStatus(ITestResult.SUCCESS);      
        }
        return false;
    }
}
```

and Testng.xml

```xml
  <listeners>
        <listener class-name="utils.AnnotationTransformer"/>
    </listeners>
```

**Comment by krmahadevan** [comment] 2020-04-01 13:04
@biletsky - Its not clear what is not working. Can you please elaborate a bit more? Are you saying that when you use the attached retry analyser, then the retry doesn't happen when you use TestNG `7.1.0` ?

**Comment by biletsky** [comment] 2020-04-01 13:21
Yes, if use 7.1.0 retry doesn't work, but if I used 6.9.13.6 version, everything worked.

**Comment by krmahadevan** [comment] 2020-04-01 17:16
@biletsky - Not sure what you are talking about.

The below sample demonstrates that this works fine using TestNG `7.1.0`

### Test class

```java
import org.testng.Assert;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(LocalReporter.class)
public class SampleTestCase {

  int count = 0;

  @Test(retryAnalyzer = RetryAnalyzer.class)
  public void testMethod() {
    if (count++ < 2) {
      Assert.fail("Failing because count is still less than 2");
    }
  }
}
```

### Retry analyser 
```java
import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;

public class RetryAnalyzer implements IRetryAnalyzer {

  private int count = 0;

  @Override
  public boolean retry(ITestResult iTestResult) {
    int maxTry = 2;
    if (count < maxTry) {
      count++;
      return true;
    }
    return false;
  }
}
```

### Reporting listener
```java
import java.util.List;
import org.testng.IReporter;
import org.testng.ISuite;
import org.testng.ITestContext;
import org.testng.xml.XmlSuite;

public class LocalReporter implements IReporter {

  @Override
  public void generateReport(
      List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
    suites.stream()
        .flatMap(each -> each.getResults().values().stream())
        .forEach(
            eachResult -> {
              ITestContext ctx = eachResult.getTestContext();
              System.err.println("Printing skipped tests");
              ctx.getSkippedTests()
                  .getAllResults()
                  .forEach(skipped -> System.err.println(skipped.getMethod().getQualifiedName()));
              System.err.println("Printing failed tests");
              ctx.getFailedTests()
                  .getAllResults()
                  .forEach(failed -> System.err.println(failed.getMethod().getQualifiedName()));
              System.err.println("Printing passed tests");
              ctx.getPassedTests()
                  .getAllResults()
                  .forEach(passed -> System.err.println(passed.getMethod().getQualifiedName()));
            });
  }
}
```

### Suite xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="2289_suite" verbose="2">
    <test name="2289_test" verbose="2">
        <classes>
            <class name="com.rationaleemotions.github.issue2289.SampleTestCase"/>
        </classes>
    </test>
</suite>
```

### Output

```
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 7.1.0 by Cédric Beust (cedric@beust.com)
...

Printing skipped tests
com.rationaleemotions.github.issue2289.SampleTestCase.testMethod
com.rationaleemotions.github.issue2289.SampleTestCase.testMethod
Printing failed tests
Printing passed tests
com.rationaleemotions.github.issue2289.SampleTestCase.testMethod
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.715 s - in TestSuite
```

As you can see from the above, the test is being retried twice and the retried attempts are being marked as **skipped** since the test eventually **passed**

**Note**
The `org.testng.IRetryAnalyzer` implementation gets passed with a new instance of `ITestResult` object for every retry attempt.

**Closed by krmahadevan** 2020-04-01 17:16 UTC
Labels: Feature: retry-analyzer, Needs Query to be answered

**Comment by biletsky** [comment] 2020-04-01 18:19
I do not need to specify “@Test(retryAnalyzer = Retry.class)” this annotation. We can just only use @Test annotation without retryAnalyzer attribute. 
I add also this listener in TestNG.xml file.
`

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="TestNG Listener Example"> 
   <listeners>       
   <listener class-name="AnnotationTransformer"/>    
</listeners>     
<test name="TestNG Sample Test" preserve-order="true">        <classes>         
   <class name="SampleTest">            </class>      
  </classes>   
 </test>
</suite>

`
The listener may not work. If I add  this annotation “@Test(retryAnalyzer = Retry.class)”  to tests then everything works.

Why listener doesn't work?I need to add this “@Test(retryAnalyzer = Retry.class)” to every test?

**Comment by VladShapeshifter** [comment] 2024-07-06 21:45
@biletsky I faced same issue as you and found some solution. The thing is to make TestNG listener work with Maven we should adjust maven-surefire-plugin. I think @krmahadevan meant to run tests with RetryAnalizer (w/o listener approach), directly specifying it in test annotation for test method, OR using not Maven command line, but TestNG directly (w/ listener approach). If we run tests with specified listener in testng.xml file using TestNG everything works fine - tests are retried (you can try to run testng.xml file directly from your IDE). At the same time, if we need to run tests using Maven command line, we can't do that w/o properly configured maven-surefire-plugin in pom.xml file that is used to connect TestNG framework with Maven build tool. So in order to run tests using Maven command line we should add our listeners (RetryListener that implements IAnnotationTransformer and/or some other listener e.g. implementation of ITestListener) to <configuration> -> <preperties> section for maven-surefire-plugin in <build> section, i.e.
```
<configaration>
    <properties>
        <property>
            <name>listener</name>
            <value>path.to.your.listener.RetryListener,some.other.listener.SomeOtherListener</name>
        </property>
    </properties>
</configuration>
```
In such way you don't have to specify listeners in your testng.xml files.
I think such case when we need to use Maven + TestNG w/ listener is very common so the problem is obvious. Idk why people still haven't answered here if they knew how to deal with the problem, I doubt that I am the first who found any solution :)
