### ISSUE TITLE
Failed tests when using RetryAnalyzer are marked as ignored instead of failed

### ISSUE THREAD

**Issue by gavrilfb** [cbeust/testng#2325] opened 2020-06-18 06:01 UTC
### TestNG Version
7.1.0
> Note: only the latest version is supported

### Expected behavior
Failed tests when using RetryAnalyzer are marked as failed.

### Actual behavior
Failed tests when using RetryAnalyzer are marked as ignored.
![image](https://user-images.githubusercontent.com/29943195/84981672-3f494f80-b15f-11ea-8a2b-25c88cf6e266.png)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

The retry impl class

	public class RetryAnalyzerImpl implements IRetryAnalyzer {
		private int maxRetryCount = 3;
		private int retryCount = 0;

		public boolean retry(ITestResult result) {
			if (retryCount < maxRetryCount) {
				retryCount++;
				return true;
			}
			return false;
		}
	}
 
The test method

	@Test(retryAnalyzer= RetryAnalyzerImpl.class)
	public void VerifyRetrievePublicaAndActiveCommunity(){
		int i = ThreadLocalRandom.current().nextInt(0, 2);
		System.out.println(i);
		Assert.assertEquals(i,0);
	}

**Comment by krmahadevan** [comment] 2020-06-18 06:44
@gavrilfb - Couple of things:

When there's a retry analyses and there are failure attempts, then the intermediate failures are always reported as skipped (because the test is being retried once again).

If even the last attempt fails, then its status alone gets reported as "failed" and if the last attempt passes, then its status alone gets reported as "passed".

So TestNG is working as designed to report the interim test execution attempts as **SKIPPED**

The TestNG team does not own the IntelliJ TestNG plugin codebase. Its being maintained by the JetBrains team. So if there are any bugs that you feel need to be addressed in IntelliJ, you should be logged in https://youtrack.jetbrains.com/issues/IDEA

Closing this issue with resolution as *Question answered*

**Closed by krmahadevan** 2020-06-18 06:44 UTC
