### ISSUE TITLE
tests run under group or main thread unless timeout param specified

### ISSUE THREAD

**Issue by borisivan** [cbeust/testng#1699] opened 2018-02-17 20:14 UTC
### TestNG Version
6.14.2

### Expected behavior
Test should run in it's own thread, with test name in the thread name

### Actual behavior
If a test doesn't have the `timeOut `parameter in the `@Test` annotation, it runs in thread main, or the group thread.

### Is the issue reproductible on runner?
- [X] Maven
- [X] Eclipse

I use the thread name in a log pattern. For 99% of my tests, the thread name is: `TestNG-method=testname-1`. But I had a couple whose thread would be either `main `(if not run in parallel) or `TestNG-tests-parallelGroupNumber`. I finally figured out what causes it, but I don't understand why... the 2 tests that exhibited the strange behavior were the only ones that didn't have a `timeOut `parameter in the `@Test` annotation. All the others had it. And when I added it to the 2 that didn't, they conformed to the thread name expectation I had.

I have some threadsafe concerns in my project and I want the tests running in their own named thread. Is it intentional that the lack of a `timeOut `parameter would cause them to run in the group thread, or is this a bug?

**Comment by juherr** [comment] 2018-02-19 13:19
The timeout feature is handled by a thread which will be killed at the end of the timeout if the test is not yet finished.
Without a timeout, no need to use thread and the global one is used.
So we can consider it is 'intentional' by design.

But we can imagine having a dedicated thread name in all cases too.

**Comment by borisivan** [comment] 2018-02-19 15:09
Thanks @juherr, understood. Having the threadname represent the test would be good, but I think it would be dangerous to rename the main/group thread to be the name of the test, unless it truly was a different thread. I'm trying to troubleshoot some threadsafe issues when tests are in parallel and want to ensure all tests are always running in their own thread.

The problem is that with the group thread, I also have a couple of background thread spawned in the `@beforeGroup` method. When running all tests in parallel=classes in one `<test>` in the XML, they get sleep interrupted when 6 tests are running in parallel with threadcount 6. When I have 6 `<test>` in the XML each with multiple classes, but parallel=tests at the suite level, and threadcount at 50, all tests run _without_ being interrupted. Looking to understand the expected behavior/impact of having background threads, as it relates to how many tests testNG will smoothly run in parallel. My goal is to run 6 tests in parallel -- i.e. the parallel=classes strategy, but I can't. Issues #1692 (looking for this info) and #1694 (confirmed bug, waiting on fix) are hindering.

Any insight you have is appreciated. Thanks!

**Comment by krmahadevan** [comment] 2018-05-30 03:15
Closing this off with resolution as _TestNG working as designed_
If there are any further queries, please help attach simple standalone tests, that we can use to reproduce the problem.

**Closed by krmahadevan** 2018-05-30 03:15 UTC
Labels: Feature: parallel, Feature: timeout
