### ISSUE TITLE
Static test method in abstract class runs repeatedly

### ISSUE THREAD

**Issue by Pr0methean** [cbeust/testng#1561] opened 2017-09-27 23:13 UTC
### TestNG Version
6.11

### Expected behavior
When I want to test static methods in an abstract class, and also provide heritable test cases for the instance methods, I can create an abstract test class with static `@Test` methods to test the static methods, instance `@Test` methods to test the instance methods, and an abstract method that instantiates the class under test. The instance methods are run once in each concrete subclass of the test class; the static methods are run only once.

### Actual behavior
The static test methods are run as many times as the abstract test class has concrete subclasses.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
```java
public abstract class Testable {
  public static String staticMethod() {
    return "Hello from a static method";
  }
  public abstract String instanceMethod();
}
public class RedTestable extends Testable {
  @Override
  public String instanceMethod() {
    return "Hello in red";
  }
}
public class BlueTestable extends Testable {
  @Override
  public String instanceMethod() {
    return "Hello in blue";
  }
}
public abstract class TestableTest {
  public abstract Testable createTestable();
  @Test
  public static void testStaticMethod() {
    Assert.assertTrue(Testable.staticMethod().startsWith("Hello"));
  }
  @Test
  public void testInstanceMethod() {
    Assert.assertTrue(createTestable().instanceMethod().startsWith("Hello"));
  }
}
public class RedTestableTest extends TestableTest {
  @Override
  public Testable createTestable() {
    return new RedTestable();
  }
}
public class BlueTestableTest extends TestableTest {
  @Override
  public Testable createTestable() {
    return new BlueTestable();
  }
}
```

**Comment by Pr0methean** [comment] 2017-09-28 00:26
A workaround I'm using at https://github.com/Pr0methean/BetterRandom/blob/dead28df1f482e73681b7c3c14a17a4c856e84c4/betterrandom/src/test/java/io/github/pr0methean/betterrandom/prng/BaseRandomStaticTest.java is to create a second test class for each affected abstract class under test, make it concrete and move the static-method tests there.

**Comment by krmahadevan** [comment] 2017-10-06 03:05
@Pr0methean - I am not sure if this is a problem with TestNG. Here's why.

* TestNG makes use of Reflection to determine the methods that are to be run. 
* When it comes to reflection, it doesn't make any sense for TestNG to distinguish between static methods and non static methods, because TestNG is always going to create an instance of your test class (the class that houses your `@Test` method) and then run the methods within it using reflection.
* If TestNG were to distinguish between static and non-static methods, then TestNG has to provide different execution mechanisms for both and am guessing that is going to cause an avalanche of changes (which am not sure is worth the effort)

Couple of questions for you : 
* Why would one want to define static methods and brand them as static test methods ?
* Why can't these methods be instance methods which perhaps internally still test static implementations ?

IMO, this is not a problem with TestNG. 

ping @juherr @cbeust - Please chime in with your thoughts. Based on your comments, we can proceed further with this issue.

**Comment by Pr0methean** [comment] 2017-10-06 05:12
The point is that instance methods should be tested in every subclass, since they can be overridden or can call overridden methods, but static methods should generally only be tested once since they won't change. If it is indeed essential for TestNG to instantiate every test class whose methods it runs, even when it only runs static ones, then my two-test-class workaround may be the best solution for everyone affected (although it should probably be mentioned in the documentation).

**Comment by krmahadevan** [comment] 2017-10-06 06:02
> but static methods should generally only be tested once 

Agreed and makes sense. But the question is, against which class should it be run ? The child classes to which it has visibility (or) should the parent class be taken into consideration ? On the whole it creates a lot of confusion IMO.

**Comment by krmahadevan** [comment] 2017-10-08 04:04
ping @juherr - IMHO we can close this issue. WDYT ?

**Comment by juherr** [comment] 2017-10-08 06:41
@cbeust WDYT? What is the expected behavior for static tests involved in inheritance?

**Comment by krmahadevan** [comment] 2017-10-10 02:01
@cbeust - Please advise so that we may proceed further accordingly.

**Comment by cbeust** [comment] 2017-10-10 04:36
I think arguments can be made both ways, whether static methods should be run once or multiple times, so TestNG is doing the right thing.

If you want to add this semantic to the meaning of `static` in the context of tests, you could add a boolean that makes sure these test methods only run once.

**Comment by krmahadevan** [comment] 2017-10-10 05:21
Closing this issue based on the feedback provided by @cbeust

**Closed by krmahadevan** 2017-10-10 05:21 UTC
Labels: inheritance
