### ISSUE TITLE
Serialization produces a null field, *only* when running on TestNG

### ISSUE THREAD

**Issue by Pr0methean** [cbeust/testng#1514] opened 2017-08-28 02:37 UTC
### TestNG Version
6.11

### Expected behavior
A static method that throws no exceptions when wrapped as its class's main() method also throws no exceptions when wrapped as a test. In this case, serialization behaves normally (i.e. non-transient fields that were non-null in the original object (I've tried writing a writeObject() method just to assert this) are also non-null in a copy made by serializing and deserializing).

### Actual behavior
java.lang.AssertionError: @AssumeAssertion(nullness)

	at betterrandom.prng.BaseRandom$BaseEntropyCountingRandom.checkedReadObject(BaseRandom.java:110)
	at betterrandom.prng.BaseRandom.readObject(BaseRandom.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at betterrandom.prng.BaseRandom$CellularAutomatonRandom.test(BaseRandom.java:299)
	at betterrandom.prng.CellularAutomatonRandomTest.testSerializable(CellularAutomatonRandomTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
[BaseRandom.zip](https://github.com/cbeust/testng/files/1254952/BaseRandom.zip)
See https://github.com/Pr0methean/betterrandom/tree/serialmcve for full context. The failure to replicate this when main() is the entry point is how I know this is a TestNG bug, and not a Java serialization bug or a bug in my own code.

**Comment by Pr0methean** [comment] 2017-08-28 02:43
FYI: This is the first case I've seen of a "reverse Heisenbug" -- one that occurs when it's being tested for in a formal testing framework, but can't be reproduced in production.

**Comment by krmahadevan** [comment] 2017-08-28 03:02
@Pr0methean - I was able to reproduce this exception even when running from within a `main()` method. So not sure how TestNG is involved here.

In order to simulate the problem, you would need to pass -`ea` to the JVM so as to enable assertions.
Here's the altered java class with the `main()` method.

```java
public class CellularAutomatonRandomTest {
    public static void main(String[] args) throws IOException, ClassNotFoundException {
        new CellularAutomatonRandomTest().testSerializable();
    }

    @Test(timeOut = 15000)
    public void testSerializable() throws IOException, ClassNotFoundException {
        // Serialise an RNG.
        CellularAutomatonRandom rng = new CellularAutomatonRandom();
        CellularAutomatonRandom result;
        try (
                ByteArrayOutputStream byteOutStream = new ByteArrayOutputStream();
                ObjectOutputStream objectOutStream = new ObjectOutputStream(byteOutStream)) {
            objectOutStream.writeObject(rng);
            byte[] serialCopy = byteOutStream.toByteArray();
            // Read the object back in.
            try (ObjectInputStream objectInStream = new ObjectInputStream(
                    new ByteArrayInputStream(serialCopy))) {
                result = (CellularAutomatonRandom) (objectInStream.readObject());
            }
        } catch (IOException | ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
        result.nextLong();
    }
}
```

Here's my run configuration 

![runconfig](https://user-images.githubusercontent.com/909773/29757661-1b6f193a-8bcb-11e7-9854-8a26f4e567ec.jpeg)

Here's the `main()` method output

```java
Exception in thread "main" java.lang.AssertionError: @AssumeAssertion(nullness)
	at betterrandom.prng.BaseEntropyCountingRandom.checkedReadObject(BaseEntropyCountingRandom.java:25)
	at betterrandom.prng.BaseRandom.readObject(BaseRandom.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at betterrandom.prng.CellularAutomatonRandomTest.testSerializable(CellularAutomatonRandomTest.java:49)
	at betterrandom.prng.CellularAutomatonRandomTest.main(CellularAutomatonRandomTest.java:33)

```

**Comment by Pr0methean** [comment] 2017-08-28 03:08
Hmm, I would've assumed IntelliJ would default to running in a "debug mode" that would include enabling assertions (especially since in one of my runs via main(), I had a breakpoint set). So can anyone possibly advise on how a non-transient field of Serializable (in this case AtomicLong) type that wasn't null when written can possibly become null when read back in?

**Comment by Pr0methean** [comment] 2017-08-28 03:15
BTW, I've only actually tested with a main() method in this simplified case; in the far-more-complex library where I encountered the issue, disabling assertions would only have turned their failures into harder-to-trace NPEs.

**Comment by krmahadevan** [comment] 2017-08-28 03:21
> So can anyone possibly advise on how a non-transient field of Serializable (in this case AtomicLong) type that wasn't null when written can possibly become null when read back in?

Please check if this link helps answer your question : http://blog.clempinch.com/transient-and-final-instance-variables-in-java/

**Comment by Pr0methean** [comment] 2017-08-28 03:56
It doesn't, since the field I'm having issues with is not transient. However, it *is* final (I'm counting on defaultReadObject() to initialize it when no constructor gets a chance to do so, with only the usual fine print involving reflection and Objenesis backdoors); any resources you can recommend for other related serialization technicalities?

**Comment by krmahadevan** [comment] 2017-08-28 08:47
@Pr0methean - I found this article to be a bit interesting http://www.oracle.com/technetwork/articles/java/javaserial-1536170.html 

We know 
* `transient` fields are ignored from serialization
* for `final` data members, their default value (`null` for objects and for primitives their default values) is what gets assigned.

So if you would like your `final` data members to be initialised when the deserialisation happens then you might want to provide your own `readObject()` and `writeObject()` implementations in your class.

**Comment by krmahadevan** [comment] 2017-09-18 11:03
Closing off this issue, since its not a TestNG anymore, but more of a serialization/de-serialization related query.

**Closed by krmahadevan** 2017-09-18 11:03 UTC
