### ISSUE TITLE
[BUG] TestNG by default disables loading DTD from unsecured Urls.

### ISSUE THREAD

**Issue by shaburov** [cbeust/testng#2384] opened 2020-10-09 19:48 UTC
### TestNG Version
```xml
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.3.0</version>
</dependency>
```

### Expected behavior
Throw exception **after** read the testng-1.0.dtd file from resource
![image](https://user-images.githubusercontent.com/15269131/95625649-7bdbe680-0a81-11eb-8304-cb6c312c173e.png)

### Actual behavior
The testng-1.0.dtd file is not readable from resources

### Is the issue reproductible on runner?
IntelliJ v2020.2.3 (TestNG IDE plugin ver. 202.7660.26)

**Comment by kobebryant2007** [comment] 2020-10-10 01:42
I think you just need add a VM arguments '-Dtestng.dtd.http=true', or use HTTPS resources. Currently, TestNG need HTTPS as default in suite files.

**Comment by shaburov** [comment] 2020-10-11 01:06
@kobebryant2007 There is an obvious bug in the code.
1. I do not want to add an argument and I do not want the file `testng-1.0.dtd` to be taken over the network.
2. If you add a flag, then based on the code, it makes no sense for me to put the file in the resources.

@juherr Pay attention please.

**Comment by krmahadevan** [comment] 2020-10-11 07:41
@shaburov - 

> I do not want to add an argument and I do not want the file testng-1.0.dtd to be taken over the network.

Based on my understanding the reason that TestNG looks for the DTD from the network is to ensure that it retrieves the latest/proper DTD. TestNG will try to retrieve the DTD from the TestNG website ONLY over the https protocol and if its not found, you are going to be seeing that error. The only way to disable that is to use that JVM argument that @kobebryant2007  suggested.

> If you add a flag, then based on the code, it makes no sense for me to put the file in the resources.

Can you help me understand what the reason behind this expectation that TestNG is to be reading a file from your local resources ? If its mentioned that way in some place, please point me to the relevant documentation. All said and done, if there are network glitches, then TestNG by default aborts currently. That has been sorted out as part of the PR https://github.com/cbeust/testng/pull/2386 which will fall back to the DTD embedded within the TestNG jar. I am guessing that once the PR gets merged, then you can end up making your testng dtd file in your CLASSPATH which can be fetched as a resource.

**Comment by juherr** [comment] 2020-10-11 19:15
@shaburov What are you trying to do?

The TestNG jar is already including the DTD and it is the one which is supposed to be used.

**Comment by shaburov** [comment] 2020-10-12 03:22
@juherr Look at the code that I attached to the screenshot and realize that this is not the case. 
An exception will be thrown before the file is read from the resources.

**Comment by algotastic** [comment] 2020-10-20 19:03
I believe the issue is either that IntelliJ is not using HTTPS:
![image](https://user-images.githubusercontent.com/22728119/96632019-b5f88400-12dc-11eb-9169-8e45cb093c26.png)

Or that the non-HTTPS URL is not in the `URLS` list (note that `TESTNG_DTD_URL` and `HTTPS_TESTNG_DTD_URL` are exactly the same).
![image](https://user-images.githubusercontent.com/22728119/96631947-9eb99680-12dc-11eb-8d45-e7f43e86f6f5.png)

**Comment by darklynx** [comment] 2020-10-23 20:52
@algotastic the second, I believe, then @shaburov is right, this is a bug:
https://github.com/cbeust/testng/blob/7.3.0/src/main/java/org/testng/xml/Parser.java#L33

it should be `public static final String TESTNG_DTD_URL = "http://testng.org/" + TESTNG_DTD;`

**Comment by juherr** [comment] 2020-10-23 21:04
Right, it looks like an unexpected "replace all" from  https://github.com/cbeust/testng/commit/cf22ccfcb2a34f9b0bb4fa8cbedae5297ddd2049

**Comment by askfor** [comment] 2020-10-31 02:52
I'm ok to add  '-Dtestng.dtd.http=true', but this makes it's impossible to test a class/method in IntelliJ offline.

**Comment by krmahadevan** [comment] 2020-11-29 17:13
Closed via https://github.com/cbeust/testng/pull/2409

**Closed by krmahadevan** 2020-11-29 17:13 UTC
