### ISSUE TITLE
HTML Colours are not getting reflected in the report in TestNG 6.8 release

### ISSUE THREAD

**Issue by Ramnathan** [cbeust/testng#375] opened 2013-04-22 07:03 UTC
When we give HTMLcode in the Reporter.Log function, generally that particular colour will be reflected for whatever we have given in the HTML report we get, till TestNG 6.7 release but the color is not getting applied from TestNG 6.8 releases. We get some weird error messages if we give the HTML Color code.  This is an important aspect which helps to filter the log report(emailable report) with different colours

**Comment by saikiran40cs** [comment] 2015-08-06 09:52
I am also facing the same issue..The html tags are getting escaped in the report and is coming as a raw text output.
For Example:Reporter.log("<font color='green'>PASS</font>");
Output: PASS, but i wanted in Green color..

Operating System Used is: Windows 7

**Comment by Vijayalakshmi01** [comment] 2016-08-10 05:38
@cbeust I am trying to insert a screenshot link to emailable report. 
Below is my code
Reporter.setEscapeHtml(false);
Reporter.log("<a href=\"" + System.getProperty("user.dir") + "\\test-output\\screenshots\\" + filename +".jpg\" target=\"_blank\"><font color='red'>Link</font></a>" );
It is giving the red link in index.html, but in emailable report, it is printing the plain text
<a href='C:\Project\test-output\screenshots\screenshot_name.jpg' target='_blank'><font color='red'>Link</font></a>
Can you pls provide me a solution for this?
TestNG: 6.9.9

**Comment by karthiknvss** [comment] 2016-12-02 23:10
Hi, Anyone has found a solution for tags getting escaped. I have tried all the possible things mentioned in the internet. But no luck..
a href="C:/2016.12.01.23.03.59.jpg"] [img src="C:/2016.12.01.23.03.59.jpg"/] [/a]

1.ReportNG reports are generating properly
2. I have set the escape property as System.setProperty("org.uncommons.reportng.escape-output", "false") 
3. I disabled the default listeners from project properties.
4. I added reportng listeners to testng.xml and pom.xml.

Not sure why the screenshots are not getting displayed. Please anyone suggest.

**Comment by mmtmohit** [comment] 2016-12-05 14:33
Hi @cbeust : Escaping is not getting turned off in emailable report html . Please fix asap Thanks

**Comment by krmahadevan** [comment] 2016-12-11 05:03
@mmtmohit - I am not able to reproduce this problem using TestNG 6.10. 
It would be good if you could please help furnish a reproducible test that can be used to recreate the problem if you feel that the issue still exists when using TestNG 6.10


Here's what my test class looks like

```java
import org.testng.Reporter;
import org.testng.annotations.Test;

import java.io.File;

public class SimulateIssue {
    @Test
    public void testMethod() {
        Reporter.setEscapeHtml(false);
        Reporter.log("<a href='http://www.google.com'><font color='red'>Open Google</font></a>", true);
        String currentDir = "file://" + new File(System.getProperty("user.dir")).getAbsolutePath() + File.separator + "pom"
            + ".xml";
        Reporter.log("<a href='" + currentDir + "'><font color='green'>View Pom file</font></a>", true);

    }
}
```

## Here are the screenshots from the generated reports

### _Emailable-Report_
![375-1](https://cloud.githubusercontent.com/assets/909773/21078182/a4bc7aea-bf8c-11e6-960e-e26be69fa02a.png)

### _Default TestNG report (index.html)_
![375-2](https://cloud.githubusercontent.com/assets/909773/21078184/acbe1438-bf8c-11e6-9bd7-98356627cd20.png)

**Comment by saikiran40cs** [comment] 2016-12-16 08:22
@mmtmohit With testNG 6.10, i am not able to reproduce the issue.
Date of release for testNG 6.10 is (Dec 06, 2016).

Use the below link to know the latest testNG releases.
https://mvnrepository.com/artifact/org.testng/testng/

I suggest to use the maven dependencies in your project so that you will not face this issues in future.

**Comment by juherr** [comment] 2016-12-16 12:58
Looks fixed in 6.10 
Feel free to reopen if it is not the case.

**Closed by juherr** 2016-12-16 12:58 UTC
Labels: Feature: report, Need: user answer

**Comment by sravee123** [comment] 2017-12-07 10:56
Hi all,

I would like to generate the output with different colors at testng
reports.

I am using the following syntax, but not working.

Reporter.log("<font color='red'> Hello world </font>");

Desired output is Hello world in red color, but actual output is <font
color='red'> Hello world </font>.

I am using testng 6.10

**Comment by sravee123** [comment] 2017-12-07 10:57
Reporter.log("<font color='red'> Hello world </font>");

**Comment by krmahadevan** [comment] 2017-12-13 13:58
@sravee123 - Please open a new issue, include all the details and you can cross reference this issue in the new one.
