### ISSUE TITLE
Each interceptor called two times

### ISSUE THREAD

**Issue by tremes** [cbeust/testng#630] opened 2015-04-03 12:58 UTC
First call is at https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestRunner.java#L734
and second call at https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestRunner.java#L847
I think this is unneccessary but the @Verifier logic in test.verify.VerifyTest actually depends on the second call (since intercept returns 4 methods in this case but freeNodes at https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestRunner.java#L755 are just 3 since DynamicGraph uses Set for storing the nodes). It simply could be https://github.com/cbeust/testng/compare/master...tremes:called_interceptor_onetime?expand=1 when omitting the Verifier test (Cannot find anything about this in the doc).

**Comment by juherr** [comment] 2015-04-26 13:49
Duplicate of #155

**Closed** 2015-04-27 02:16 UTC
