### ISSUE TITLE
Error when converting JUnit4.4 test class to TestNG

### ISSUE THREAD

**Issue by tfischer4765** [cbeust/testng#194] opened 2012-03-14 12:52 UTC
When I use the "Convert to TestNG" feature of the Testng Eclipse integration, the following, non-existing import is generated: 

import static org.testng.AssertJUnit.assertThat;

My testng-plugin version is   TestNG    6.4.0.20120226_1704

**Comment by krmahadevan** [comment] 2017-09-17 14:18
ping @missedone - Nick can you please help take a look at this one and if this is no longer an issue, please help close this.

**Comment by missedone** [comment] 2017-09-18 07:49
can't reproduce this on recent release 6.12.0.201709050550, @krmahadevan , plese colse this one. thx

**Comment by krmahadevan** [comment] 2017-09-18 07:50
Closing this issue based on feedback from @missedone

**Closed by krmahadevan** 2017-09-18 07:50 UTC
Labels: Runner: eclipse
