### ISSUE TITLE
No way to enforce @Test(singleThreaded = true) when test defined in base class

### ISSUE THREAD

**Issue by findepi** [cbeust/testng#2361] opened 2020-09-07 15:26 UTC
### TestNG Version

6.10, 7.3.0

### Expected behavior

Methods executed serially

### Actual behavior

Tests executed parallel

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

```java
@Test(singleThreaded = true)
public abstract class BaseTestClass
{
    private final AtomicInteger currentTests = new AtomicInteger();

    protected void test()
    {
        int currentTests = this.currentTests.incrementAndGet();
        try {
            assertEquals(currentTests, 1);
            MILLISECONDS.sleep(10);
        }
        catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        finally {
            this.currentTests.decrementAndGet();
        }
    }

    @Test
    public void test1()
    {
        test();
    }

    @Test
    public void test2()
    {
        test();
    }

    @Test
    public void test3()
    {
        test();
    }

    @Test
    public void test4()
    {
        test();
    }
}
```

```java
@Test(singleThreaded = true)
public class TestClass
        extends BaseTestClass
{
}
```

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="A Suite" parallel="methods" thread-count="4">
    <test name="A test" parallel="methods" thread-count="4">
        <packages>
            <package name="findepi.test.ng" />
        </packages>
    </test>
</suite>
```

**Comment by findepi** [comment] 2020-09-07 15:27
**Workaround**

add a dummy test method to the leaf test class.

**Comment by krmahadevan** [comment] 2020-09-07 15:58
@findepi - `6.1` is a really a very old version of TestNG. Can you please try again using `7.3.0` (latest released version of TestNG and post back your experience ?

**Comment by krmahadevan** [comment] 2020-09-07 16:33
I just now tried this using TestNG `7.3.0` and this works fine without having to add a dummy test method in the child class.
Closing this issue. Please comment if you are still facing this as a problem and we can investigate further.

**Comment by findepi** [comment] 2020-09-07 16:36
I reproduced this with 7.3.0. The only change I had to do is to remove `DOCTYPE` from my suite.

**Comment by krmahadevan** [comment] 2020-09-07 17:32
@findepi - I am not able to reproduce this at my side. Why don't you attach a maven sample project that I can execute from the command line to reproduce the problem ?

**Comment by krmahadevan** [comment] 2020-09-07 17:33
Ok.. Hold on.. I think am reading the problem incorrectly

**Comment by findepi** [comment] 2020-09-07 19:52
> Why don't you attach a maven sample project that I can execute from the command line to reproduce the problem ?

https://github.com/findepi/testng-2361

on my machine:

```
$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_PL, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

```
$ mvn clean test
[....]
[ERROR] Failures:
[ERROR]   TestClass>BaseTestClass.test2:52->BaseTestClass.test:32 expected [1] but found [2]
[ERROR]   TestClass>BaseTestClass.test3:58->BaseTestClass.test:32 expected [1] but found [2]
[ERROR]   TestClass>BaseTestClass.test4:64->BaseTestClass.test:32 expected [1] but found [2]
[ERROR] testng2361.TestClassWithFactory.test1(testng2361.TestClassWithFactory)
[INFO]   Run 1: PASS
[ERROR]   Run 2: TestClassWithFactory>BaseTestClass.test1:46->BaseTestClass.test:32 expected [1] but found [2]
[INFO]
[ERROR] testng2361.TestClassWithFactory.test2(testng2361.TestClassWithFactory)
[INFO]   Run 1: PASS
[ERROR]   Run 2: TestClassWithFactory>BaseTestClass.test2:52->BaseTestClass.test:32 expected [1] but found [2]
[INFO]
[ERROR] testng2361.TestClassWithFactory.test4(testng2361.TestClassWithFactory)
[ERROR]   Run 1: TestClassWithFactory>BaseTestClass.test4:64->BaseTestClass.test:32 expected [1] but found [2]
[ERROR]   Run 2: TestClassWithFactory>BaseTestClass.test4:64->BaseTestClass.test:32 expected [1] but found [2]
[INFO]
[INFO]
[ERROR] Tests run: 9, Failures: 6, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[...]
```

**Closed** 2020-09-09 04:17 UTC
