### ISSUE TITLE
Stacktrace is being printed for tests that passed when using expectedExceptions

### ISSUE THREAD

**Issue by ericjang96** [cbeust/testng#1228] opened 2016-11-03 15:58 UTC
### TestNG Version
6.9.10

### Expected behavior
I am using org.testng.reporters.XMLReporter as one of my listeners. All of my tests passed, so there should be no stacktraces in my testng.xml

### Actual behavior
For tests where I used expectedExceptions like the following:
```
@Test(invocationCount = kInvocationCount, threadPoolSize = kThreadPoolSize, expectedExceptions = {Exception.class}
```

The report shows the test-method status="PASS", but also prints the exception thrown, and the full stacktrace.

### Is the issue reproductible on runner?

- [x] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

**Comment by juherr** [comment] 2016-11-04 08:33
Thanks for the report. Why is it a problem for you to have the stacktrace?

@cbeust What do you think?

**Comment by cbeust** [comment] 2016-11-04 13:35
Agreed, not sure the stack trace adds any value if the test passes.

-- 
Cédric

**Comment by ericjang96** [comment] 2016-11-04 15:24
The main reason why I don't want the stacktrace is because I have about 200,000 tests and 40,000 of them have expected exceptions. So I believe that it is a waste of machine resources and time for the program to be writing them for passed tests.

Also, it seems to technically be incorrect behavior according to the Javadoc for XMLReporterConfig to be printing stacktraces for passed tests:
```
/**
   * Stack trace output method for the failed tests using one of the
   * STACKTRACE_* constants.
   */
  private int stackTraceOutputMethod = STACKTRACE_FULL;
```

**Comment by juherr** [comment] 2016-11-04 15:43
Ok, no prob for me :) I've just wanted confirmation from @cbeust before because it will change an historical behavior.

Could you propose a fix via a pull request? :)

**Comment by krmahadevan** [comment] 2016-11-05 05:43
@cbeust / @juherr - I have attempted at fixing this by adding a JVM argument named `stacktrace.output.level` using which one can control the verbosity. A value of `0` would disable stacktrace dumping in xml reports and a value of `2` would print the verbose logs. The default behavior is to print verbose logs (that way we are not breaking backward compatibility) but if one wants to disable the verbosity they can do so by passing `-Dstacktrace.output.level=0`

**Comment by ericjang96** [comment] 2016-11-05 08:38
@krmahadevan If I'm understanding you correctly, that doesn't solve this issue. You are letting the user easily modify the verbosity level, but not actually fixing the issue of stacktraces being printed for passed tests. Can you make sure this issue doesn't get closed with yours? Your message still has "fixes #1228" in it.

**Comment by krmahadevan** [comment] 2016-11-05 08:47
@ericjang96 - Why do you think this doesn't fix the issue ? By setting a JVM argument you can disable to stacktrace printing for passed tests (which is what the bug is all about), but at the same time I am ensuring that there is backward compatibility and the old behavior is not impacted. So IMO this does fix this problem. After the PR has been merged you would need to just pass in a JVM argument to get the new behavior, whereas for everyone else the current behavior of seeing stacktrace in the xml for even tests that passed, would continue to be there as is. For your use case, you don't want to see the stacktraces, but I am just trying to ensure that no one comes back and complains as to why the stacktraces are no longer appearing in the xml file.

**Comment by ericjang96** [comment] 2016-11-05 08:55
@krmahadevan Isn't what you've described a workaround? So if I set verbosity to 0 using your JVM argument, I wouldn't get ANY stacktraces, including my failed tests. The current behaviour is incorrect because I am getting stacktraces for specific passed tests (ones where I am using expectedExceptions) when I should never be getting stacktraces for passed tests. I still want them for failed tests.

**Comment by krmahadevan** [comment] 2016-11-05 08:59
@ericjang96 - No i am not suggesting a workaround. I am just ensuring that new expected behavior is also supported and at the same time the existing behavior is not impacted. If you take a look at the changes that are part of my PR, you would realise that the ability to control the verbosity of stactraces in xml reports is isolated ONLY to passed tests, and for failed tests the JVM argument has no effect. 

See here : https://github.com/krmahadevan/testng/commit/34763f1d3c85bd74477f9dd57a1fe1e1640e9238#diff-7826b0006b6dfc243ef805d4a2b135f6R306

**Comment by ericjang96** [comment] 2016-11-05 09:08
@krmahadevan Ah I see, I was going by the flag and method names, didn't really look at the implementation. You are right, and thanks for the fix. Can I suggest adding clarity by changing the flag name to something more clear like `"stacktrace.success.output.level"` and same for the method that gets this value? At first glance, it seems like the flag would change the overall verbosity level.

**Comment by krmahadevan** [comment] 2016-11-05 09:44
@ericjang96 - No problem. I renamed the JVM argument per your need and also the method name as well. 

@juherr / @cbeust - If you are fine with the changes, please help get this merged.

**Closed** 2016-11-07 21:17 UTC
Labels: Feature: report
