### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class 

### ISSUE THREAD

**Issue by pritesh-patil** [cbeust/testng#2495] opened 2021-03-10 03:57 UTC
### TestNG Version
7.4

### Expected behavior
The class should initialised and which is verified in 7.2,7.3. it is working correctly.

### Actual behavior
Not sure what has changed in 7.4 that class has not initialised as below exception occurs

java.lang.NoClassDefFoundError: Could not initialize class Validations
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Is the issue reproductible on runner?

Shell
Maven
IntelliJ

### Test case sample

-----
```
@Test(groups = {"Regression", "Sanity", "PROD", "API"}, description = "Get Playbook - /api/v2/playbooks/search?status=Active")
public void Verify_Retrieve_Active_Playbook() {
    String path = "/api/v2/playbooks/search?status=Active";
    given().
            header(timeStamp).
            log().
            all().
            contentType(ContentType.JSON).
            when().
            get("/v2/playbooks/search?status=Active").
            then().
            log().
            all().
            assertThat().
            spec(Validations.checkStatusCode);
}
```
-------------------
```
public class Validations {

    public static ResponseSpecification checkStatusCodeAndContentType =

            new ResponseSpecBuilder().
                    expectStatusCode(200).
                    expectContentType(ContentType.JSON).
                    build();

    public static ResponseSpecification checkStatusCode =

            new ResponseSpecBuilder().
                    expectStatusCode(200).
                    expectBody("status", equalTo("Success")).
                    build();


    public static ResponseSpecification checkStatusCodeAndContentTypeHtml =

            new ResponseSpecBuilder().
                    expectStatusCode(200).
                    expectContentType("text/html;charset=UTF-8").
                    build();

    public static ResponseSpecification checkStatusCodeCreated =

            new ResponseSpecBuilder().
                    expectStatusCode(201).
                    expectBody("status", equalTo("Success")).
                    build();

    public static ResponseSpecification checkNoContentStatusCode =

            new ResponseSpecBuilder().
                    expectStatusCode(204).
                    build();

    public static ResponseSpecification invalidPayloadStatusCode =

            new ResponseSpecBuilder().
                    expectStatusCode(anyOf(equalTo(400), equalTo(500))).
                    build();
}
```

**Comment by krmahadevan** [comment] 2021-03-10 04:15
@pritesh-patil - You would need to share a sample project that can be used to reproduce this issue.

```
java.lang.NoClassDefFoundError: Could not initialize class Validations
```

seems to suggest that the problem is with your Test class `Validations` and the code that you shared shows no connection to it whatsoever with TestNG.

So please share a sample project that can be used to reproduce your issue, failing which we would have to close this issue without any further action being taken.

**Comment by pritesh-patil** [comment] 2021-03-10 18:23
After debugging for whole day issue resolved by adding junit dependancy explicity as my Validation has two import statements as below which are basically referring from junit present earlier version of testing (7.3,7.4)

`import static org.hamcrest.Matchers.anyOf;
import static org.hamcrest.Matchers.equalTo;` 

`
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.12</version>
</dependency>
`
looks like in the current version of testing 7.4 has only below dependencies as compare to previous
versions
[INFO] +- org.testng:testng:jar:7.4.0:compile
[INFO] |  +- com.beust:jcommander:jar:1.78:compile
[INFO] |  \- org.webjars:jquery:jar:3.5.1:compile

and in the version below 7.3 (including) has below dependancies
+- org.testng:testng:jar:7.3.0:compile
[INFO] |  +- com.beust:jcommander:jar:1.78:compile
[INFO] |  +- org.apache.ant:ant:jar:1.10.3:compile
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.10.3:compile
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  \- com.google.inject:guice:jar:no_aop:4.2.2:compile
[INFO] |     +- javax.inject:javax.inject:jar:1:compile
[INFO] |     +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |     \- com.google.guava:guava:jar:25.1-android:compile
[INFO] |        +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |        +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO] |        +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |        +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |        \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
-----------

So, in my case Validations class not gets initialised as hamcrest dependency missing in 7.4 through junit . After explicit adding junit dependancy my problem resolved.

**Comment by krmahadevan** [comment] 2021-03-11 06:50
@pritesh-patil - JUnit is now an optional dependency for TestNG 7.4.0
That explains the issue that you were facing.

Since the problem has been resolved, closing this issue.

**Closed by krmahadevan** 2021-03-11 06:50 UTC
Labels: Need: sample, Need: user answer, Needs Query to be answered
