### ISSUE TITLE
Assert.assertEquals() broken for multi-dimensionnal array

### ISSUE THREAD

**Issue by ylemontagner** [cbeust/testng#1342] opened 2017-02-22 13:49 UTC
Hi,

As of TestNG version 6.9.10, the following test case fails:

```
@Test
public static void testCaseWithMultiDimensionalArray() {

	int[][] array1 = new int[1][];
	array1[0] = new int[] { 1, 2, 3 };

	int[][] array2 = new int[1][];
	array2[0] = new int[] { 1, 2, 3 };

	Assert.assertEquals(array1, array2);
}
````

It used to work up to version 6.9.9. The "normal" behavior seems to be the old one, i.e. consider `array1` and `array2` as equals.

**Comment by juherr** [comment] 2017-02-22 15:45
Duplicate of http://github.com/cbeust/testng/issues/1300

The behavior changed in 6.9.10 with https://github.com/cbeust/testng/pull/870
The previous behavior will be available with `assertEqualsDeep` in the next release (you can already try it with 6.10.1-SNAPSHOT).

**Closed by juherr** 2017-02-22 15:45 UTC

**Comment by ylemontagner** [comment] 2017-02-22 15:55
Thank you.
