### ISSUE TITLE
Unable to add Multiple iAnnotationTransformers

### ISSUE THREAD

**Issue by baubakg** [cbeust/testng#1939] opened 2018-10-29 10:21 UTC
### TestNG Version
- 6.14.3
- 7.0.0-beta1

### Use case
I wave to listeners:

- **Listener1**  : A retry listener that re-executes a test on failure
- **Listener2**  : An externalized group selector. I load groups from a file and use execute the test if they are part of the group

I include both in my testng file as listeners. This is because I do not always want to reexecute tests. So this is used in some projects but not in all.

Both listeners implement IAnnotationTransformer

### Expected behavior
I should be able to go through both listeners

### Actual behavior
In both cases only one listener is called. There is however a difference between 6.X and 7,X

#### 6.14.3
- **Listener1**  is ignored
- **Listener2** is called once

#### 7.0.0-beta1
- **Listener1**  is ignored
- **Listener2** is called **13 times**....

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse (for 6.14.3)
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Below is the code:
To reproduce you need to run the test : MultipleIAnnotations.testHavingTwoIAnnotations

command line:
`mvn clean test -Dtest=MultipleIAnnotations`

#### My listeners
They are quite similar:

##### Listener1

```java
public class Listener1 implements IAnnotationTransformer {

	private static int myTrace=0;

	public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
		myTrace++;		
	}

	public static int getMyTrace() {
		return myTrace;
	}

	public static void setMyTrace(int myTrace) {
		Listener1.myTrace = myTrace;
	}
}
```

##### Listener2

```java
public class Listener2 implements IAnnotationTransformer {

	private static int myTrace=0;

	public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
		myTrace++	
	}

	public static int getMyTrace() {
		return myTrace;
	}

	public static void setMyTrace(int myTrace) {
		Listener2.myTrace = myTrace;
	}
}
```

#### Test Code

```java
public class MultipleIAnnotations {

	@Test
	public void testHavingTwoIAnnotations() {
		TestNG testNGTestInstance = new TestNG();
		
		//Add suite
		XmlSuite l_testSuite = new XmlSuite();
		l_testSuite.setName("My Two IAnnotation Suite");
		List<XmlSuite> mySuites = new ArrayList<XmlSuite>();
		mySuites.add(l_testSuite);
		testNGTestInstance.setXmlSuites(mySuites);
		
		//Add listener
		l_testSuite.addListener("com.gandomi.testng.tests.Listener1");
		l_testSuite.addListener("com.gandomi.testng.tests.Listener2");
		
		//Add Test
		XmlTest lr_Test = new XmlTest(l_testSuite);
		
		lr_Test.setName("A simple test for testing iAnnotationTransformer");
		
		lr_Test.setXmlClasses(Arrays.asList(new XmlClass(SimpleTest.class)));
		
		//Run Tests
		testNGTestInstance.run();
		
		//Validate listener calls
		SoftAssert softAssert = new SoftAssert();
		
		softAssert.assertEquals(Listener1.getMyTrace(), 1, "We should have passed through Listener1");
		softAssert.assertEquals(Listener2.getMyTrace(), 1, "We should have passed through Listener2");		
		softAssert.assertAll();		
	}
}
```

Just for information I have a dummy test SimpleTest.simplePlaceHolder which is there for making the listener trigger.

```java
public class SimpleTest {
	@Test
	public void simplePlaceHolder() {
		Assert.assertTrue(true);
	}
}
```

**Comment by krmahadevan** [comment] 2018-10-29 12:33
@baubakg 

This issue is related to https://github.com/cbeust/testng/issues/1894
Currently by functionality TestNG does not let you add more than one implementation of `IAnnotationTransformer` into it. Even if added I believe only the last one to be added is the one to be considered.

This is still up for discussion and I am looking for inputs from both @cbeust and @juherr to know if this needs to be altered. There's a very easy alternative as shown in my comment in 
https://github.com/cbeust/testng/issues/1894#issuecomment-412249299

**Comment by baubakg** [comment] 2018-10-29 12:53
Thanks a lot @krmahadevan I am not shocked by this. I had played with a similar solution, but yours is quite nice. I may copy.

Do you want me to close this issue?

**Comment by krmahadevan** [comment] 2018-10-29 12:54
@baubakg Yeah you could. Because we still have an issue related to this problem that is tracking this. Moreover this would be a duplicate of #1894

**Comment by krmahadevan** [comment] 2018-10-29 12:56
Closing this as duplicate of #1894

**Closed by krmahadevan** 2018-10-29 12:56 UTC
Labels: Need: Discussion to finalize, annotationtransformer
