### ISSUE TITLE
Test NG 7.0.1

### ISSUE THREAD

**Issue by inder159** [cbeust/testng#2245] opened 2020-02-14 07:32 UTC
### TestNG 7.0.1
> Note: only the latest version is supported

### Actual behavior
[RemoteTestNG] detected TestNG version 7.0.1
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

### Is the issue reproductible on runner?
- [ ] Eclipse

### Test case sample
package test;

import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class D1 {
	@BeforeTest 
	public void testCase2() 
	{
		System.out.println("hello");
	}
	
@Test 
public void testCase3() 
{
	System.out.println("I am main");
}

}

**Comment by missedone** [comment] 2020-02-14 18:37
same as #2223

**Comment by krmahadevan** [comment] 2020-02-15 07:38
Closing this as a duplicate of #2223

**Closed by krmahadevan** 2020-02-15 07:38 UTC
