### ISSUE TITLE
[Bug] JUnit Reporter doesn't include ignored methods

### ISSUE THREAD

**Issue by gdemecki** [cbeust/testng#1211] opened 2016-10-21 06:54 UTC
### TestNG Version

6.9.13.6 (latest available)
### Expected behavior

I believe that `JUnitReportReporter` should be compliant with the JUnit 4.12 rules and thus should include the disabled/ ignored tests (the ones marked with `@Test(enabled = false)` in the XML report under `junitreports/` directory.

Yes, I know, I know, this is not how TestNG treats ignored tests - but if we are going to produce a JUnit-compliant test report, then I guess we should stick to the JUnit rules :)
### Actual behavior

Now, TestNG doesn't generate absolutely no info about such test in the output xml report.
### Is the issue reproductible on runner?

Tested via Maven.
### Test case sample

``` java
 @Test(enabled = false)
 public void should_be_ignored() {
     assertEquals("abcd", "abc");
 }
```

I would expect to see followig entry in the generated JUnit report:

``` xml
<testcase time="0" classname="com.myproject.AbcTest" name="should_be_ignored">
  <skipped/>
</testcase>
```

**Comment by juherr** [comment] 2016-10-24 08:49
@cbeust What do you think?

**Comment by krmahadevan** [comment] 2016-11-13 14:57
@cbeust @juherr - Please advise on the expected behaviour. Based on your inputs I would like to try and take a jab at this issue.

**Comment by cbeust** [comment] 2016-11-14 20:39
I'm fine with that. As far as I recall, these tests don't appear in the reports because they are removed from the suite very early on (at annotation parsing time) so TestNG doesn't even know about them by the time it runs the reports.

**Comment by gdemecki** [comment] 2016-11-15 13:40
@krmahadevan - I'm glad you are willing to tackle this.
Based on what Cedric said, if you are going to implement this feature, then AFAIK you can also make issue #1213 by the way. Because they are quite related. What do you think?

Also one thing that come to my mind: I'm not sure how introducing a "disabled/ ignored"  (for me both mean the same) category for test methods will conflict with the current TestNG implementation.

What do I mean? Although `testng-results.xml` doesn't contain any notion of disabled tests - when I open a generated HTML report, I can see there: `Ignored methods` section (above the `Chronological view`).

@cbeust What do you think? Does it matter?

**Comment by cbeust** [comment] 2016-11-15 19:20
@gdemecki Now you mention it, I do remember that I made a few changes so that ignored methods actually get preserved for the reports, so what I said earlier is probably no longer accurate (it was a long time ago, my memory is hazy :)).

Either way, I agree it's useful to have that, if we don't already, so the issue is legitimate: let's make sure that ignored methods are available to reporters and listeners.

**Comment by krmahadevan** [comment] 2016-11-21 04:03
@gdemecki - Please see if this is what you were after : https://github.com/cbeust/testng/pull/1247#issuecomment-261837443

**Comment by gdemecki** [comment] 2016-11-23 11:28
Hi @krmahadevan, almost, but not exactly.
Issue with additional counter for ignored methods is solved.
But issue titled `JUnit Reporter doesn't include ignored methods` is not really solved, because report format doesn't conform to the format produced by JUnit Ant task/ Maven Surefire Plugin. 

Why? Because you have used `<ignored/>` xml element:
```xml
<testcase name="iShouldNeverBeExecuted" time="0.0" classname="org.rationale.emotions.junit.MyTestcase">
  <ignored/>
</testcase>
```
instead of `<skipped />`:

```xml
<testcase name="iShouldNeverBeExecuted" time="0.0" classname="org.rationale.emotions.junit.MyTestcase">
  <skipped/>
</testcase>
```

3rd party tools which are supposed to parse the above XML report won't recognize the new `<ignored/>` element.  So I believe that we should stick to the rules set by ant/ maven surefire.

Ps. The current schema used by e.g. maven-surefire-plugin you can view here: [maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd](https://github.com/apache/maven-surefire/blob/master/maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd).

BTW: Thanks for your hard work, I was surprised you was able to come up with the implementation so fast.

Kind regards

**Comment by krmahadevan** [comment] 2016-11-24 04:15
@gdemecki - I am a bit confused here. I understand the part wherein you are saying that "ignored" tests should be included in the xml with the tag as `skipped` instead of `ignored` (Your original bug report did have that. Somehow I missed that).

But now that you did share the schema (am no big xml expert), I tried generating a sample xml using the schema and this is what I got

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite name="str1234" time="str1234" tests="str1234" errors="str1234" skipped="str1234" failures="str1234" group="str1234">
  <properties>
    <property name="str1234" value="str1234" />
  </properties>
  <testcase name="str1234" classname="str1234" group="str1234" time="str1234">
    <failure message="str1234" type="str1234" time="str1234">str1234</failure>
    <rerunFailure message="str1234" type="str1234" time="str1234">str1234</rerunFailure>
    <skipped message="str1234">str1234</skipped>
    <error message="str1234" type="str1234">str1234</error>
    <system-out />
    <system-err />
  </testcase>
</testsuite>
```

I don't see the attribute called "ignored" in the JUnit schema you shared. But now TestNG added it up via https://github.com/cbeust/testng/pull/1247 

So aren't we out of sync with what Junit is giving and what now TestNG produces ?

Just trying to understand what value add we would be doing by counting/marking `ignored` test as `skipped` in the report, but explicitly calling out `ignored` count at the `suite` level tag. How will an end user who looks at the junitreports/xml file be able to differentiate which test was `skipped` and which one was `ignored` ?

**Comment by juherr** [comment] 2016-11-24 10:19
@krmahadevan You can have a look on the junit reporter from ant: https://github.com/apache/ant/blob/e843dd287f13bc9e87b1af1201d2e557fdcc1897/src/main/org/apache/tools/ant/taskdefs/optional/junit/XMLJUnitResultFormatter.java#L331-L336
It marks ignored tests as skipped.

**Comment by gdemecki** [comment] 2016-11-24 10:58
@krmahadevan sure, let me explain:

> I don't see the attribute called "ignored" in the JUnit schema you shared. But now TestNG added it up via #1247

It is Ok that you cannot see the attribute `ignored` there. Because  JUnit-style of report doesn't use `ignored` word, it just uses the `skipped` for this purpose. In the JUnit world they are synonyms. Although in the TestNG world they aren't synonyms.

> How will an end user who looks at the junitreports/xml file be able to differentiate which test was skipped and which one was ignored ?

Please look at my explanation above. They are synonyms.

I think your confusion is caused by differences in the JUnit and TestNG possible test statues. Basically:

JUnit has four possible test statuses:

 1. Success
 2. Failure (due to AssertionFailedError)
 3. Error (unexpected Exception has been thrown)
 4. Skipped (aka. Ignored)

While TestNG has so far just three (please correct me if I'm wrong) possible test statuses:

 1. Passed
 2. Failed
 3. Skipped (but **not ignored**! This status is only for tests which were dependent on the failed tests)

So TestNG has no equivalent for the status `SKIPPED`  from JUnit (although it **has already status with the same name**, but for a totally different purpose). This is probably root of a confusion.

On the other hand:  JUnit has never had any notion of dependency between tests, so there is **no equivalent** of the TestNG `SKIPPED` status.

So thanks to your work there is a new status in the TestNG which is called `IGNORED`  - which will be/ should be an equivalent for `SKIPPED` status from junit. Because so far, end user was totally not aware of how many tests were actually permanently disabled in a test suite. Now it will change.

Thanks, and please ping me if something is not clear.

Ps. @cbeust , @juherr please correct me if I was wrong somewhere above.

**Comment by krmahadevan** [comment] 2016-11-24 15:35
@gdemecki - Awesome! Thanks for clarifying things. I took my baby steps directly with TestNG so I am not aware of how JUnit works. So this does add a lot of clarity. 

> So TestNG has no equivalent for the status SKIPPED from JUnit (although it has already status with the same name, but for a totally different purpose). This is probably root of a confusion.

Yes that's why I got confused. In TestNG `skipped` indicates either an upstream failure (either due to an upstream test failure or due to a config failure). I didn't realise that JUnit had a different meaning for the word `skipped`.

> So thanks to your work there is a new status in the TestNG which is called IGNORED
That wasn't me. It was @cbeust :) I am just bringing that information into the JUnit reports (this information is already available in the TestNG, its just that not all the TestNG default reports show this).
I haven't yet brought out this information in all of the TestNG's html reports (atleast to the best of my knowledge), but this information is atleast now available in the JUnit reports that TestNG produces after my delivery.

> @krmahadevan You can have a look on the junit reporter from ant: https://github.com/apache/ant/blob/e843dd287f13bc9e87b1af1201d2e557fdcc1897/src/main/org/apache/tools/ant/taskdefs/optional/junit/XMLJUnitResultFormatter.java#L331-L336
It marks ignored tests as skipped.

@juherr - Thanks for pointing me to this.

**Comment by krmahadevan** [comment] 2016-11-24 16:04
@gdemecki and @juherr 

**This is how the xml generated under `junitreports/ ` folder will look like (This is the JUnit compliant xml report produced by TestNG)**

`cat junitreports/TEST-test.junitreports.SimpleTestSample.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by test.junitreports.LocalJUnitReportReporter -->
<testsuite name="test.junitreports.SimpleTestSample" tests="2" time="0.000" ignored="1" failures="0" timestamp="24 Nov 2016 15:45:53 GMT" skipped="1" hostname="MacBook-Pro.local" errors="1">
  <testcase name="masterTest" time="0.000" classname="test.junitreports.SimpleTestSample">
    <error type="java.lang.IllegalStateException" message="Simulating a llegal state.">
      <![CDATA[java.lang.IllegalStateException: Simulating a llegal state.
	at test.junitreports.SimpleTestSample.masterTest(SimpleTestSample.java:12)
    ........ //Intentionally trimming the stacktrace for breivity
    ........	
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
    </error>
  </testcase> <!-- masterTest -->
  <testcase name="childTest" time="0.000" classname="test.junitreports.SimpleTestSample">
    <skipped/>
  </testcase> <!-- childTest -->
  <testcase name="iShouldNeverBeExecuted" classname="test.junitreports.SimpleTestSample">
    <skipped/>
  </testcase> <!-- iShouldNeverBeExecuted -->
</testsuite> <!-- test.junitreports.SimpleTestSample -->
```

**This is how the xml generated under `suite/` folder will look like (This can be visualised as a TestNG report in xml format)**
This report has the new category of `ignored` tests being shown for TestNG users.

`cat suite/test.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by test.junitreports.LocalJUnitXMLReporter -->
<testsuite hostname="MacBook-Pro.local" ignored="1" name="test" tests="2" failures="1" timestamp="24 Nov 2016 15:45:54 GMT" time="0.002" errors="0">
  <testcase name="masterTest" time="0.001" classname="test.junitreports.SimpleTestSample">
    <failure type="java.lang.IllegalStateException" message="Simulating a llegal state.">
      <![CDATA[java.lang.IllegalStateException: Simulating a llegal state.
	at test.junitreports.SimpleTestSample.masterTest(SimpleTestSample.java:12)
	at test.junitreports.JUnitReportsTest.runTest(JUnitReportsTest.java:48)
	at test.junitreports.JUnitReportsTest.testJUnitXMLReporter(JUnitReportsTest.java:30)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
... Removed 50 stack frames]]>
    </failure>
  </testcase> <!-- masterTest -->
  <testcase name="childTest" time="0.0" classname="test.junitreports.SimpleTestSample">
    <skipped/>
  </testcase> <!-- childTest -->
  <testcase name="iShouldNeverBeExecuted" time="0.0" classname="test.junitreports.SimpleTestSample">
    <ignored/>
  </testcase> <!-- iShouldNeverBeExecuted -->
</testsuite> <!-- test -->
```

**Comment by juherr** [comment] 2016-11-24 16:20
LGTM

**Comment by krmahadevan** [comment] 2016-11-24 16:22
@juherr Thank you. Can you please help approve the PR and kindly help it get merged ?

**Closed** 2016-11-25 17:50 UTC
Labels: Feature: junit, Feature: report, Feature: skip test, xml
