### ISSUE TITLE
ITestListener's methods get called multiple times

### ISSUE THREAD

**Issue by PythonDarkening** [cbeust/testng#2290] opened 2020-04-04 07:14 UTC
### TestNG Version
> Note: only the latest version is supported
all the versions: 7.0.x and even the version 6.14.3

### Expected behavior
TestNG will execute tests only once

### Actual behavior
When I have two tests in a testng.xml file one of them is called multiple times, but running only single test works well

This issue is the same as the bug closed: https://github.com/cbeust/testng/issues/956

### Is the issue reproducible on a runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
**The main testng.xml have the following information**:

```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="mySuite" configfailurepolicy="continue" verbose="1" parallel="false">
    <suite-files>
        <suite-file path="MyTestClass.xml" />
    </suite-files>
</suite>
```

**The suite file called by the main testng.xml file contains the following:**

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="MyTestClass" verbose="1" parallel="tests" thread-count="2" configfailurepolicy="continue">
        <test name="testName 1">
            <classes>
                <class name="MyTestClass" />
            </classes>
        </test>
        <test name="testName 2">
            <classes>
                <class name="MyTestClass" />
            </classes>
        </test>
</suite>
```

**This is the Java Test class:**

```java
    public class MyTestClass extends BaseTest {

	@Test()
    public void test1() {
    	System.out.println("test1");
    }

	@Test()
    public void test2() {
    	System.out.println("test2");
    }
    }
```

**This is the BaseTest class which extends the above class:**

```java
    @Listeners(TestAnalyzer.class)
    public class BaseTest {

    @BeforeClass(alwaysRun = true, description = "Setup Environment")
    public void setupBeforeClass(@Optional("chrome") String browser, ITestContext context){
    	// my setup steps here such as driver creation ...

    }

    @AfterClass(alwaysRun = true, description = "WebDriver TearDown")
    public void tearDown(){
        log.info("Closing the driver");
        driver.quit();
    }
    }
```

**And this is the class that implements the interface "ITestListener"**

```java
    public class TestAnalyzer implements ITestListener {

    @Override
    public void onTestStart(ITestResult result) {
    	// HERE IS THE ISSUE!!!!
        log.info(String.format("Executing test: %s", result.getName());
    }
    }
```

**Comment by krmahadevan** [comment] 2020-04-04 07:17
@PythonDarkening - pls include a sample that can be used to reproduce the problem.

**Comment by PythonDarkening** [comment] 2020-04-04 07:30
> @PythonDarkening - pls include a sample that can be used to reproduce the problem.

Done @krmahadevan 

Please if you have any doubt or comment let me know

**Comment by krmahadevan** [comment] 2020-04-04 15:49
@PythonDarkening - This should get fixed once TestNG `7.2.0` is released since it was fixed as part of addressing https://github.com/cbeust/testng/issues/2220

So please wait for `7.2.0` to be released and try again.

**Closed by krmahadevan** 2020-04-04 15:49 UTC

**Comment by PythonDarkening** [comment] 2020-04-04 16:25
@krmahadevan thanks for your comments but I would like to know when would be that release for TestNG? Also if you can provide a patch in order to add it to my framework would be awesome

**Comment by krmahadevan** [comment] 2020-04-04 16:43
@PythonDarkening 

> I would like to know when would be that release for TestNG

It should be released soon. I dont have the exact date/timelines for this.

> Also if you can provide a patch in order to add it to my framework would be awesome

No I dont have a patch. But the easiest thing to do would be to get rid of the listener references via the `@Listeners` annotation and add them via the suite file using `<listeners>` tag or via [ServiceLoader](https://testng.org/doc/documentation-main.html#listeners-service-loader) mechanism

**Comment by PythonDarkening** [comment] 2020-04-04 17:06
Ok, just to make it clear to me, what I understood is that removing the “@Listener” annotation at class level and put it in the xml file it is a work around for this issue?

**Comment by krmahadevan** [comment] 2020-04-04 17:37
Yes!

**Comment by PythonDarkening** [comment] 2020-04-04 17:56
Ok, I’ll try
