### ISSUE TITLE
InvocationCount doesn't work with running tests in parallel

### ISSUE THREAD

**Issue by louis57** [cbeust/testng#1758] opened 2018-04-13 09:22 UTC
### TestNG Version 6.14.3
For some reason, I need to execute my tests parallel on IE11 and Chrome (parallel="tests"), each browser on separated Node machine, and the @Test annotation should be run for multiple number of times (invocationCount=2). 

This is my testng.xml:

```xml
    <suite name="Parallel" parallel="tests" thread-count="2">    
        <test name="Performance Test Chrome">
            <parameter name="browser" value="Chrome"/>            
            <parameter name="remoteURL" value="http://myIP1:5555/wd/hub"/>
            <parameter name="user" value="user1"/>
            <classes>
                <class name="com.TestClass"/>
            </classes>
        </test>
        <test name="Performance Test IE11">
            <parameter name="browser" value="IE" />            
            <parameter name="remoteURL" value="http://myIP2:5555/wd/hub"/>
            <parameter name="user" value="user2"/>
            <classes>
                <class name="com.TestClass" />
            </classes>
        </test>
    </suite>
```

This is snippet of my TestClass:

```java
    public class TestClass {
        public WebDriver webDriver;
    
        @Parameters({"browser", "remoteURL"})
        @BeforeTest
        public void setUp(String browser, String remoteURL) throws Exception {      
            if (browser.equalsIgnoreCase("chrome")) {            
                ChromeOptions optionsChrome = new ChromeOptions();                
                webDriver = new RemoteWebDriver(new URL(remoteURL), optionsChrome);            
            } else if (browser.equalsIgnoreCase("ie")) {            
                InternetExplorerOptions optionsIE = new InternetExplorerOptions();                
                webDriver = new RemoteWebDriver(new URL(remoteURL), optionsIE);            
            } else
                throw new Exception("Browser is not supported");            
        }

        @Parameters({"user"})
        @Test(invocationCount = 2, threadPoolSize = 2)
        public void parallelTest(String user) {        
            login(user);        
        }

        @AfterTest
        public void tearDown() {
            webDriver.quit();
        } 
    }
```

**Expect**: The test should be run on each browser on respectively Node machines and performed @Test annotation 2 times, in parallel. I have 2 different users to avoid sessions

**Actual**: Browsers are actually opened at the same time on 2 nodes, but the test steps don't run through, they get stuck with `NoSuchElementException`, at the login page

Note that if I run @test annotation only with `parallel="tests"` OR `invocationCount=2` alone, then the test is executed successfully as expected respectively. When I combine `parallel` AND `invocationCount` then i get this issue. I execute test within IntelliJ, by right click on testng.xml and run.

Is the combination between `parallel="tests"` and `invocationCount=2` possible? Is it related to TestNG or IntelliJ? Any help much appreciated. Thanks

**Comment by krmahadevan** [comment] 2018-04-18 04:24
I dont think there's any problem with TestNG per se. TestNG does spin off the `@Test` methods in parallel when you have a combo of both `parallel=tests` and `invocationCount`.

Here's a full fledged TestNG only sample

```java
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class SampleTest {
    @Parameters({"age"})
    @Test(invocationCount = 2, threadPoolSize = 2)
    public void testMethod(int age) {
        System.err.println("Age is [" + age + "] on thread [" + Thread.currentThread().getId() + "]");
    }
}
```

```java
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.util.Arrays;

public class IssueTest {
    @Test
    public void testMethod() {
        XmlSuite xmlsuite = createXmlSuite("my_suite");
        XmlTest xmltest1 = createXmlTest(xmlsuite, "my_test1", SampleTest.class);
        xmltest1.addParameter("age", "10");
        XmlTest xmltest2 = createXmlTest(xmlsuite, "my_test2", SampleTest.class);
        xmltest2.addParameter("age", "20");
        System.err.println(xmlsuite.toXml());
        TestNG testng = create(xmlsuite);
        xmlsuite.setParallel(XmlSuite.ParallelMode.TESTS);
        testng.setVerbose(2);
        testng.run();
    }

    private static XmlSuite createXmlSuite(String name) {
        XmlSuite result = new XmlSuite();
        result.setName(name);
        return result;
    }

    private static XmlTest createXmlTest(XmlSuite suite, String name, Class<?>... classes) {
        XmlTest result = new XmlTest(suite);
        result.setName(name);
        int index = 0;
        for (Class<?> c : classes) {
            XmlClass xc = new XmlClass(c.getName(), index++, true /* load classes */);
            result.getXmlClasses().add(xc);
        }
        return result;
    }
    private static TestNG create(XmlSuite... suites) {
        TestNG result = create();
        result.setXmlSuites(Arrays.asList(suites));
        return result;
    }

    private static TestNG create() {
        TestNG result = new TestNG();
        result.setUseDefaultListeners(false);
        result.setVerbose(0);
        return result;
    }
}
```

The output is as below

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="my_suite">
  <test thread-count="5" name="my_test1">
    <parameter name="age" value="10"/>
    <classes>
      <class name="com.rationaleemotions.github.issue1758.SampleTest"/>
    </classes>
  </test> <!-- my_test1 -->
  <test thread-count="5" name="my_test2">
    <parameter name="age" value="20"/>
    <classes>
      <class name="com.rationaleemotions.github.issue1758.SampleTest"/>
    </classes>
  </test> <!-- my_test2 -->
</suite> <!-- my_suite -->

Age is [20] on thread [16]
Age is [20] on thread [13]
Age is [10] on thread [14]
Age is [10] on thread [15]

===============================================
my_suite
Total tests run: 4, Failures: 0, Skips: 0
===============================================


===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

The problem I see in your code is that you are creating a web driver object in a `@BeforeTest` method (which gets executed once per `<test>` tag) and then trying to have your methods share the object. So multiple invocations of `@Test` method are going to be running on the same browser instance, which is incorrect.

Closing this issue as **Not a bug**

Please feel free to provide a pure TestNG sample (similar to the one that I shared), if you are still seeing this as a problem.

**Closed by krmahadevan** 2018-04-18 04:24 UTC
Labels: Feature: invocationCount, Feature: parallel
