### ISSUE TITLE
Test case Dependency overwrites priority in TestNG 

### ISSUE THREAD

**Issue by nirajsharma999** [cbeust/testng#1121] opened 2016-08-23 04:13 UTC
Meta -

OS: Windows 7

Selenium Version: 2.53.0 WebDriver

Browser: Chrome

Expected Behavior - While Running Tests with the combination of dependency and priority through testNG the priority must have higher execution precision.

Actual Behavior - The Dependency overwrites the precision of priority.

Steps to reproduce - Please execute below mentioned simple Driver class.

```java
package test.pack;

import org.testng.annotations.Test;

public class dependencyTest {

@Test(priority = 1)
public void testMethod001() {
    System.out.println("TC-1");
}

@Test(dependsOnMethods = { "testMethod001" }, priority = 1)
public void testMethod002() {
    System.out.println("TC-2");
}

@Test(dependsOnMethods = { "testMethod002" }, priority = 1)
public void testMethod003() {
    System.out.println("TC-3");
}

@Test(dependsOnMethods = { "testMethod001" }, priority = 2)
public void testMethod004() {
    System.out.println("TC-4");
}
}
```

```
######Output #######
TC-1
TC-2
TC-4
TC-3
PASSED: testMethod001
PASSED: testMethod002
PASSED: testMethod004
PASSED: testMethod003

Default test
Tests run: 4, Failures: 0, Skips: 0
Default suite

Total tests run: 4, Failures: 0, Skips: 0
```

**Comment by juherr** [comment] 2016-08-23 07:12
Thanks for the report.

Closed as duplicate of #474

**Closed by juherr** 2016-08-23 07:12 UTC
Labels: Feature: dependsOn, Feature: priority
