### ISSUE TITLE
Run test after finish of some parallel tests in a test suite

### ISSUE THREAD

**Issue by Amr1977** [cbeust/testng#1904] opened 2018-08-21 05:12 UTC
Given parallel Tests A, B, C, we need to run test  D only after completion of both tests A and B and in parallel with test C (if still running), is this currently possible ?

https://stackoverflow.com/q/51940397/1356559

**Comment by juherr** [comment] 2018-08-23 18:29
No, but it should.

You have to configure a dependency from D to A and B (by dependsOnMethods or by using groups).
But currently, we have an issue when parallel is used with an order feature.

**Comment by wengm** [comment] 2018-08-23 19:41
If A,B,C,D are test methods, use `dependsOnMethods `to solve it. If they are `<test>`, then use `dependsOnGroups `to solve it.

**Comment by Amr1977** [comment] 2018-08-23 22:51
@wengm A, B, C, D are <test> elements running in parallel, I already tried `dependsOnGroups` but it seems to run A & B again (and in series) in D's thread (in addition to their own parallel tests), as a work around I am thinking about creating .lock files for A and B that gets monitored by D periodically, so that D proceeds on removal of all these lock files.

**Comment by krmahadevan** [comment] 2018-08-24 02:57
@juherr - Which issue are you referring to? I thought the parallel execution had a problem when using `priority` (soft dependencies) and not with `dependsXXX` (hard dependencies).

@Amr1977 - Just to clear out ambiguities, can you please help share a simple standalone example that can be used to reproduce the problem ?

**Comment by Amr1977** [comment] 2018-08-24 03:33
@krmahadevan  Given testng.xml containing a suite, this suite contains A, B, C, D which are parallel test elements, we need test D to start as soon as both A and B are finished, regardless of test C state.

**Comment by krmahadevan** [comment] 2018-08-24 03:37
@Amr1977 

When you say **test element** are you referring to `@Test` annotated method (or) are you referring to `<test>` tag ? 

If you are referring to `@Test` annotated method, then you would need to share a sample, because this is a straight forward case wherein it should work if you use `dependsOnMethods` (or) `dependsOnGroups`

If you are referring to `<test>` tag, then I dont think its currently possible to do this because dependencies AFAIK, should be confined within a single `<test>` and not spawn across `<test>` tags.

**Comment by Amr1977** [comment] 2018-08-24 03:40
@krmahadevan  That was all about test tags in suite xml file, Yes I have to make a workaround, thank you very much gentlemen.

**Comment by krmahadevan** [comment] 2018-08-24 03:44
Closing this issue with resolution as _question answered_

**Closed by krmahadevan** 2018-08-24 03:44 UTC
Labels: Feature: dependsOn, Feature: parallel, Need: sample

**Comment by juherr** [comment] 2018-08-24 04:36
@krmahadevan I can't remember. Did we fix the issue with hard dependencies?
