### ISSUE TITLE
How to use multiple IAnnotationTransformer's? 

### ISSUE THREAD

**Issue by drapostolos** [cbeust/testng#2441] opened 2020-12-18 10:52 UTC
### TestNG Version
> 7.3.0

### Expected behavior
Have this in the console
```
*AnnotationTransformer1* m1
*AnnotationTransformer1* m2
*AnnotationTransformer2* m1
*AnnotationTransformer2* m2
```

### Actual behavior
This is in the console
```
*AnnotationTransformer2* m1
*AnnotationTransformer2* m2
```

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I have the following testng.xml where I want to specify multiple `IAnnotationTransformer` implementations. One is provided from a library, that I can't change. One is my own. I would prefer not to extend the library one.

```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite configfailurepolicy="continue" name="some-name" verbose="2">
    <listeners>
		<listener class-name="annotation.transformer.AnnotationTransformer1" />
		<listener class-name="annotation.transformer.AnnotationTransformer2" />
    </listeners>
	<test name="some-test-name" group-by-instances="true">
		<packages>
			<package name="annotation.transformer.*" />
		</packages>
	</test>
</suite>
````

TestClass

```java
package annotation.transformer;
import org.testng.annotations.Test;

public class Tests {
	@Test
	public void m2() throws Exception {
		System.out.println("m1");
	}
	@Test
	public void m1() throws Exception {
		System.out.println("m2");
	}
}
```

My two `IAnnotationTransformer` implementations:
```java
package annotation.transformer;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import org.testng.IAnnotationTransformer;
import org.testng.annotations.ITestAnnotation;

public class AnnotationTransformer1 implements IAnnotationTransformer{
	@Override
	public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
		if(testMethod != null) {
			System.out.println("*AnnotationTransformer1* " + testMethod.getName());
		}
	}
}
```

```java
package annotation.transformer;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import org.testng.IAnnotationTransformer;
import org.testng.annotations.ITestAnnotation;

public class AnnotationTransformer2 implements IAnnotationTransformer{
	@Override
	public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
		if(testMethod != null) {
			System.out.println("*AnnotationTransformer2* " + testMethod.getName());
		}
	}
}

```

**Comment by krmahadevan** [comment] 2020-12-31 04:41
@drapostolos - Currently TestNG does not allow you to wire in more than one `IAnnotationTransformer` (Now historically why this was decided so is not clear to me as well). But you can build a composite annotation transformer which can still work with multiple annotation transformers internally.

Please refer to https://github.com/cbeust/testng/issues/1894#issuecomment-412249299 for a full fledged sample.

Since this topic is already being discussed as part of https://github.com/cbeust/testng/issues/1894 I am going to close this as a duplicate of https://github.com/cbeust/testng/issues/1894

**Closed by krmahadevan** 2020-12-31 04:41 UTC
