### ISSUE TITLE
JSON Data cannot be transferred

### ISSUE THREAD

**Issue by lybMavis** [cbeust/testng#1119] opened 2016-08-19 07:16 UTC
When I use dataprover, I can't transfer data in JSON format.

next is   issus contexts:

```
java.net.SocketException: Software caused connection abort: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    at java.io.BufferedWriter.flush(BufferedWriter.java:254)
    at org.testng.remote.strprotocol.JsonMessageSender.sendMessage(JsonMessageSender.java:41)
    at org.testng.remote.strprotocol.MessageHub.sendMessage(MessageHub.java:43)
    at org.testng.remote.strprotocol.RemoteTestListener.onFinish(RemoteTestListener.java:34)
    at org.testng.TestRunner.fireEvent(TestRunner.java:1232)
    at org.testng.TestRunner.afterRun(TestRunner.java:1023)
    at org.testng.TestRunner.run(TestRunner.java:636)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
```

**Comment by juherr** [comment] 2016-08-19 07:50
I suppose you are using eclipse. Could you confirm?

Ping @missedone

**Comment by missedone** [comment] 2016-08-19 08:13
@lybMavis
did this issue happen only when using DataProvider? what if you run a normal test case (no DataProvider), will you see the same issue?

**Comment by lybMavis** [comment] 2016-08-19 08:42
@juherr  yes    This problem is generated in eclipse

**Comment by lybMavis** [comment] 2016-08-19 08:44
@missedone When I use DataProvider, only JSON has been reported to such a issue

**Comment by missedone** [comment] 2016-08-19 08:59
could you share a sample project for reproducing this issue?

**Comment by lybMavis** [comment] 2016-08-19 10:00
@missedone  

this is test:
@Test(dataProvider = "addPlatPersonInfo", dataProviderClass = BaseDataPreper.class)
	public void addPlatPersonInfo(String url, int result, Map params, int length) throws Exception {
}

this is DataProvider:
@SuppressWarnings("unchecked")
	@DataProvider(name = "addPlatPersonInfo")
	public static Object[][] addPlatPersonInfo() throws InterruptedException, BiffException, IOException {
		
		List<Map<String, Object>> list = ExcelDealUtil.getParamsFromExcel(PropertiesUtil.getValueFromKey("base.excel"),
		        "addPlatPersonInfo", "post");
		Object a[][] = new Object[list.size()][4];
		for (int i = 0; i < list.size(); i++) {
			Thread.sleep(10);
			String url = "base/addPlatPersonInfo";
			Map<String, Object> map = new HashMap<String, Object>();
			map = (Map<String, Object>)list.get(i).get("params");
			String params = JsonUtils.object2Json(map);
			a[i][0] = RequestDeal.reqSdkUrl(url, params, "post");
			Map<String, Object> tempMap = (Map<String, Object>)list.get(i).get("expectedMap");
			a[i][1] = Integer.parseInt(tempMap.get("expectedCodeResult").toString());
			a[i][2] = params ;
			a[i][3] = i;
		}
		
		return a;
	}
The exclusion method is found to be a problem with this paramete “			a[i][2] = params ;”r, according to the abnormal JsonMessageSender feeling that is internally quasi changed (for JSON format data).a[i][2] = params ;

**Comment by juherr** [comment] 2016-08-19 12:08
@lybMavis Could you provide an inline content of the data provider? As we don't have all your util classes nor your excel file, we are not able to reproduce the issue easily.

**Comment by juherr** [comment] 2016-09-14 07:31
I close the issue because we are not able to reproduce it for the moment.
Feel free to reopen it if you have more details to share with us.

**Closed by juherr** 2016-09-14 07:31 UTC
Labels: Need: user answer, Runner: eclipse
