### ISSUE TITLE
[Fatal Error] testng-1.0.dtd:1:3: The markup declarations contained or pointed to by the document type declaration must be well-formed

### ISSUE THREAD

**Issue by sanoj-s** [cbeust/testng#2114] opened 2019-07-18 13:39 UTC
Getting following error while parsing the testng.xml file. I am using the latest testng version: 6.14.3.

**[Fatal Error] testng-1.0.dtd:1:3: The markup declarations contained or pointed to by the document type declaration must be well-formed.
org.xml.sax.SAXParseException; systemId: http://testng.org/testng-1.0.dtd; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)**

**Comment by krmahadevan** [comment] 2019-10-13 08:26
@sanoj-s - The latest released version of TestNG is `7.0.0` please retry using that and if this is still a problem, please include your suite xml file contents as well.

**Comment by JamalMSaad** [comment] 2019-12-10 15:05
Hi, 
I a facing the same issue and i am using the latest TestNG version 7.0.0 ;
I noticed that the issue is happening when trying to parse the following .xml file 
"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Automation Tests" parallel="false" verbose="1">
    <test name="SCENARIO 1">
        <classes>
            <class name="Login.LoginTest"/>
        </classes>
    </test>
</suite>
"

here is the code where it is failing:
```
File fXmlFile = new File("testcase.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(fXmlFile);// **<<<< it is failing here**
```

**Comment by JamalMSaad** [comment] 2019-12-13 08:24
I fixed the issue by completely removing all installed JDKs and fresh install the latest one, following the following URL https://www.java.com/en/download/help/mac_uninstall_java.xml

**Comment by krmahadevan** [comment] 2020-03-12 04:00
This issue has been fixed via commit https://github.com/cbeust/testng/commit/f895124a0b46de1dc2f09c8f24503f3712694a21 and should be available in the upcoming version of TestNG

**Closed by krmahadevan** 2020-03-12 04:00 UTC
