### ISSUE TITLE
MethodInvocationHelper.java:289 throws exception java.lang.ArrayIndexOutOfBoundsException: 0 

### ISSUE THREAD

**Issue by mgandalf** [cbeust/testng#1498] opened 2017-08-04 13:29 UTC
### TestNG Version
6.11

### Expected behavior
	ThreadTimeoutException should be thrown

### Actual behavior
	MethodInvocationHelper.java:289 throws exception java.lang.ArrayIndexOutOfBoundsException: 0 
	since in call: 'exception.setStackTrace(exec.getStackTraces()[0]);' exec.getStackTraces() is empty array.

### NOTES:
In [org.testng.internal.thread.ExecutorAdapter:53] call List<Thread> threads = m_threadFactory.getThreads(); returns 0 threads in Idea.

### Is the issue reproductible on runner?

- [ unknown] Shell
- [ unknown] Maven
- [ yes] Gradle 
- [ unknown] Ant
- [ unknown] Eclipse
- [ yes] IntelliJ
- [unknown ] NetBeans

### Test case sample
1. create test method with defined timeout and make it timeout e.g.
    @Test(timeOut = 5000)
    public void testMethod() {
		while(true){
		}
	}

**Comment by juherr** [comment] 2017-08-04 19:48
Duplicate of #1493

**Closed by juherr** 2017-08-04 19:48 UTC

**Comment by umerazizm1** [comment] 2018-02-12 06:51
Install Java 32 Bit and try again. 

It might be possible that your machine is 64-bit operating system and you have installed Java JDK 64-bit but Data loader requires 32-bit java to run these commands. Java should be installed in this location "C:\Program Files (x86)\Java". 

Don't forget to change environment variable path also.
