### ISSUE TITLE
testnames switch not working properly

### ISSUE THREAD

**Issue by ekrzgra** [cbeust/testng#1224] opened 2016-10-31 12:05 UTC
### TestNG Version
testng-6.9.12

### Expected behavior
According to documentation:
> -testnames	A comma separated list of test names.	Only tests defined in a <test> tag matching one of these names will be run.

### Actual behavior
When incorrect (non exisitng) test name is entered (and it is only test name provided) then all tests in suite are executed. According to specification there should be no tests executed in such case.

### Is the issue reproductible on runner?
- [x] Shell

### Test case sample
Any test suite with tests defined in it will be good to reproduce problem.

**Comment by juherr** [comment] 2016-10-31 13:00
Thanks for the report. Could you share your `suite.xml` and the command line you are using?

**Comment by ekrzgra** [comment] 2016-11-02 08:06
Hi,

Suite:

![testng](https://cloud.githubusercontent.com/assets/2421467/19920892/9c553c5e-a0db-11e6-9346-bac2016502e4.png)

Commands I am doing:
`testng -testnames TC4,TC1 test_suite.xml` - working OK (executes TC1 only)
`testng -testnames TC4 test_suite.xml` - NOK (executes TC1, TC2 and TC3)

**Comment by krmahadevan** [comment] 2016-11-05 09:57
@juherr - I recently submitted a [PR](https://github.com/cbeust/testng/commit/a67846d92c3dd820b3458273663778e6b9c22296) around this functionality which was merged. I think this issue can be closed now.

**Comment by juherr** [comment] 2016-11-06 19:18
Duplicate of ##1178

**Closed by juherr** 2016-11-06 19:18 UTC
Labels: Feature: test selection, Runner: CLI

**Comment by juherr** [comment] 2016-11-06 19:23
@ekrzgra Could you confirm the fix for your issue with the `6.9.14-SNAPSHOT` from https://oss.sonatype.org/content/repositories/snapshots/ ?

**Comment by ekrzgra** [comment] 2016-11-07 10:13
Hi,

I can confirm that fix in 6.9.14-SNAPSHOT is working fine.

Thank you!
