### ISSUE TITLE
TestNG 7.0.0: @BeforeClass/@AfterClass getting called multiple times during test run

### ISSUE THREAD

**Issue by PredatorVI** [cbeust/testng#2156] opened 2019-09-26 15:50 UTC
Oracle Java 8u221
Maven 3.6.1
NetBeans 11.1
Windows 10

Expected result (TestNG 6.14.3):
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running debug.TestBeforeAfterClassOrdering
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Begin
  --> Doing setup
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Complete
[TestBeforeAfterClassOrdering.testMethod]: @Test Begin
  --> Running a test
[TestBeforeAfterClassOrdering.testMethod]: @Test Complete
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Begin
  --> Doing cleanup
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Complete
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.749 s - in debug.TestBeforeAfterClassOrdering

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

Actual result (TestNG 7.0.0):
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running debug.TestBeforeAfterClassOrdering
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Begin
  --> Doing setup
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Complete
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Begin
  --> Doing cleanup
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Complete
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Begin
  --> Doing setup
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Complete
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Begin
  --> Doing cleanup
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Complete
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Begin
  --> Doing setup
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Complete
[TestBeforeAfterClassOrdering.testMethod]: @Test Begin
  --> Running a test
[TestBeforeAfterClassOrdering.testMethod]: @Test Complete
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Begin
  --> Doing cleanup
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Complete
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Begin
  --> Doing setup
[TestBeforeAfterClassOrdering.setup]: @BeforeClass Complete
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Begin
  --> Doing cleanup
[TestBeforeAfterClassOrdering.cleanup]: @AfterClass Complete
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.981 s - in debug.TestBeforeAfterClassOrdering

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

Test Project Attached:
[testng-test.zip](https://github.com/cbeust/testng/files/3658677/testng-test.zip)

**Comment by javydreamercsw** [comment] 2019-09-26 19:16
I was about to write something like this when I ran into this one. It seems to be tied to the @Test annotation at a class level. I was able to "fix" this by removing that and moving groups (in my case) to the individual tests which I was trying to avoid by having them at a class level.

**Comment by bc-joshroe** [comment] 2019-10-01 23:44
This looks like a duplicate of https://github.com/cbeust/testng/issues/2152

**Comment by javydreamercsw** [comment] 2019-10-02 00:25
It does.

**Comment by juherr** [comment] 2019-10-06 10:20
Duplicate of #2152

**Closed by juherr** 2019-10-06 10:20 UTC

**Comment by HDwares** [comment] 2019-11-19 07:44
I am still facing the issue in testng 7.0.0. @Test methods run number of times <test> tag is present in testng.xml

**Comment by krmahadevan** [comment] 2019-11-20 04:56
@HDwares - Please be more elaborate. I would suggest that you create a new issue (instead of commenting on an existing issue that was closed ) with a full fledged simple standalone sample that can be used to recreate your problem

**Comment by HDwares** [comment] 2019-11-20 17:00
Suppose there are 2 Java Files:

Test1:
import org.testng.annotations.Test;

public class Test1 {
	
	@Test
	public void Test1Method1() {
		System.out.println("This is method 1 from Test 1");
	}

}
Test2:
import org.testng.annotations.Test;

public class Test2 {
	
	@Test
	public void Test2Method1() {
		System.out.println("This is method 1 from Test 2");
	}

}

And testng.xml contains:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite" verbose="2" thread-count="1">
	<test name="Test1">
		<classes>
			<class name="Test1" />
		</classes>
	</test>
	<test name="Test2">
		<classes>
			<class name="Test2" />
		</classes>
	</test>
</suite> 


When I run the testng.xml suite then I get the following results:
[RemoteTestNG] detected TestNG version 7.0.0
...
... TestNG 7.0.0 by CÃ©dric Beust (cedric@beust.com)
...

This is method 1 from Test 1
PASSED: Test1Method1

===============================================
    Test1
    Tests run: 1, Failures: 0, Skips: 0
===============================================

PASSED: Test1Method1

===============================================
    Test2
    Tests run: 1, Failures: 0, Skips: 0
===============================================

This is method 1 from Test 2
PASSED: Test1Method1
PASSED: Test2Method1

===============================================
    Test2
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
Suite
Total tests run: 2, Passes: 2, Failures: 0, Skips: 0
===============================================

Also attached is the testng run result screen shot:
![image](https://user-images.githubusercontent.com/49922820/69259850-ec1d1780-0be4-11ea-8e68-fe98aa08cb64.png)


When I changed testng plugin to 6.8.8 it started working fine.

**Comment by krmahadevan** [comment] 2019-11-21 04:17
@HDwares - From what you are saying it looks like its a TestNG eclipse plugin related problem. I can't reproduce this on IntelliJ. So please create a new issue [here](https://github.com/cbeust/testng-eclipse/issues) and include all the relevant details (TestNG version that you are using, TestNG eclipse plugin version, a full fledged simple standalone project)
