### ISSUE TITLE
DataProviders getting executed before starting test suit.

### ISSUE THREAD

**Issue by akashshinde** [cbeust/testng#883] opened 2015-11-19 20:42 UTC
Here is my scenario,
1.I am creating some assets and then storing it in class.
2.Then I am passing each asset by using Data providers to other test methods.
3.But when I try to run testng.xml file,first thing getting executing is @Dataproviders method.Where it returns 0 objects.Then executes my first step(i.e creating a asset) and now dataprovider should provide data to the next running test,but its not.It's skipping test completely

I have tried dependsonmethods and dependsongroups.But no success

**Comment by juherr** [comment] 2015-11-19 22:33
You don't explain why you want to do that and you don't share any concrete example.
It will be difficult to answser you.

And I don't see where is the issue here.

**Comment by akashshinde** [comment] 2015-11-19 22:46
ok,Let me explain.Currently I am working on API Automation projects.Where first,I am creating assets using post request.

So lets say, I have created 10 assets,Now In one ArrayList I am storing all 10 asset ID's 

and next I am providing dataProvider to second test,Dataprovider is defined like below.

`@DataProvider(name = "assets")

    public static Object[][] getAssets(){
        AssetStore assetStore = AssetStore.getSharedInstance();
        Object[][] objects = new Object[assetStore.getAssets().size()][1];
        for (int i = 0; i < assetStore.getAssets().size(); i++) {
            objects[i][1] = assetStore.getAssets().get(i);
            objects[i][0] = STATUS_OK;
        }
        return objects;
    }`

Here,when I ran test,It first executes this dataprovider method which returns 0(ZERO) objects,Then it starts test to create assets and skips next tests to whom I am providing above dataprovider.

**Comment by akashshinde** [comment] 2015-11-19 22:53
Workflow of my Test.
` createAssetTest() {`
`  // Here I am creating asset and store ID returned by response in AssetStore class.`
`} `

then I am providing data to second test method by providing this ID's as parameter.
` testAssetTest(String id) {
  // Here as dataprovider returned 0 ,this test is getting skipped.
}  `


and I don't know why dataprovider method is getting executed before

**Comment by juherr** [comment] 2015-11-19 23:08
> I don't know why dataprovider method is getting executed before

Why not? TestNG doesn't guarantee when data provider is called. By default, it doesn't guarantee the order of tests. 
The problem is your assumptions are wrong. 

Why don't you create your assets in the data provider. It is what your are supposed to do.

**Comment by juherr** [comment] 2015-11-21 22:48
@akashshinde Are we agree you configured `dependOnMethods` attribute?

```java
@Test(dataProvider = "assets", dependsOnMethods = "createAssetTest")
public void testAssetTest(String id) {
}
```

**Comment by akashshinde** [comment] 2015-11-22 22:06
@juherr Yes,I have added dependsOnGroups,even I tried with setting groups and adding group dependencies,still no luck

I set debugger to see whats going on,then I figured out testNG calculates all factory and data-provider data first before executing any test suite.That is the reason I am getting no data in data provider to run  tests with dynamic data provider.

**Comment by juherr** [comment] 2015-11-23 05:57
Which version do you use? Could you try with 6.9.9?

**Comment by juherr** [comment] 2015-11-23 06:55
Could you upgrade your examples with annotations?

**Comment by sandy999s** [comment] 2015-11-23 11:54
For these kind of sitiautions i have used lazy loading DataProvider i.e where return type is Iterator<Object[]>.....which actually solved my issue.

so for your issue, it may change like


@DataProvider(name = "assets")
    public static Iterator<Object[]> getAssets(){
        AssetStore assetStore = AssetStore.getSharedInstance();
        ArrayList<Object[]> alist=new ArrayList<Object[]>();
                for (int i = 0; i < assetStore.getAssets().size(); i++) {
               alist.add(new Object[]{assetStore.getAssets().get(i),"STATUS_OK"});
        }
        return alist.iterator();
    }


Can you try this above and let us know

**Comment by juherr** [comment] 2015-11-23 12:25
It could be a workarround but it should work with `Object[][]` too, and I was not able to reproduce @akashshinde issue.

**Comment by akashshinde** [comment] 2015-11-24 19:11
@sandy999s using lazy providers,I am able to executes tests properly
@juherr yes I am using 6.9.9 version

**Comment by krmahadevan** [comment] 2018-05-31 04:10
Closing this issue based on above comment.

**Closed by krmahadevan** 2018-05-31 04:10 UTC
Labels: Feature: data-provider

**Comment by saumildharia** [comment] 2018-06-12 21:17
I have a similar usecase, In testng.xml suite file I have a bunch of tests and the run is controlled using preserver order. The last test in the  testng.xml uses @Factory with data provider annotations. When I execute the testng.xml suite file the @Dataprovider executes first. 

Is there a way we can control the execution of @Dataprovider method just before the Test and not at the start of the test suite.

I have tried lazy loading approach also, but it did not work

Testng verison 6.14.3

**Comment by juherr** [comment] 2018-06-12 22:10
If I understand well your need, I'd like to add a dependency between a test method and a data provider, and run the data provider after the test.

But by design, TestNG is first building the graph of tests, order them and then run them.
Running data providers is part of the first step.
I don't think we will change it soon.

@krmahadevan Do you see any workarround?

**Comment by saumildharia** [comment] 2018-06-12 22:29
@juherr Let me state it again, the usecase is that the dataprovider method should be called just before the test which uses the dataprovider and not at the very begening of the test suite.

As per your above comment I understand that this type of usecase is not supported as how the TestNg is designed?

**Comment by krmahadevan** [comment] 2018-06-13 03:09
@juherr - I dont think we have any work-around for situations that involve a combo of `@Factory` and a `dataProvider` because as you already pointed out, TestNG first goes about instantiating test classes, binds those instances to the `ITestNGMethod` instances and then at a later stage the test methods get executed. 

@saumildharia 
Here's the summary

* `@Factory` + data provider - Data provider is always called at the very beginning (irrespective of whether you use `Object[][]` for eager or `Iterator<Object[]>` for lazy loading)
* `@Test` + data provider - Data provider is ONLY called when the `@Test` is about to be executed. Here you can use the `Iterator` model to make it lazy loading.

**Comment by saumildharia** [comment] 2018-06-13 17:39
@krmahadevan @juherr Thanks for the info, in future is there a plan to add support for @Factory + data provider use case?

**Comment by krmahadevan** [comment] 2018-06-13 17:40
@saumildharia - It would require a bit of work in terms of revamping the TestNG internals. so cant commit for sure

**Comment by AdityaYadav29** [comment] 2021-04-05 05:23
@krmahadevan What if we override the iterator function to create the object?

**Comment by krmahadevan** [comment] 2021-04-05 05:28
@AdityaYadav29 - Not sure what you are talking about. But if you have a fix in mind, please feel free to propose a PR and we would be more than happy to help with the review

**Comment by AdityaYadav29** [comment] 2021-04-05 05:39
What I meant is, if we override the method of the iterator so that the object is created only when next() is called?

**Comment by krmahadevan** [comment] 2021-04-05 05:50
@AdityaYadav29 - I understand what you mean when you say "override the iterator function", but my question was more around where are you talking about ? The iterator's complete `next()` invocation happens at the very beginning itself when there's a `@Factory` + `dataprovider` combination, because TestNG first creates Test class objects and only then goes about using these instances to run tests. So it really doesn't matter what you do with the `Iterator`

1. Is it in your tests project (or)
2. Is it in TestNG ? If its in TestNG, as I already called out earlier, it is an invasive change and needs a bit more work to be done.

**Comment by AdityaYadav29** [comment] 2021-04-05 06:08
@krmahadevan thank you for the info. Yes it was in the TestNG. I was trying to achieve this while running the particular test after other test suites have run and I wanted to use the data that was being produced in one of the test as a @DataProvider with @Factor

**Comment by krmahadevan** [comment] 2021-04-05 08:58
If you are looking at sharing data between multiple `<test>` then you can make use of `setAttribute()` and `getAttribute()` in the `ISuite` object. But if you want to share data between multiple `<suites>` then you are better off in building your own data sharing mechanism that is singleton in nature.

**Comment by mperiyasamy** [comment] 2021-05-24 18:05
Had similar issue and the Lazy implementation works fine for me too 👍
