### ISSUE TITLE
TestNG 7.4.0  Can not skip test through listener

### ISSUE THREAD

**Issue by bearxc** [cbeust/testng#2522] opened 2021-04-15 19:42 UTC
It looks like  testng  continue execute test   even there is skip exception has been generated  through listener

```java
public class TestListener implements  IInvokedMethodListener {
  @Override
    public void beforeInvocation(IInvokedMethod invokedMethod, ITestResult result) {
            if (method.getName().contains("oneTest"))
            throw new SkipException("skip test ...");
   }
   
  @Override
    public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
    }
}
```

```java
@Listeners({TestListener.class})
public class TestSample  {

    @Test()
    public void oneTest() {
        System.out.println("aaaaaaa");
        Assert.assertEquals(1,2);
    }

    @Test()
    public void twoTest() {
        Assert.assertEquals(1,1);
    }
}
```

when run TestSample ,  
```  
[Utils] [WARN] [Warning] Caught a [SkipException] exception from one of listeners com.sample.tests.TestListener. Will mark [com.sample.tests.TestSample.oneTest()] as SKIPPED.
aaaaaaa
.....
....
......
```

testNG still continue execute code .

`BaseInvoker.java` catch the exception , but does not handle it properly ...  

```java
  InvokedMethodListenerInvoker invoker =
        new InvokedMethodListenerInvoker(listenerMethod, testResult, testResult.getTestContext());
    for (IInvokedMethodListener currentListener : m_invokedMethodListeners) {
      try {
        invoker.invokeListener(currentListener, invokedMethod);
      } catch (SkipException e) {
        String msg = String.format(
            "Caught a [%s] exception from one of listeners %s. Will mark [%s()] as SKIPPED.",
            SkipException.class.getSimpleName(), currentListener.getClass().getName(),
            invokedMethod.getTestMethod().getQualifiedName());
        Utils.warn(msg);
        testResult.setStatus(ITestResult.SKIP);
        testResult.setThrowable(e);
      }
    }
```

**Comment by bj-9527** [comment] 2021-04-20 06:10
Hi, 
Maybe it related to the code `if (method.getName().contains("oneTest"))` in the `beforeInvocation` methed.
I use `if (invokedMethod.getTestMethod().getMethodName().contains("oneTest"))` instead and it shows:
![image](https://user-images.githubusercontent.com/73265830/115345977-23c92e00-a1e2-11eb-82c1-db74ede8b9e5.png)

**Comment by juherr** [comment] 2021-04-20 06:40
@bj-9527 Could you tell us what is the difference between `method` and `invokedMethod`, and what is the result of `method.getName()`?

**Comment by bj-9527** [comment] 2021-04-20 07:06
Sorry, I have the concern too. Maybe the reporter @bearxc could clarify how to get the `method`.

**Comment by bearxc** [comment] 2021-04-20 13:17
System.out.println("aaaaaaa");

This line should not be executed  when throw skip exception  on listener

**Comment by dfosticupgrade** [comment] 2021-04-21 20:40
i found same issue

**Comment by juherr** [comment] 2021-04-22 12:51
I think `method.getName()` is not returning what you expect.
You can check the expected behavior here: https://github.com/cbeust/testng/blob/master/core/src/test/java/test/name/NameTest.java

**Comment by dfosticupgrade** [comment] 2021-04-22 13:38
> I think `method.getName()` is not returning what you expect.
> You can check the expected behavior here: https://github.com/cbeust/testng/blob/master/core/src/test/java/test/name/NameTest.java

`method.getName()`  has nothing to do, you can just skip nomatter what
`    public void beforeInvocation(IInvokedMethod invokedMethod, ITestResult result) {
            throw new SkipException("skip test ...");
   }`

the behaviour is still the same

**Comment by bearxc** [comment] 2021-04-22 17:13
This is nothing to do with   method.getName().  

when  running oneTest() ,  listener  throws skip exception on   beforeInvocation  , TestNG catches that exception and still continue execute   the test code from oneTest() ( System.out.println("aaaaaaa";) , that is not correct.


expect behaviour : TestNG should skip execution on  oneTest() immediately.

**Comment by krmahadevan** [comment] 2021-04-25 12:50
This issue is a duplicate of https://github.com/cbeust/testng/issues/2415

Closing this issue.

**Closed by krmahadevan** 2021-04-25 12:50 UTC
Labels: Feature: listener, Feature: skip test
