### ISSUE TITLE
xml with beanshell works in 6.12, not in 6.14

### ISSUE THREAD

**Issue by borisivan** [cbeust/testng#1687] opened 2018-02-07 04:47 UTC
### TestNG Version
6.14.2

### Expected behavior
XML gets parsed successfully, like it does in 6.12

### Actual behavior

```java
java.lang.NullPointerException
	at org.testng.internal.Bsh.includeMethodFromExpression(Bsh.java:28)
	at org.testng.internal.XmlMethodSelector.includeMethod(XmlMethodSelector.java:60)
	at org.testng.internal.RunInfo.includeMethod(RunInfo.java:50)
	at org.testng.internal.MethodGroupsHelper.includeMethod(MethodGroupsHelper.java:86)
	at org.testng.internal.MethodGroupsHelper.collectMethodsByGroup(MethodGroupsHelper.java:67)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:56)
	at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:197)
	at org.testng.internal.TestNGMethodFinder.getBeforeClassMethods(TestNGMethodFinder.java:58)
	at org.testng.TestClass.initMethods(TestClass.java:140)
```

### Is the issue reproducible on runner?
- [ x ] Maven
- [ x ] Eclipse

### Test case sample
I have verbose set to 10, but there are no testNG log messages. Just the null pointer exception, as it tries to parse the XML. But it successfully parses the same file in 6.12 and runs the tests.

Some text redacted, but here's the XML:

```xml
<?xml version="1.0"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="thisSuite" time-out="300000" verbose="10">
    <method-selectors>
        <method-selector>
            <script language="beanshell"><![CDATA[
    
                String sanityOnly = System.getProperty("sanityOnly");
                
                if (sanityOnly == null) {
                      sanityOnly = "false";
                }
                
                if (sanityOnly.contains("true")) {
                    runMethod = groups.containsKey("sanity") && (groups.containsKey("g1") || groups.containsKey("g2") || groups.containsKey("g3"));
                } else {
                    runMethod = groups.containsKey("g1") || groups.containsKey("g2") || groups.containsKey("g3");
                }
                
                return runMethod;
                ]]></script>
        </method-selector>
    </method-selectors>
    <parameter name="sampleRate" value="0.5"/>
    <test name="theseTests">
        <classes>
            <class name="com.xxx.xxxTests"/>
            <class name="com.xxx.xxxTests2"/>
        </classes>
    </test>
</suite>
```

**Comment by krmahadevan** [comment] 2018-02-07 14:18
The problem is with your beanshell expression. Your expression is returning a `null` value (`runMethod` is `null`). Please change your beanshell to something like below (notice how `runMethod` is being initialized to `true`)

```xml
<script language="beanshell"><![CDATA[

    String sanityOnly = System.getProperty("sanityOnly");

    if (sanityOnly == null) {
          sanityOnly = "false";
    }

    runMethod = true;

    if (sanityOnly.contains("true")) {
        runMethod = groups.containsKey("sanity") && (groups.containsKey("g1") || groups.containsKey("g2") || groups.containsKey("g3"));
    } else {
        runMethod = groups.containsKey("g1") || groups.containsKey("g2") || groups.containsKey("g3");
    }
    return runMethod;
    ]]>
</script>
```

Am going to be closing this issue.

**Comment by borisivan** [comment] 2018-02-07 22:45
Thanks, and I see your point! Not sure why this was working prior to upgrading to 6.14.2.

**Closed** 2018-02-08 22:09 UTC
