### ISSUE TITLE
Maven surefire plugin not setting -suitethreadpoolsize parameter for parallel suites execution.

### ISSUE THREAD

**Issue by sjavvadi** [cbeust/testng#548] opened 2014-09-15 09:51 UTC
Currently latest surefire plugin (version 2.17) is using deprecated TestNG configure (Map) method in which Map argument is converted to CommandLineArgs. Unfortunately the suitethreadpoolsize parameter is missing and   CommandLineArgs.SUITE_THREAD_POOL_SIZE is not set and not executed.

The following fragment of code placed in org.testng.TestNG.java in method configure(Map  cmdLineArgs) will resolve this issue:

 Object  suiteThreadPoolSize = cmdLineArgs.get(CommandLineArgs.SUITE_THREAD_POOL_SIZE);
    if (null != suiteThreadPoolSize) {
        if (suiteThreadPoolSize instanceof String){
            result.suiteThreadPoolSize=Integer.parseInt((String) suiteThreadPoolSize);
        } 
        if (suiteThreadPoolSize instanceof Integer){
            result.suiteThreadPoolSize=(Integer) suiteThreadPoolSize;
        }
    }

**Comment by juherr** [comment] 2015-07-22 10:37
Duplicate of #546

**Closed by juherr** 2015-07-22 10:37 UTC
