### ISSUE TITLE
Parallel doesn't work 

### ISSUE THREAD

**Issue by symphonicon** [cbeust/testng#1676] opened 2018-01-29 08:51 UTC
### TestNG Version
6.13, 6.13.1

### Expected behavior
Tests, methods, packages run parallel to each other in different threads.

### Actual behavior
Suite runs in single thread, tests are executed one by one. 

### Is the issue reproductible on runner?
- [x] Maven
- [x] IntelliJ

### Test case sample
Two classes that print current thread they are running. 
```
public class TestParallelClassOne {
    @Test
    public void testCaseOne() {
        // Printing class name and Id of the thread on using which test method got executed
        System.out.println("Test Case One in " + getClass().getSimpleName()
                + " with Thread Id:- " + Thread.currentThread().getId());
    }
    @Test
    public void testCaseTwo() {
        //Printing class name and Id of the thread on using which test method got executed
        System.out.println("Test Case two in " + getClass().getSimpleName()
                + " with Thread Id:- " + Thread.currentThread().getId());
    }
}
```

Tests run as expected up until the TestNG 6.13 and 6.13.1

**Comment by krmahadevan** [comment] 2018-01-29 14:26
This is perhaps a possible duplicate of #1636 

Can you please check if [this](https://github.com/cbeust/testng/issues/1636#issuecomment-349182219) work-around helps till 6.14 (the fix will be available in this version) is released ?

**Comment by symphonicon** [comment] 2018-01-30 07:19
Yes, it worked. Thank you.

**Comment by krmahadevan** [comment] 2018-01-30 08:41
Closing this since 6.14 will take care of resolving this.

**Closed by krmahadevan** 2018-01-30 08:41 UTC
