### ISSUE TITLE
Getting error while running test through TestNG

### ISSUE THREAD

**Issue by mithun-kumar7** [cbeust/testng#2284] opened 2020-03-28 14:51 UTC
### TestNG Version
TestNG version 7.0.1
> Note: only the latest version is supported
### Actual behavior
[RemoteTestNG] detected TestNG version 7.0.1
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

### Is the issue reproductible on runner?

- [x] Eclipse

### Test case sample
package webServices.rest;

import org.testng.annotations.Test;

public class RADemo {
	@Test
	public void demo() {
		System.out.println("Hello World");
	}

}

**Comment by krmahadevan** [comment] 2020-03-29 04:22
Duplicate of https://github.com/cbeust/testng/issues/2223

The latest TestNG eclipse plugin should be fixing it. If this is still a problem, please file an issue in https://github.com/cbeust/testng-eclipse project which tracks Eclipse TestNG plugin issues.

**Closed by krmahadevan** 2020-03-29 04:22 UTC
