### ISSUE TITLE
TestNG DataProvider annotation regression

### ISSUE THREAD

**Issue by smaudet** [cbeust/testng#989] opened 2016-02-23 19:20 UTC
between 6.8.21 and 6.9.x there has been a dataprovider regression.

It used to be dataproviders would map to a particular method based on the containing class.

Now it appears that they pull from sort of global 'pool', and they aren't even filtering properly by supplying dataProviderClass.

Do you not have a TestNG test for this stuff yet? You need more tests for your tests, @cbeust

Will write-up a more detailed example, basically, I have:

`
class A { 
  @DataProvider(name="blah") public Iterator<Object[]> stuff() { ... } 
  @Test(dataProvider="blah") public void test1(Object... args) { ... }
}

class B { 
  @DataProvider(name="blah") public Iterator<Object[]> stuff() { ... } 
  @Test(dataProvider="blah") public void test1(Object... args) { ... }
}
`

The test1 in A and B should use the DataProvider in their classes. Not randomly pick and choose.

Already there was a regression in 6.8 I think where you have to specify the dataProviderClass...

**Comment by cbeust** [comment] 2016-02-23 19:38
It would be great if you can provide a test that fails...

Thanks!

**Comment by smaudet** [comment] 2016-02-25 16:19
Weird.

I have the test case, unless I'm doing something exactly what didn't work in my project is working in your project...

I have some other things to try, like changing the java version (8 vs 7).

A couple of questions regarding the current project. 

1) I have my tests on top of tag 6.9.5 - is this 'current release'? 6.9.10 is the last release on maven central:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.testng%22%20AND%20a%3A%22testng%22

I saw the weird behavior w. 6.9.10 but not so much with 6.8.21, and then tried 6.9.4/5, didn't see a difference, but after testing inside the project maybe I have to eat my words... if there's not something else involved (like version of maven, java, project specific things).

2) I see you are using maven-release-plugin to version things. Your maven/pom-test.xml:
  a) is that supposed to be in the root directory still?
  b) you are referencing a 6.8.22-SNAPSHOT that AFAIK doesn't exist anywhere (no tags, no maven central releases.

**Comment by juherr** [comment] 2016-02-25 20:10
What are you trying to say ? I'm not following you.

**Comment by smaudet** [comment] 2016-02-26 12:56
I'll push later today. I think it might be more informative just to see what I've done.

**Comment by smaudet** [comment] 2016-03-10 16:25
Sorry, have this on my plate still as a TODO. Have not forgotten.

**Comment by krmahadevan** [comment] 2018-05-31 03:59
Closing this issue. Please comment if this is still a problem in TestNG `6.14.3` (latest released version as of today)

I can't reproduce this using TestNG `6.14.3`
Here's what I have.

**Test classes**

```java
package com.rationaleemotions.github.issue989;

import java.lang.reflect.Method;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class ClassA {
  @DataProvider(name = "blah")
  public Object[][] stuff(Method method) {
    String m = method.getName();
    String c = method.getDeclaringClass().getName();
    System.err.println("Running data provider in ClassA for test method " + c + "." + m + "()");
    return new Object[][] {{1}};
  }

  @Test(dataProvider = "blah")
  public void test(int i) {
    System.err.println(i);
  }
}
```
```java
package com.rationaleemotions.github.issue989;

import java.lang.reflect.Method;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class ClassB {
  @DataProvider(name = "blah")
  public Object[][] stuff(Method method) {
    String m = method.getName();
    String c = method.getDeclaringClass().getName();
    System.err.println("Running data provider in ClassB for test method " + c + "." + m + "()");
    return new Object[][] {{1}};
  }

  @Test(dataProvider = "blah")
  public void test(int i) {
    System.err.println(i);
  }
}
```

**Suite xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="336_Suite-MySuite-InVM" parallel="false" verbose="2">
  <test name="989_test">
    <classes>
      <class name="com.rationaleemotions.github.issue989.ClassA"/>
      <class name="com.rationaleemotions.github.issue989.ClassB"/>
    </classes>
  </test>
</suite>
```

**output**
...
... TestNG 6.14.3 by Cédric Beust (cedric@beust.com)
...
Running data provider in ClassA for test method com.rationaleemotions.github.issue989.ClassA.test()
1
Running data provider in ClassB for test method com.rationaleemotions.github.issue989.ClassB.test()
1
PASSED: test(1)
PASSED: test(1)

===============================================
    989_test
    Tests run: 2, Failures: 0, Skips: 0
===============================================

===============================================
336_Suite-MySuite-InVM
Total tests run: 2, Failures: 0, Skips: 0
===============================================

**Closed by krmahadevan** 2018-05-31 03:59 UTC
Labels: Feature: data-provider
