### ISSUE TITLE
Configuration methods have the same test class instance when @Factory is being used

### ISSUE THREAD

**Issue by Taredel** [cbeust/testng#2428] opened 2020-11-30 15:24 UTC
### TestNG Version
> 7.3.0
### Expected behavior
For each configuration method (@BeforeClass, @BeforeMethod) corresponding test class instance created with @Factory is set
### Actual behavior
For each configuration method (@BeforeClass, @BeforeMethod) only one test class instance created with @Factory is set

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```
public class FactoryTest {

    int i;

    @Factory(dataProvider = "dp")
    public FactoryTest(int i) {
        this.i = i;
    }

    @DataProvider(parallel = true)
    public static Object[][] dp() {
        return new Object[][] {
                {5},
                {4},
                {12},
                {9},
                {2}
        };
    }

    @BeforeClass
    public void beforeClassBody()  {
        System.out.println("Before class test class instance - " + this.toString());
    }

    @Test
    public void testBody() {
        System.out.println("Test class instance in test - " + this.toString());
    }
}
```
**Custom report to print configuration method's instances**
```
public class Reporter implements IReporter {

    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites,
                               String outputDirectory) {
        suites.get(0).getResults().get("Sample test")
                .getTestContext()
                .getPassedConfigurations()
                .getAllResults()
                .forEach(x -> System.out.println(x.getInstance().toString()));
    }
}
```
**testNG xml runner**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="factory tests" >
    <test name="Sample test" parallel = "instances" thread-count="3" group-by-instances="true">
        <classes>
            <class name="FactoryTest" />
        </classes>
    </test>

    <listeners>
        <listener class-name="Reporter"/>
    </listeners>
</suite>
```
**Console Log**
```
Before class test class instance - FactoryTest@573f2bb1
Before class test class instance - FactoryTest@402f32ff
Before class test class instance - FactoryTest@48eff760
Test class instance in test - FactoryTest@48eff760
Test class instance in test - FactoryTest@573f2bb1
Test class instance in test - FactoryTest@402f32ff

Before class test class instance - FactoryTest@7c0e2abd
Before class test class instance - FactoryTest@5ae9a829
Test class instance in test - FactoryTest@7c0e2abd
Test class instance in test - FactoryTest@5ae9a829

factory tests
Total tests run: 5, Passes: 5, Failures: 0, Skips: 0

FactoryTest@5ae9a829
FactoryTest@5ae9a829
FactoryTest@5ae9a829
FactoryTest@5ae9a829
FactoryTest@5ae9a829

Process finished with exit code 0
```

There is no difference whether the test were run in parallel or not - the result is the same.

**Comment by bj-9527** [comment] 2020-12-17 06:25
The root cause of this issue is about the relationship of test method and config method. When TestNG try to build a [TestClass](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestClass.java#L115), in the init method, the config method will only record the last assignment, so in the initiated TestClass object, only one method's config method will be record and so, when generate TestResult, only a single config method will be store several times.

In this draft, I just propose a solution and only solved the beforeClass config method, please check and give comments.

**Comment by juherr** [comment] 2020-12-17 09:08
@bj-9527 I'm pretty sure the fix can work but I see 2 problems:

* it updates the public API for internal usages and I don't see a user use-case for it
* it stores everything in memory when we already have some memory issues.

I don't have a better option to propose for the moment.

**Comment by bj-9527** [comment] 2020-12-18 06:13
Maybe we can add a internal interface for internal usage for the first point.
I will also check if there's any other way to maintain the relationship between test method and config method, with less memory usage.

**Comment by krmahadevan** [comment] 2020-12-18 09:12
@bj-9527 - I concur with @juherr in terms of the memory footprint. The `TestClass` should not have to remember the entire map once the job of associating a configuration method to its corresponding object is completed and so I thought that maybe we should wipe off that map

**Comment by juherr** [comment] 2020-12-18 09:26
In fact, the TestNG model becomes a bit old, and adding too many things is making it weak.

About the current subject, I can't remember if the notion of "test instance" already exists.
I feel a test instance is composed of a test class and an instance object, and not the opposite (a test class should not have all test instances).
Saying that I don't have a more concrete idea. The subject is not easy :)

**Comment by krmahadevan** [comment] 2020-12-19 05:44
@juherr - What you are suggesting perhaps is going to involve a complete revamp at how TestNG manages objects.

Currently TestNG does not have the notion of `TestInstance`.

Here's what exists today

* `IClass` - Provides capabilities to instantiate objects of its type.
* Once the object gets instantiated its gets associated either with a `ConfigurationMethod` (or) a `FactoryMethod` or a `TestNGMethod`

So I feel that we should get the review comments fixed for this PR merged and perhaps work on a design that aligns with what you are suggesting and maybe revamp it from there (similar to what we did with the DI implementation)

**Comment by juherr** [comment] 2020-12-19 13:07
Sure, it can be done in many steps.

If the current issue can be fixed without adding new methods on the public API, I will be happy to merge the PR :)

**Comment by krmahadevan** [comment] 2020-12-19 13:55
@juherr - Yes. That is why I was mentioning that we could perhaps have the `TestClass` implement a new interface which has just this new method and we could manage it (this new interface would reside in the `internal` package).

**Comment by juherr** [comment] 2020-12-19 14:12
If `TestClass` implements a new interface, the new methods will be visible even if they come from a private interface.

A better solution would be a `TestClass` child which implements the new interface. The access to new methods will be possible by `instanceof`/cast. But I don't know if it is possible to do it without breaking things.

**Comment by krmahadevan** [comment] 2020-12-19 14:18
@juherr 

* `TestClass` even though its in `org.testng`, its a package visible class. So that ensures that the visibility is confined to within TestNG.
* Since we are going to be adding a new interface and have `TestClass` implement this new interface, we should be fine (since we are not adding this to `IClass` interface
* So we don't need to be resorting to sub-classing `TestClass`

**Comment by juherr** [comment] 2020-12-19 17:12
Right, I didn't notice the package visibility. It should do the job then 👍

**Comment by bj-9527** [comment] 2020-12-21 01:34
One thing I should mention is that this pull request only solves the 'BeforeClass' config method, should we add more map filed in `TestClass` to solve all config method?

**Comment by krmahadevan** [comment] 2020-12-21 04:40
@bj-9527 - The only two configuration methods that fall in scope is `@BeforeClass` and `@BeforeMethod`.  I dont think `@BeforeMethod` is involved/considered in the `TestClass` implementation. So once we fix the current review comments, I guess we should be good with this PR

**Closed** 2020-12-22 16:44 UTC
Labels: Feature: factory
