### ISSUE TITLE
can't run tests in paralell

### ISSUE THREAD

**Issue by AntonSyl** [cbeust/testng#1696] opened 2018-02-13 08:42 UTC
### TestNG Version
> Note: only the latest version is supported
6.14.2
### Actual behavior
Tests run one by one

### Is the issue reproductible on runner?
```
<suite name="parallelTest" verbose="1" parallel="classes" thread-count="2">
    <test name="ProjectsTest">
        <classes>
            <class name="web.tests.ProjectsTest"/>
        </classes>
    </test>
    <test name="UsersTest">
        <classes>
            <class name="web.tests.UsersTest"/>
        </classes>
    </test>
    <test name="OfflineTime">
        <classes>
            <class name="web.tests.OfflineTime"/>
        </classes>
    </test>

    <test name="Login">
        <classes>
            <class name="web.tests.LoginTest"/>
        </classes>
    </test>


</suite>
```

- [ ] Gradle

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by borisivan** [comment] 2018-02-14 15:28
I suspect this is because you have parallel=classes and not parallel=tests.

If one of your tests (as defined in the XML) had 2 classes in it, then when it got to that test, it might execute 2 at the same time. But you have 1 class in each "test" in the XML, and it's executing the "test" sections of the XML in sequence. But if you changed to parallel=tests, it would execute two of the test sections in parallel.

**Comment by AntonSyl** [comment] 2018-02-14 15:42
The same issue with parallel=tests. Works in 6.11 version

**Comment by ghenadied** [comment] 2018-02-14 16:26
Hi,

The correct suite file would have then parallel="tests". If someone wants to have parallel="classes", why not to move them under the same test tag?

**Comment by krmahadevan** [comment] 2018-02-14 18:00
@AntonSyl - I didn't quite understand your issue ?

* `parallel=classes` at a `<suite>|<test>` level would trigger parallelism only when there are more than one classes in the `<test>` tag.
* `parallel=tests` at a `<suite>` level would trigger parallelism only when there is at least two or more `<test>` in your `<suite>`.

So for which scenario is it not working when you use TestNG 6.14.2 ? Can you please share a full fledged sample that can be used to reproduce the issue ? Please include the suite xml and also the test classes (please trim them to ensure that they dont have any complex logic).

**Comment by krmahadevan** [comment] 2018-02-24 09:09
This looks like its related to https://github.com/cbeust/testng/issues/1701 and is a due to a bug in Gradle. Refer https://github.com/gradle/gradle/issues/4457

Closing this issue.

**Closed by krmahadevan** 2018-02-24 09:09 UTC
Labels: Feature: parallel, Need: user answer, Runner: Gradle
