### ISSUE TITLE
TestNG running only First test in every Test suite

### ISSUE THREAD

**Issue by ChiduDC** [cbeust/testng#2116] opened 2019-07-23 08:27 UTC
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by ChiduDC** [comment] 2019-07-23 08:29
I tried with all the latest Test NG jar 6.9.9, 6.8 & also beta version 7.0.0 - beta1 & beta 3.. still same issue exists

**Comment by krmahadevan** [comment] 2019-07-23 08:32
@ChiduDC - Couple of things.

1. The latest released version of TestNG is `7.0.0-beta7`. Please retry using that.
2. If the problem still persists, please share a sample standalone that can be used to recreate the problem.

Without a sample, we cannot do much in terms of investigating as to what is going wrong.

**Comment by cirej2000** [comment] 2019-08-30 17:39
What I'm seeing in my case is that I have run into a situation where the test instance Object being passed to the ClassMethodMap.removeAndCheckIfLast method as a key is not matching its hashcode to the key in the ClassMethodMap!  It actually fails within the java ConcurrentHashMap class.  If I debug within the ConcurrentHashmap class and fudge the hashcode of the passed key to the one from the internal concurrenthashmap.  Things proceed successfully.  If not, it fails.  This is really weird!  I dunno if it's TestNG, Java, my code or a combination!  :(

**Comment by cirej2000** [comment] 2019-08-30 21:02
My problem was in my code.  Spring config files for my autowired beans were probably marked final at some point.  Then, I must've removed the "final" keyword recently.  The hash code was still changeable because those damn fields were mutable!

**Comment by cirej2000** [comment] 2019-08-30 23:14
Not a final keyword.  But definitely make sure that if you have a base class with object fields that they should not be mutable.  @Data annotation from lombok will implicitly add @Getter @Setter to each field in your class.  If you only want a @Getter, it will punish you!

**Comment by krmahadevan** [comment] 2019-08-31 01:44
No updates from the original poster and no sample still. Closing this issue. If this is still a problem, please try using `7.0.0` and share a simple standalone test that can be used to reproduce the problem.

**Closed by krmahadevan** 2019-08-31 01:44 UTC
