### ISSUE TITLE
XML Test Suite - Exclude included methods based on excluded group tags

### ISSUE THREAD

**Issue by nik-suri** [cbeust/testng#2407] opened 2020-11-08 01:52 UTC
### TestNG Version
6.9.6

### Expected behavior
My test suite looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name"mySuite">
    <test name="My Suite">
        <groups>
            <run>
                <exclude name="NOT_LIVE" />
            </run>
        </groups>
        <classes>
            <class name="com.mypackage.MyClass">
                <methods>
                    <include name="myTest" />
                </methods>            
            </class>
        </classes>
    </test>
</suite>
```

`MyClass.myTest` is part of the `NOT_LIVE` group, and my expectation here is that it should therefore not run as part of the test suite. However, `MyClass.myTest` may soon be tagged as part of the `LIVE` group, and at that point it should run as part of the test suite.

### Actual behavior
The actual behavior is that `MyClass.myTest` is still run as part of the test suite, because explicitly including it seems to override the `NOT_LIVE` group exclusion.

### Is the issue reproductible on runner?
I am not sure what "runner" is. I use Maven, so that is checked.

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Sample test suite XML provided above.

**Comment by krmahadevan** [comment] 2020-11-08 08:56
@nik-suri - The latest released version for TestNG is `7.3.0`. So please retry using that. If the problem persists, please include the following:

1. A sample test class (please help keep this as simple as possible, just by using some sysout statements)
2. Suite xml file to be used
3. Expected output that you are looking for.

**Comment by nik-suri** [comment] 2020-11-08 22:36
@krmahadevan thanks. I just tried using TestNG `7.3.0` and the problem persists. Here are my samples:

Test Class - `Test.kt`:
```
package com.niksuri.mypackage

import org.testng.annotations.Test

class Test {
    @Test(groups = ["NOT_LIVE"])
    fun test() {
        println("This is a test")
    }
}
```

Suite XML File - `testSuite.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name"testSuite">
    <test name="My Test Suite">
        <groups>
            <run>
                <exclude name="NOT_LIVE" />
            </run>
        </groups>
        <classes>
            <class name="com.niksuri.mypackage.Test">
                <methods>
                    <include name="test" />
                </methods>            
            </class>
        </classes>
    </test>
</suite>
```

When I run this test suite, I see "This is a test" printed to the console. This is not the expected behavior. Since I have specified that `Test.test` is part of the `NOT_LIVE` group, I expect that the test should not be run. The test should be skipped.

Actual Output:
```
This is a test

==== Invoked methods
    Test.test()[pri:0, instance:com.niksuri.mypackage.Test@5d5eef3d] 1566502717
====

===============================
testSuite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================
```

When I change my XML suite to the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name"testSuite">
    <test name="My Test Suite">
        <groups>
            <run>
                <exclude name="NOT_LIVE" />
            </run>
        </groups>
        <classes>
            <class name="com.niksuri.mypackage.Test" />
        </classes>
    </test>
</suite>
```

I see this output, which is what I expect to see when I explicitly include the test method as shown in my first Suite XML sample above.

Expected Output:
```
==== Invoked methods
====

===============================
testSuite
Total tests run: 0, Passes: 0, Failures: 0, Skips: 0
===============================

[TestNG] No tests found. Nothing was run
```

**Comment by krmahadevan** [comment] 2020-11-10 18:01
@nik-suri - Looking at the TestNG implementation, it looks like TestNG is working as designed.
If a test method has been explicitly included to be run in the suite file, then it has the last say and it would get excluded.
I think you would either specify groups to be run (or) pick and choose classes/methods as your execution.
But if both are present, then the included methods has the last say. ( See [here](https://github.com/cbeust/testng/blob/6cc92dfc1a72be9b25370be73fe115c159a6bfeb/src/main/java/org/testng/internal/XmlMethodSelector.java#L77-L101)

Closing this issue with resolution as **Working as designed**

**Comment by nik-suri** [comment] 2020-11-25 19:03
@krmahadevan would you accept a PR to enhance this functionality?

Specifically, I am thinking of adding an `override` attribute to the `groups` definition in the XML suite. If the override flag is present, then the specified groups will override the explicitly included methods.

**Comment by krmahadevan** [comment] 2020-11-25 19:44
@nik-suri - Sure. Please go ahead and submit the PR. We can have it reviewed.

**Comment by nik-suri** [comment] 2020-11-25 20:14
@krmahadevan great, thanks. I wanted to confirm before starting, so I will work on this now. You can expect the PR within a week or so.

**Comment by krmahadevan** [comment] 2020-11-26 03:04
Sure. 

@juherr - Pls share your inputs on this as well.

**Comment by juherr** [comment] 2020-11-26 09:02
If I understand the issue: the current behavior excludes the union between included and excluded tests.
@nik-suri would like to include the union.

I don't have any opinion about the behavior but I'd like to keep the current one and only activate the new one by a configuration as usual.

**Comment by krmahadevan** [comment] 2020-12-19 05:51
Closed via https://github.com/cbeust/testng/pull/2430

**Closed by krmahadevan** 2020-12-19 05:51 UTC
Labels: Feature: groups, xml
