### ISSUE TITLE
Parameters threadCount and parallel doesn't work with maven 

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [cbeust/testng#987] opened 2016-02-19 11:03 UTC
[TestMultithreading_v.0.2.zip](https://github.com/cbeust/testng/files/137813/TestMultithreading_v.0.2.zip)

Related issues:
# https://github.com/cbeust/testng/issues/419 threadCount parameter does not work with ant script
# https://github.com/cbeust/testng/pull/936 Fix issue #419: parallel mode was ignored with command line

https://groups.google.com/forum/#!topic/testng-users/kRmLWw6ts0U

**Version**
TestNG: 6.9.11-SNAPSHOT
Surefire: 2.19

When I try to set parallel and threadCount via surefire plugin TestNG doesn't accept values. 
Tried both:

```
<configuration>                    
    <parallel>tests</parallel>
    <threadCount>3</threadCount>
</configuration>
```

```
<property>
    <name>tests</name>
    <value>classes</value>
</property>
<property>
    <name>threadCount</name>
    <value>3</value>
</property>
```

See detailed example in attached project:
[TestMultithreading_v.0.2.zip](https://github.com/cbeust/testng/files/137813/TestMultithreading_v.0.2.zip) 

Additional info:
If I set this parameters in TestSuite.xml file it works fine.

**Comment by juherr** [comment] 2016-02-19 12:40
Potential related Surefire issue: https://issues.apache.org/jira/browse/SUREFIRE-1179

Ping @Tibor17 Fyi

**Comment by kermek** [comment] 2016-02-19 13:26
According to the reporter's version that issue (https://issues.apache.org/jira/browse/SUREFIRE-1179) should be fixed:
*Fix Version/s: 2.19*

**Comment by sergejjkim** [comment] 2016-02-26 13:25
please take a look at https://github.com/cbeust/testng/issues/991#issuecomment-189271235

**Comment by juherr** [comment] 2016-02-26 13:51
@aTan-aka-Xellos As you are using a `testng.xml`, could you try to configure parallel and threadcount there?

**Comment by Tibor17** [comment] 2016-02-26 16:56
@aTan-aka-Xellos 
Please see our integration tests. We used TestNG 6.9.6 but I think the threadCount should be passed in system properties.
https://github.com/Tibor17/maven-surefire/commit/5105a84099af74d579d5975b25e1bdfe04333643

Your configuration is different from ours.

**Comment by aTan-aka-Xellos** [comment] 2016-02-26 17:27
@juherr Please read issue carefully, I add it exactly for avoid such questions:

> 
> Additional info:
> If I set this parameters in TestSuite.xml file it works fine.

**Comment by aTan-aka-Xellos** [comment] 2016-02-26 17:45
@Tibor17 
I've looked into it and I can't find any differences. I also tried set it in properties. In attached example there is not exactly 'dataproviderthreadcount' value but I've tried it (as threadCount also). 

Also please note that in attached example only 2 mixed versions how I've tried set them (properties and via <parallel>tests</parallel> approach). But tried a lot of different combinations. Checked stackoverflow and so on...

Could someone try to make my example working in parallel via pom.xml please? If needed provide sources  different way (from git, not attached zip) I'll do it.

**Comment by Tibor17** [comment] 2016-02-26 23:00
These two configurations are compatible. they are applicable if and only if you do not use <suiteXmlFiles/> in Surefire/Failsafe plugin. This means this configuration works fine if you have only ordinal tests without `suites.xml` If you use suites then do not use this configuration and tie to configuration in `suites.xml` or `dataproviderthreadcount` and `parallel`.
For more information see our documentation
http://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html
or our integration tests which is highly recommended. It's easy to find those `*IT.java` files using testng dependency in POM:
https://github.com/apache/maven-surefire/tree/master/surefire-integration-tests/src/test/resources
If there is anything which needs better documentation please let me know.

```
<configuration>                    
    <parallel>tests</parallel>
    <threadCount>3</threadCount>
</configuration>
```

```
<property>
    <name>parallel</name>
    <value>classes</value>
</property>
<property>
    <name>threadCount</name>
    <value>3</value>
</property>
```

**Comment by aTan-aka-Xellos** [comment] 2016-02-27 00:38
@Tibor17 

> They are applicable if and only if you do not use <suiteXmlFiles/> in Surefire/Failsafe plugin.

Is it for sure? Because it seems illogically, for example:

I have suite.xml with few another suites.
And via maven+surefire using propertie 'suitethreadpoolsize' I can run this suites in parallel.
And 'parallel' seems should work the same.

Our case is:
We run our tests on CI.
We have a lot of suites in xml.
We need run them sometimes in parallel, sometimes not parallel, sometimes different number of threads.

So we can't set parallel via annotation for 100-300 tests and change it each time :)
Also it's strange to use for it parameters in suites xml - then if we have 20 suites - we need update them and commit each time when we want run them in parallel or not.

From the other hand - if 'parallel' will work the same as 'suitethreadpoolsize' - we could set number of threads or tyle of parallel (tests/methods/classes) on the fly by changing 1 parameter on CI.

Is this example clear? 

I'll check your integration tests in few days. Thanks for link.

**Comment by Tibor17** [comment] 2016-02-27 00:52
@aTan-aka-Xellos 
Try to use those version of TestNG as we did 6.9.4, 6.9.6, 6.9.8, etc.
From our PoV `suitethreadpoolsize` is different from `parallel`.
Now what is your problem?

**Comment by aTan-aka-Xellos** [comment] 2016-04-05 13:59
@Tibor17 
I've tried investigate how TestNG works inside and what I've found according this issue:

Parameters configured from pom.xml (parallel/threadCount) are extracted correctly. 
But they are not written into XmlSuite (or XmlTest) or they are overwritten by 'NONE' parameters which are parsed from suite xml file.

I've putted few console outputs inside TestNG and what I've received (set parameter parallel = tests in pom.xml):

This is command line parameters (extracted from pom.xml)
> commandLine: tests
> XmlSuite getValidParallel: tests
> TestNG setParallel:tests
> XmlSuite skipDeprecatedValues: tests

Then parameters from suite xml are parsed:

> initializeSuitesAndJarFile
> xmlSuite attribute: none
> XmlSuite getValidParallel: none
> XmlSuite setParallel:none
> XmlSuite skipDeprecatedValues: none

Please note, that it's okay since I DIDN'T ADD parallel parameter inside suite xml, but only into pom.xml. 

So again, the root-cause of issue that command line parameters received from pom.xml (surefire configuration) doesn't saved or overwritten later!

**Comment by aTan-aka-Xellos** [comment] 2016-04-06 12:43
Find out work-around:

All your tests should have parent (some BaseTest) and this bethod should contains method:

```
    @BeforeSuite
    public void beforeSuite(ITestContext context) {
        context.getCurrentXmlTest().getSuite().setParallel(XmlSuite.ParallelMode.TESTS);
        context.getCurrentXmlTest().getSuite().setThreadCount(3);
    }
```

It's a draft version. 
May be it won't be applicable for all projects since it require parent class, but for our project it works fine since we already have parent BaseTest. We will provide this parameters (threadCount/parallel from config.properties)

But bug in TestNG is still exist :(

**Comment by t-node** [comment] 2017-10-10 20:52
Any update on this issue?

**Comment by juherr** [comment] 2017-10-10 21:19
Ping @krmahadevan

**Comment by krmahadevan** [comment] 2017-10-11 03:53
I revisited this issue using TestNG 6.12 and surefire plugin version 2.20.1.

Below are my findings.

If the surefire plugin section contains 

```xml
<suiteXmlFiles>
    <suiteXmlFile>${suitexml}</suiteXmlFile>
</suiteXmlFiles>
``` 

then both parallelism and thread count are determined *ONLY* from the user provided TestNG suite xml file.
However, if the user would like to work with a suite xml file and still be able to alter attributes of the suite xml file such as thread count (or) parallelism mode etc., then one would need to build an implementation of `org.testng.IAlterSuiteListener` and change them from within this listener.
For more information on how to use this listener, please refer to my blog post [here](https://rationaleemotions.wordpress.com/2017/09/29/building-dynamic-testng-suites/)

If the surefire plugin section does not refer to a suite xml file, then parallelism and thread count can be controlled as below :
```xml
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.20.1</version>
    <configuration>
        <!-- try to set methods in parallel-->
        <parallel>methods</parallel>
        <threadCount>3</threadCount>
    </configuration>
</plugin>
``` 

So I guess TestNG is working properly here and there doesn't seem to be any issue here. Based on @Tibor17 explanation, it looks like surefire plugin is also working as intended.

And since TestNG does provide a proper listener for altering some of the runtime attributes via `IAlterSuiteListener` I am closing off this issue.

Here's the output of the modified project that I ran.
I have attached it [here](https://github.com/cbeust/testng/files/1374135/TestMultithreading.zip) as well for reference.

```
mvn clean test
    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running TestSuite
    Running temp.Test_1.test1() on Thread [13]
    Running temp.Test_3.test3() on Thread [15]
    Running temp.Test_2.test2() on Thread [14]
    Start test_3
    Parallelism Set at suite level is methods
    Start test_2
    Parallelism Set at test level is methods
    Threadcount Set at test level is 3
    Parallelism Set at suite level is methods
    Threadcount Set at suite level is 3
    Start test_1
    Finish test_3
    Finish test_1
    Finish test_2
    [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.255 s - in TestSuite
```
                    
```        
mvn clean test -Puses-suite

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
Running temp.Test_1.test1() on Thread [1]
Parallelism Set at suite level is none
Parallelism Set at test level is none
Threadcount Set at test level is 5
Parallelism Set at suite level is none
Threadcount Set at suite level is 5
Start test_1
Finish test_1
Running temp.Test_2.test2() on Thread [1]
Start test_2
Finish test_2
Running temp.Test_3.test3() on Thread [1]
Start test_3
Finish test_3
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.332 s - in TestSuite
```

@t-node - Please refer to my blog that I shared to learn how to get this work for you.

**Comment by juherr** [comment] 2017-10-11 06:08
@krmahadevan 

This part is strange for me:

> Parameters configured from pom.xml (parallel/threadCount) are extracted correctly.
But they are not written into XmlSuite (or XmlTest) or they are overwritten by 'NONE' parameters which are parsed from suite xml file.

Did you check if it is working, without a listener, with the command line? Or with this method (which is used by surefire)?
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L1648

**Comment by krmahadevan** [comment] 2017-10-11 07:59
@juherr - My bad for jumping the gun there ! I have identified the problem. Will send in a PR soon.

**Closed** 2017-10-12 20:14 UTC
Labels: Feature: parallel, Runner: maven
