### ISSUE TITLE
Exception in @BeforeMethod / @BeforeClass skips more tests than expected.

### ISSUE THREAD

**Issue by friedeks** [cbeust/testng#295] opened 2012-10-22 07:33 UTC
If tests inherit from a common AbstractTest class. A failure during init in one of the testclasses skips not only all methods in the failed test class, but all testclasses inheriting forom the same superclass.

The error occurs only with the super class having a @BeforeMethod calling its child.

Expected behavior: All methods of the test class with the failing init should be skipped, but all other test classes shold be executed.

Code to reproduce the bug: Just run group "initbug". All Methods in both classes will be skipped, even with only one class failing:

``` java
//******************************************************************************
package de.gek.test;                       

import org.testng.annotations.BeforeMethod;

public class AbstractTest {                
  static boolean first = false;            

  @BeforeMethod(alwaysRun = true)          
  public void init(){                      
    abstractInit();                        
  }                                        

  protected void abstractInit() {          
  }                                                                                   
}                                          


//******************************************************************************
package de.gek.test;                           
import org.testng.annotations.Test;            

public class BeforeTest1 extends AbstractTest {

  @Override                                    
  protected void abstractInit() {              
    if(!first){                                
      first = true;                            
      throw new RuntimeException("Init Bug1.");
    }                                          
  }                                            

  @Test(groups = "initbug")                    
  public void testSomething(){                 
    return;                                    
  }                                            

  @Test(groups = "initbug")                    
  public void testMore(){                      
    return;                                    
  }                                            
}       


//******************************************************************************
package de.gek.test;                                                                  

import org.testng.annotations.Test;            

public class BeforeTest2 extends AbstractTest {

  @Override                                    
  protected void abstractInit() {              
    if(!first){                                
      first = true;                            
      throw new RuntimeException("Init Bug2.");
    }                                          
  }                                            

  @Test(groups = "initbug")                    
  public void testIt(){                        
    return;                                    
  }                                            
}
```

**Comment by juherr** [comment] 2017-02-20 10:17
Duplicate of #286

**Closed by juherr** 2017-02-20 10:17 UTC
