### ISSUE TITLE
IClassListener#onAfterClass run more than once per class

### ISSUE THREAD

**Issue by tjni** [cbeust/testng#1618] opened 2017-11-21 02:02 UTC
### TestNG Version
6.11 and built locally from the repository.

### Expected behavior
The `IClassListener#onAfterClass` hooks is run at most once for each test class.

### Actual behavior
The `IClassListener#onAfterClass` hooks can be run multiple times for one test class.

### Reproduction steps

It so happens that Gradle 4.3 introduces an `onAfterClass` hook that throws an NPE when run more than once for a test class. To see this in action, please clone https://github.com/tjni/gradle-testng-npe and run `./gradlew test`.

### Analysis

What is happening is that when `TestRunner` is computing `m_allTestMethods`, it includes test methods that are disabled by its containing class's annotation. This happens because it ignores the `m_enabled` status of the `ITestNGMethod` but tries to prune disabled methods by only looking for an annotation on the method.

When the `TestMethodWorker` later processes these disabled methods, `invokeAfterClassMethods` will call `ClassMethodMap#removeAndCheckIfLast` to decide whether to call the `onAfterClass` hook. The `removeAndCheckIfLast` method will always return true if no methods remaining on the class are enabled, which is the case in the example.

**Comment by krmahadevan** [comment] 2019-03-24 02:49
Since this has been fixed in gradle by @tjni  as part of the PR https://github.com/gradle/gradle/issues/3545 I am closing this issue

**Closed by krmahadevan** 2019-03-24 02:49 UTC
Labels: Feature: listener

**Comment by krmahadevan** [comment] 2019-03-24 02:57
@juherr - Please let me know if you feel that we still should address the root of the problem by filtering out disabled test methods itself when TestNG initializes. 

Class : org.testng.internal.TestNGMethodFinder

Change 

```java
  @Override
  public ITestNGMethod[] getTestMethods(Class<?> clazz, XmlTest xmlTest) {
    ITestNGMethod[] methods = AnnotationHelper.findMethodsWithAnnotation(
        clazz, ITestAnnotation.class, annotationFinder, xmlTest);
    return methods;
  }
```

To 

```java
  @Override
  public ITestNGMethod[] getTestMethods(Class<?> clazz, XmlTest xmlTest) {
    ITestNGMethod[] methods = AnnotationHelper.findMethodsWithAnnotation(
        clazz, ITestAnnotation.class, annotationFinder, xmlTest);
   return Arrays.stream(methods).filter(ITestNGMethod::getEnabled).toArray(ITestNGMethod[]::new);
  }
```

Impact : 

Two tests in TestNG would need to be altered, because now the count of methods would vary (disabled tests would be ignored by TestNG when it queries a class. What this would mean is that, incase someone wants to generate a report which also includes all methods that have been disabled (perhaps when running in the `dryRun` mode, will be impacted)

I haven't been able to figure out how to reproduce this issue without the problematic version of gradle being involved.

**Comment by juherr** [comment] 2019-03-24 07:47
I'm not feeling it good because `TestNGMethodFinder` has the responsibility of finding methods, not filtering them.
If needed, the filtering should be done by the caller.

But we can add a new method:
`public List<ITestNGMethod> getTestMethods(Class<?> clazz, XmlTest xmlTest, Predicate<? super ITestNGMethod > predicate)`
It could be a step forward to replace arrays by collections.
