### ISSUE TITLE
TestNg 6.9.5 do not behave as 6.8.x do. 

### ISSUE THREAD

**Issue by martinaldrin** [cbeust/testng#802] opened 2015-09-18 09:07 UTC
When we did a uplift of TestNg the we saw a that expectedException behaves differently.
@Test(expectedExceptions = SkipException.class)

**Comment by juherr** [comment] 2015-09-18 13:52
Duplicate of #773 and fixed with #774.
It will be available in the next TestNG release.

**Closed by juherr** 2015-09-18 13:52 UTC
