### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by wengm** [cbeust/testng#1070] opened 2016-06-17 06:54 UTC
Version:6.9.12-SNAPSHOT

Compiling error in eclipse:
Description	Resource	Path	Location	Type
The method addInstance(Class<? extends T>, T) in the type TestNGClassFinder is not applicable for the arguments (Class<capture#22-of ?>, capture#23-of ?)	TestNGClassFinder.java	/testng/src/main/java/org/testng/internal	line 255	Java Problem

**Comment by juherr** [comment] 2016-06-17 08:21
Or maybe a javac issue which means we have to fix it. Not really clear for me.
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/TestNGClassFinder.java#L262

Potential related links: 
http://stackoverflow.com/questions/23006777/eclipse-fails-to-compile-generic-code-but-mvn-compile-works
https://bugs.eclipse.org/bugs/show_bug.cgi?id=432603
https://bugs.openjdk.java.net/browse/JDK-8039214

**Comment by juherr** [comment] 2016-06-17 08:32
@wengm Could tell me if the following is working for you:

```java
  private void addInstance(Object o) { // migrate from T to Object
    addInstance(o.getClass(), o);
  }

  private <S, T extends S> void addInstance(Class<T> clazz, S o) { // introduce S
    ...
```

**Comment by juherr** [comment] 2016-06-21 15:30
@wengm I don't reproduce the issue with Mars.2 Release (4.5.2). Which eclipse version do you use?

**Comment by missedone** [comment] 2016-06-21 22:01
I can see it on Eclipse [Neon RC3](https://www.eclipse.org/downloads/index-developer.php)

**Comment by wengm** [comment] 2016-06-22 00:17
@juherr mine is also 4.5.2 but your fix works.

**Comment by wengm** [comment] 2016-06-22 00:40
It should be a javac bug.

**Comment by wengm** [comment] 2016-06-22 00:47
@juherr You fix has bellow compiling error:

Description	Resource	Path	Location	Type
Bound mismatch: The generic method addInstance(Class<T>, S) of type TestNGClassFinder is not applicable for the arguments (Class<capture#22-of ?>, capture#23-of ?). The inferred type capture#22-of ? is not a valid substitute for the bounded parameter <T extends S>	TestNGClassFinder.java	/testng/src/main/java/org/testng/internal	line 255	Java Problem

**Comment by wengm** [comment] 2016-06-22 00:50
Here is the quick fix by eclipse:

`diff --git a/src/main/java/org/testng/internal/TestNGClassFinder.java b/src/main/java/org/testng/internal/TestNGClassFinder.java
index 631b295..92ff2c3 100644
--- a/src/main/java/org/testng/internal/TestNGClassFinder.java
+++ b/src/main/java/org/testng/internal/TestNGClassFinder.java
@@ -1,5 +1,7 @@
 package org.testng.internal;
 
+import static org.testng.internal.ClassHelper.getAvailableMethods;
+
 import java.lang.reflect.Constructor;
 import java.lang.reflect.Method;
 import java.lang.reflect.Modifier;
@@ -20,8 +22,6 @@ import org.testng.internal.annotations.IAnnotationFinder;
 import org.testng.xml.XmlClass;
 import org.testng.xml.XmlTest;
 
-import static org.testng.internal.ClassHelper.getAvailableMethods;
-
 /**
  * This class creates an ITestClass from a test class.
  *
@@ -259,15 +259,15 @@ public class TestNGClassFinder extends BaseClassFinder {
     addInstance(o.getClass(), o);
   }
 
-  private <T> void addInstance(Class<? extends T> clazz, T o) {
-    List<Object> list= m_instanceMap.get(clazz);
+    private <T> void addInstance(Class<?> class1, Object object) {
+        List<Object> list = m_instanceMap.get(class1);
 
     if(null == list) {
       list= Lists.newArrayList();
-      m_instanceMap.put(clazz, list);
+            m_instanceMap.put(class1, list);
     }
 
-    list.add(o);
+        list.add(object);
   }
 
   public static void ppp(String s) {
`

**Comment by wengm** [comment] 2016-06-22 00:50
Eclipse quick fix is like this:
`private <T> void addInstance(Class<?> class1, Object object) {`

**Comment by juherr** [comment] 2016-06-22 08:48
@wengm @missedone Could you try with this project? https://github.com/juherr/testng-1070-test-compile

My output is:

```
It works!
test.CompileClass is not a child of test.CompileClass$ChildClass
It works!
It works!
```

I'm using Linux, what is your OS?

**Comment by missedone** [comment] 2016-06-22 09:29
hi @juherr 
I have the same output as yours, I'm on OS X.
I don't think anything wrong with the syntax around the [solo piece of code](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/TestNGClassFinder.java#L266), but that could mess up Eclipse JDT compiler in the context of the whole `TestNGClassFinder` class.

BTW, i think we don't need Generic for methods [1](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/TestNGClassFinder.java#L266) and [2](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/TestNGClassFinder.java#L262)

**Comment by juherr** [comment] 2016-06-22 09:39
Agree for 2.
But in 1, I expect to have a check on the relation of the 2 arguments (but the little project shows it is not working as expected).
The relation is important and if the check is not possible at compile time, then I'll have to do at runtime.

**Comment by missedone** [comment] 2016-06-22 09:51
ya, i see, it's better to check the relation at compile time.

how about this:
```java
// Nick: removed the generic from the parameter 'IInstanceInfo'
  private void addInstance(IInstanceInfo ii) {
    addInstance(ii.getInstanceClass(), ii.getInstance());
  }

// Nick: removed the generic from method signature
  private void addInstance(Object o) {
    addInstance(o.getClass(), o);
  }
```

**Comment by juherr** [comment] 2016-06-22 12:21
> removed the generic from method signature

+1

> removed the generic from the parameter 'IInstanceInfo'

Why? `IInstanceInfo` and `IInstanceInfo<?>` are the same.

BTW, I'm still not able to reproduce the issue... I will try on another computer.

**Comment by missedone** [comment] 2016-06-22 12:34
oh, forgot to say, once removed the generic from the parameter 'IInstanceInfo', the compiling error gone.

**Comment by juherr** [comment] 2016-06-22 12:46
> oh, forgot to say, once removed the generic from the parameter 'IInstanceInfo', the compiling error gone.

:fearful: It doesn't make sense for me.

BTW `<T, S extends T> void addInstance(Class<S> clazz, T o)` is doing what I expect on both eclipse (mine) and intellij

**Comment by juherr** [comment] 2016-06-22 12:48
@missedone And what about: `private <T> void addInstance(IInstanceInfo<T> ii) {`?

**Comment by missedone** [comment] 2016-06-22 13:06
yeah, I know, however it just get the compiling error gone, 
<img width="498" alt="testng_compiling" src="https://cloud.githubusercontent.com/assets/555134/16267562/4cb66498-383f-11e6-934e-924de78bbcb8.png">

that's why I said something messed the Eclipse JDT compiler.

the compiling error still there if `<T, S extends T> void addInstance(Class<S> clazz, T o)`:
<img width="526" alt="testng_compile_err" src="https://cloud.githubusercontent.com/assets/555134/16267570/59ea6f42-383f-11e6-9cce-943d660722dc.png">

**Comment by missedone** [comment] 2016-06-22 13:11
hi @juherr 

> And what about: private <T> void addInstance(IInstanceInfo<T> ii)?

yes, it works 😄 
<img width="495" alt="testng_compiling2" src="https://cloud.githubusercontent.com/assets/555134/16267673/e9d29896-383f-11e6-9ba4-cee82da9274f.png">

**Comment by juherr** [comment] 2016-06-22 13:20
Final proposition before pull request:

```java
  private <T> void addInstance(IInstanceInfo<T> ii)
  private void addInstance(Object o)
  private <T, S extends T> void addInstance(Class<S> clazz, T o)
```

Maybe you should open a ticket for JDT, it could help.

**Comment by missedone** [comment] 2016-06-22 13:31
hi @juherr
your proposed changes work at my side.

> Maybe you should open a ticket for JDT, it could help.
I think so too, but will do more investigation myself before open the ticket :)

**Comment by juherr** [comment] 2016-06-22 13:57
> your proposed changes work at my side.

:+1: 

> will do more investigation myself before open the ticket :)

I think `IInstanceInfo<?>` is failing because `getInstanceClass()` will return something like `Class<capture#XX-of ?>` and `getInstance()` will return `capture#YY-of ?` when we expect `Class<capture#XX-of ?>` and `capture#XX-of ?`.

**Comment by juherr** [comment] 2016-06-22 16:07
Is

```java
List<?> l = ...
foo(l, l);
```

working with 

```java
<T> void foo(List<T> l1, List<T> l2) {}
```

???

**Comment by juherr** [comment] 2016-06-23 12:46
In fact, the issue is not yet finished: @forax helped me to undesrtand that the expected behavior is a bug of java7 compiler. No need to have something so complicated.

@missedone But there is an issue on the eclipse compiler too and I summarized it in https://gist.github.com/juherr/c3f70f4b80c5f98a47aa6cb9b5bb14ef
Feel free to open the issue on the eclipse project.

**Comment by missedone** [comment] 2016-06-23 14:59
created JDT bug here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496660

thanks

**Comment by juherr** [comment] 2016-09-02 17:13
Won't fix by eclipse.

**Closed by juherr** 2016-09-02 17:13 UTC
Labels: 3rd-party-issue, Runner: eclipse
