### ISSUE TITLE
Set name and parallel to test node instead of only suite node in xml programatically

### ISSUE THREAD

**Issue by aleklukashevich** [cbeust/testng#1644] opened 2017-12-15 14:33 UTC
### TestNG Version
6.13.1

### Expected behavior
When adding parameters to suite, such as name and parallel, then they should be added only for suite node in xml

### Actual behavior
Adds name and parallel to test node too

### Is the issue reproductible on runner?

- [x] Maven

### Test case sample
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="120" guice-stage="DEVELOPMENT" name="ng_all" parallel="tests">
  <listeners>
     some listeners...
  </listeners>
  <test thread-count="120" name="1" parallel="tests">
    <classes>
      <class name="com.test1"/>
    </classes>
  </test> <!-- 1 -->
  <test thread-count="120" name="2" parallel="tests">
    <classes>
      <class name="com.test2"/>
    </classes>
  </test> <!-- 2 -->
  <test thread-count="120" name="3" parallel="tests">
    <classes>
      <class name="com.test3"/>
    </classes>
  </test> <!-- 3 -->
  <test thread-count="120" name="4" parallel="tests">
    <classes>
      <class name="com.test4"/>
    </classes>
```

**Comment by krmahadevan** [comment] 2017-12-15 14:41
@aleklukashevich - Can you please share a sample that can be used to reproduce the issue ?

**Comment by aleklukashevich** [comment] 2017-12-15 15:04
```
public class TestListener implements IAlterSuiteListener {
    /**
     * @param suites - The list of {@link XmlSuite}s that are part of the current execution.
     */
    @Override
    public void alter(List<XmlSuite> suites) {
        XmlSuite suite = suites.get(0);
        List<XmlTest> xmlTests = new ArrayList<>();

        IntStream.range(0, 10).forEach(xmlClass -> {
            XmlTest xmlTest2 = new XmlTest(suite);
            xmlTest2.setClasses(Collections.singletonList(new XmlClass()));
            xmlTests.add(xmlTest2);
        });

        xmlTests.forEach(suite::addTest);

        suite.setParallel(XmlSuite.ParallelMode.TESTS);
        suite.setThreadCount(10);
        suite.toXml();
    }
}
```

**Comment by krmahadevan** [comment] 2017-12-21 16:51
@aleklukashevich - TestNG is working as designed AFAIK. By default, if parallel mode is not specified at the `<test>` level, then TestNG defaults to what was specified at the `<suite>` level. In this case, you have specified the parallelism mode to be "tests" at the "<suite>" level and nothing is specified at the `<test>` level. Hence you are seeing the parallel mode to be "tests" at each of the `<test>` as well.

Am gonna have to close this off as Working as designed.

**Closed by krmahadevan** 2017-12-21 16:51 UTC

**Comment by aleklukashevich** [comment] 2017-12-22 13:54
If it works as designed then tell me please why, it doesn't work on 6.9.10v by using the same code ?

**Comment by krmahadevan** [comment] 2017-12-23 13:57
@aleklukashevich 

The reason why I say this is working as designed is because 

1. The behavior of defaulting to the `parallel` attribute provided at the `<suite>` level, when none provided at the `<test>` level has been in TestNG for a very long time I think (To be specific, since commit 4b9824b5e971a03fe42236402046147699375e3f



2. The behavior of standardizing the xml generation logic was introduced as part of #1455 

(2) Just made this behavior explicitly visible to you in the suite xml that gets generated.

But functionally TestNG has always resorted to honoring the `parallel` attribute at the `<suite>` level, if its missing in the `<test>` tag.

I hope that clarifies.
