### ISSUE TITLE
Wrong source folder default in "New TestNG class" wizard

### ISSUE THREAD

**Issue by franco-conte777** [cbeust/testng#129] opened 2011-11-11 16:19 UTC
You have a project called "AAA" with a source folder called "src"
You create a package called "com.foo.bar"
You want to create a new TestNG class in "bar" so you select the "bar" folder and bring up the "New TestNG class" wizard
You will notice that the "Source Folder" by default gets set to "\AAA\src\com\foo" (and "Package:" to "com.foo.bar")
If you go ahead it will create a package called "com.foo.bar" **_inside**_ the "com.foo" package.
I think this is wrong, as it should just create the new TestNG class inside "com.foo.bar", without creating additional folders.

The Eclipse "New Class" wizard in this case (i.e. when you select the 'bar' folder) will default the "Source Folder" to "AAA/src", the "Package:" to "com.foo.bar" and create the new class in "bar"

**Comment by krmahadevan** [comment] 2017-09-17 12:20
ping @missedone . Can you please help take a look if this is still an issue and if not please help close this out ?

**Comment by missedone** [comment] 2017-09-18 06:10
can't reproduce this on recent release 6.12.0.201709050550
<img width="523" alt="screenshot at sep 17 23-09-32" src="https://user-images.githubusercontent.com/555134/30530638-54853988-9bfd-11e7-96bd-07cf740e46c3.png">

**Comment by krmahadevan** [comment] 2017-09-18 06:12
Based on @missedone comment, closing this off.

**Closed by krmahadevan** 2017-09-18 06:12 UTC
Labels: Runner: eclipse
