### ISSUE TITLE
I hope the method with the same name can be executed multiple times

### ISSUE THREAD

**Issue by linavaos** [cbeust/testng#2395] opened 2020-10-16 05:57 UTC
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
I have a requirement to use the < include > method to execute the same method with different parameters. However, the same method is found to be executed only once.how can i do?

xml code
```xml
<suite name="Suite">
    <parameter name="way" value="1"></parameter>
    <test verbose="2" preserve-order="true" name="webAddSalesCostContractActualProductGoodsCase200">
        <classes>
            <class name="com.zhoupu.quality.test.Test">
                <methods>
                    <include name="fun">
                        <parameter name="case" value="{case json1}"></parameter>
                    </include>
                    <include name="fun">
                        <parameter name="case" value="{case json2}"></parameter>
                    </include>
                </methods>
            </class>
        </classes>
    </test>
</suite>
```

### Actual behavior
fun method can be  executed  twice

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [*] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by kobebryant2007** [comment] 2020-10-20 07:14
Could you please provide a simple code for how to reproduce this issue.

**Comment by krmahadevan** [comment] 2020-10-27 16:58
@linavaos - This is currently not possible in the way in which you are doing.

The reason being TestNG retrieves the methods from a class using reflection (and so there's no way that the same method is going to be retrieved multiple times because Java mandates that a method has to be unique in a class) and then runs the retrieved methods as a comparison against the ones that you specified via the `<include>` tag to check which one to execute and which one to skip. I think you should just use a data driven approach for this.

**Comment by krmahadevan** [comment] 2020-10-27 16:59
Closing this off with resolution as *Question Answered*

**Closed by krmahadevan** 2020-10-27 16:59 UTC
