### ISSUE TITLE
6.12 not released to maven for use as a dependency

### ISSUE THREAD

**Issue by jatheisenii** [cbeust/testng#1564] opened 2017-10-02 17:28 UTC
### TestNG Version
6.12

### Expected behavior
Available at https://mvnrepository.com/artifact/org.testng/testng

### Actual behavior
6.11 is the last release

### Is the issue reproductible on runner?

- [ ] Shell
- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I can update in eclipse to 6.12 testng but I cannot use it as a dependency in maven

**Comment by juherr** [comment] 2017-10-03 08:13
Duplicate of #1506

**Closed by juherr** 2017-10-03 08:13 UTC
