### ISSUE TITLE
since 6.9.10 is not allowed complex parameters in test method(JMockit Injectable/Mocked)

### ISSUE THREAD

**Issue by avaysberg** [cbeust/testng#1501] opened 2017-08-07 10:38 UTC
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
until version 6.9.10 was it allow use the different Objects like parameter.
```
@Test
    public void testCreateDAOFacotry(@Injectable DAOFactory daoFactory) throws Exception {
        Assert.assertNotNull(DAOFactory.createDAOFacotry(daoFactory.getClass(), new Class<?>[] {}, new Object[] {}));
    }
```

### Actual behavior
Now with version 6.9.11 and high i receive exception:
```
org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testCreateDAOFacotry([Parameter{index=0, type=com.unitedinternet.portal.mobile.cocos.persistence.dao.DAOFactory, declaredAnnotations=[@mockit.Mocked(stubOutClassInitialization=false)]}])
Arguments: [(java.lang.String)]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1228)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1125)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) 
```

### Is the issue reproductible on runner?
- [x] Maven
- [x] Eclipse

**Comment by juherr** [comment] 2017-08-07 20:14
Duplicate of #1164

**Closed by juherr** 2017-08-07 20:14 UTC
