### ISSUE TITLE
testng executes the @BeforeClass and every @Test at a different thread

### ISSUE THREAD

**Issue by yardening2** [cbeust/testng#1335] opened 2017-02-15 09:09 UTC
### TestNG Version
6.10

### Expected behavior
The whole `<test>name</test>` should run on one thread

### Actual behavior
each @Test inside the class is executed on a different thread

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
A reopen of issue #1333 
The issue has nothing to do with dependsOn, it happens with the example test I've attached to issue #1333 And there is no dependsOn there

**Comment by juherr** [comment] 2017-02-15 12:46
Duplicate of #1333

**Closed by juherr** 2017-02-15 12:46 UTC
