### ISSUE TITLE
Depends On Methods is not fully enforced when running Parallel Instances

### ISSUE THREAD

**Issue by BrandonDudek** [cbeust/testng#2054] opened 2019-04-09 14:39 UTC
### TestNG Version
> 7.0.0-beta5 and 6.14.3

### Expected behavior
Test methods are executed in order.
If Method3 depends on Method2 and Method2 has a DataProvider, all of Method2's calls should finish, before Method3 is called. (For a given instance.)

### Actual behavior
Method3 is called before all of Method2's calls have completed. (For a given instance.)

### Is the issue reproducible on runner?
Yes.
- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> I wrote a sample project to showcase this bug: [testng-parallel-instance-depends-on-methods-bug;](https://github.com/BrandonDudek/testng-parallel-instance-depends-on-methods-bug). If you run either of the TestNG XML Test Suites, you can see the for instance "B" `testMethod3` starts executing before all of the `testMethod2`s, for instance "B" have finished.

**Comment by krmahadevan** [comment] 2020-01-04 10:34
@BrandonDudek 

I have tried reproducing this in TestNG `7.1.0` and I am not able to reproduce this problem.

Here's the sample that I have used for this (I had to tweak the sample a bit for this)

The reason why I had tweak the sample is because it relies on `System.out.println` and that makes it hard to guess what is going on. The sample that I added has assertions which ensures that every later method has its start time as later than the upstream method.

Please comment if you notice something that's missing in this sample which needs to be added to reproduce the problem. Closing this as **Not reproducible**

**Sample test class**

```java
import java.util.Iterator;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class TestClassSample {

  private static final int ITERATIONS = 3;
  private static final int COUNT = 3;

  @DataProvider(parallel = true)
  public static Iterator<Object[]> factoryDataProvider() {

    return IntStream.range('A', 'A' + COUNT)
        .mapToObj(i -> new Object[]{Character.toString((char) i)})
        .collect(Collectors.toList()).iterator();
  }

  private final String INSTANCE_NAME;

  @Factory(dataProvider = "factoryDataProvider")
  public TestClassSample(String _instanceName) {
    INSTANCE_NAME = _instanceName;
  }

  @Test
  public void testMethod1() throws InterruptedException {
    for (int i = 0; i < ITERATIONS; i++) {
      TimeUnit.SECONDS.sleep(1);
    }
    Logs.getInstance().add(this.toString(), "testMethod1");
  }

  @Test(dependsOnMethods = "testMethod1")
  public void testMethod2() throws InterruptedException {
    int count = (INSTANCE_NAME.equalsIgnoreCase("B") ? 6 : ITERATIONS);

    for (int i = 0; i < count; i++) {
      TimeUnit.SECONDS.sleep(1);
    }
    Logs.getInstance().add(this.toString(), "testMethod2");
  }

  @Test(dependsOnMethods = "testMethod2")
  public void testMethod3() throws InterruptedException {
    for (int i = 0; i < ITERATIONS; i++) {
      TimeUnit.SECONDS.sleep(1);
    }
    Logs.getInstance().add(this.toString(), "testMethod3");
  }

  @Override
  public String toString() {
    return INSTANCE_NAME;
  }
}
```

**The logger**

```java
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Random;
import java.util.concurrent.TimeUnit;

public class Logs {

  private static final Logs instance = new Logs();

  public static Logs getInstance() {
    return instance;
  }

  private final Map<String, Map<Long, String>> data = new LinkedHashMap<>();
  private final Random random = new Random();

  public synchronized void add(String instance, String method) {
    Map<Long, String> map = data.computeIfAbsent(instance, instanceName -> new LinkedHashMap<>());
    try {
      TimeUnit.MILLISECONDS.sleep(random.nextInt(10));
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
    map.put(System.currentTimeMillis(), method);
  }

  public Map<String, Map<Long, String>> getLogs() {
    return data;
  }
}
```

**The test runner**

```java
import java.util.Collections;
import java.util.Map;
import org.testng.Assert;
import org.testng.TestNG;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlSuite.ParallelMode;
import org.testng.xml.XmlTest;

public class IssueTest {

  @Test(dataProvider = "dp")
  public void runTest(ParallelMode mode) {
    XmlSuite suite = newSuite(mode);
    TestNG testng = new TestNG();
    testng.setGroupByInstances(true);
    testng.setParallel(ParallelMode.NONE);
    testng.setXmlSuites(Collections.singletonList(suite));
    testng.setVerbose(2);
    System.err.println(suite.toXml());
    testng.run();
    System.err.println("Printing logs");
    Logs.getInstance().getLogs().forEach((k, v) -> {
      System.err.println("Instance : " + k);
      long previous = 0;
      for (Map.Entry<Long, String> each : v.entrySet()) {
        Long time = each.getKey();
        String method = each.getValue();
        System.err.println(method + "() :" + time);
        Assert.assertTrue(previous < time);
        previous = time;
      }
    });
  }

  private static XmlSuite newSuite(ParallelMode mode) {
    XmlSuite xmlSuite = new XmlSuite();
    xmlSuite.setParallel(mode);
    xmlSuite.setGroupByInstances(true);
    xmlSuite.setName("xml_suite");
    XmlTest xmlTest = new XmlTest(xmlSuite);
    xmlTest.setName("xml_test");
    XmlClass xmlClass = new XmlClass(TestClassSample.class.getName());
    xmlTest.setXmlClasses(Collections.singletonList(xmlClass));
    return xmlSuite;
  }

  @DataProvider(name = "dp")
  public Object[][] getData() {
    return new Object[][]{
        {ParallelMode.FALSE},
        {ParallelMode.INSTANCES}
    };
  }
}
```

**The output**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="xml_suite" group-by-instances="true">
  <test thread-count="5" name="xml_test" group-by-instances="true">
    <classes>
      <class name="xyz.swatt.testng.TestClassSample"/>
    </classes>
  </test> <!-- xml_test -->
</suite> <!-- xml_suite -->

PASSED: testMethod1 on A
PASSED: testMethod2 on A
PASSED: testMethod3 on A
PASSED: testMethod1 on B
PASSED: testMethod2 on B
PASSED: testMethod3 on B
PASSED: testMethod1 on C
PASSED: testMethod2 on C
PASSED: testMethod3 on C

===============================================
    xml_test
    Tests run: 9, Failures: 0, Skips: 0
===============================================


===============================================
xml_suite
Total tests run: 9, Passes: 9, Failures: 0, Skips: 0
===============================================

Printing logs
Instance : A
testMethod1() :1578133793544
testMethod2() :1578133796568
testMethod3() :1578133799581
Instance : B
testMethod1() :1578133802599
testMethod2() :1578133808631
testMethod3() :1578133811641
Instance : C
testMethod1() :1578133814658
testMethod2() :1578133817677
testMethod3() :1578133820690
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="xml_suite" parallel="instances" group-by-instances="true">
  <test thread-count="5" name="xml_test" parallel="instances" group-by-instances="true">
    <classes>
      <class name="xyz.swatt.testng.TestClassSample"/>
    </classes>
  </test> <!-- xml_test -->
</suite> <!-- xml_suite -->



PASSED: testMethod1 on B
PASSED: testMethod1 on C
PASSED: testMethod1 on A
PASSED: testMethod2 on A
PASSED: testMethod2 on C
PASSED: testMethod2 on B
PASSED: testMethod3 on A
PASSED: testMethod3 on B
PASSED: testMethod3 on C

===============================================
    xml_test
    Tests run: 9, Failures: 0, Skips: 0
===============================================


===============================================
xml_suite
Total tests run: 9, Passes: 9, Failures: 0, Skips: 0
===============================================

Printing logs
Instance : A
testMethod1() :1578133793544
testMethod2() :1578133796568
testMethod3() :1578133799581
testMethod1() :1578133823839
testMethod2() :1578133826853
testMethod3() :1578133829871
Instance : B
testMethod1() :1578133802599
testMethod2() :1578133808631
testMethod3() :1578133811641
testMethod1() :1578133823836
testMethod2() :1578133829869
testMethod3() :1578133829879
Instance : C
testMethod1() :1578133814658
testMethod2() :1578133817677
testMethod3() :1578133820690
testMethod1() :1578133823838
testMethod2() :1578133826865
testMethod3() :1578133829888


===============================================
Default Suite
Total tests run: 2, Passes: 2, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

**Closed by krmahadevan** 2020-01-04 10:34 UTC
Labels: Feature: dependsOn, Feature: parallel
