### ISSUE TITLE
Test passes under Maven test but fails under Maven verify when using RetryAnalizer

### ISSUE THREAD

**Issue by javydreamercsw** [cbeust/testng#2416] opened 2020-11-13 17:24 UTC
### TestNG Version
7.3.0

### Expected behavior
Tests to behave the same regardless of the Maven test method used.

### Actual behavior
The test fails under verify Maven command.

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class RetryAnalyzerNGTest {
  private int count = 0;

  /** Test of retry method, of class RetryAnalyzer. */
  @Test
  public void testRetry() {
    assertEquals(count++, TEST_RETRIES);
    count = 0;
  }

  @DataProvider
  public Object[][] testData() {
    return new Object[][] {{1}, {2}, {3}};
  }

  @Test(dataProvider = "testData")
  public void testDataProviderRetry(int value) {
    assertEquals(count++, TEST_RETRIES);
    count = 0;
  }
}
```
**Note:** TEST_RETRIES is a constant set by parameters.

Retry Analyzer:

```
import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;

public class RetryAnalyzer 
    implements IRetryAnalyzer{
  private int counter = 0;

  /** {@inheritDoc} */
  @Override
  public boolean retry(@NonNull ITestResult result) {
    if (counter < TEST_RETRIES) {
      info("Retrying test " + result.getName() + "(" + counter++ + ")");
      return true;
    }
    // Reset for data provider retries to work properly.
    counter = 0;
    return false;
  }
}
```
Transformer:
```
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.testng.IAnnotationTransformer;
import org.testng.IRetryAnalyzer;
import org.testng.annotations.ITestAnnotation;

public class RetryAnalyzerTransformer implements IAnnotationTransformer {
  private static final Log LOG = LogFactory.getLog(RetryAnalyzerTransformer.class);

  /** {@inheritDoc} */
  @Override
  public void transform(
      ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
    try {
      IRetryAnalyzer analyzer =
          annotation.getRetryAnalyzerClass().getDeclaredConstructor().newInstance();

      if (analyzer == null || !(analyzer instanceof RetryAnalyzer)) {
        annotation.setRetryAnalyzer(RetryAnalyzer.class);
      }
    } catch (InstantiationException
        | IllegalAccessException
        | IllegalArgumentException
        | InvocationTargetException
        | NoSuchMethodException
        | SecurityException ex) {
      LOG.error(ex.getLocalizedMessage(), ex);
    }
  }
}
```

Injected via pom:
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${dependency.surefire.version}</version>
        <configuration>
          <properties>
            <property>
              <name>listener</name>
              <value>path.to.class.RetryAnalyzerTransformer</value>
            </property>
          </properties>
        </configuration>
      </plugin>
```

Verify command: `mvn -DTEST_RETRIES=3 test:compile verify`
Test command: `mvn -DTEST_RETRIES=3 test:compile test`

Not sure what other information I can provide, so let me know.

**Comment by krmahadevan** [comment] 2020-11-29 17:09
Duplicate of https://github.com/cbeust/testng/issues/2417

**Closed by krmahadevan** 2020-11-29 17:09 UTC
