### ISSUE TITLE
Issue with getting pass percentage

### ISSUE THREAD

**Issue by arunaousula9421** [cbeust/testng#2247] opened 2020-02-17 14:01 UTC
### TestNG Version
> Version: 6.9.10

Hi Guys,

I am trying to get pass percentage of all the passed test methods using below code:

`iTestResult.getMethod().getSuccessPercentage()`

or

`iTestContext.getAllTestMethods()[0].getSuccessPercentage()`

But in both the cases even if the test fails it returns 100%.

Can I please know if there is anyway I can get the pass percentage of only passed tests.

**Comment by krmahadevan** [comment] 2020-02-18 03:32
@arunaousula9421 - The latest released version of TestNG is `7.1.0`. Please try again using that. If the problem persists, please attach a sample standalone that can be used to reproduce the problem.

If there are no updates on this issue, we will have to close the issue.

**Comment by arunaousula9421** [comment] 2020-02-18 11:38
Sure @krmahadevan . Will try the latest version and see if that works.

**Comment by arunaousula9421** [comment] 2020-02-18 12:03
@krmahadevan As you said I have updated testng version to `7.1.0`. But I still see the issue in the getting the pass percentage.

`1582026737617000000 100  com.rxp.hpp.selenium.tests.hpp.qa.dcc.V2DccRedSysST         FAIL`
Though the test is marked as failed we still see the percentage as 100 instead of 0.

Here's the sample code, I have used
`.addField("Passpercentage", iTestResult.getMethod().getSuccessPercentage())`

or

`.addField("Passpercentage", (iTestContext.getAllTestMethods()[0].getSuccessPercentage()))`

**Comment by krmahadevan** [comment] 2020-02-19 03:52
@arunaousula9421 - I took a closer look at this issue.
This is NOT a problem with TestNG but it looks like you are trying to read up the value via the wrong means.

`org.testng.ITestNGMethod#getSuccessPercentage` returns the pass percentage that was set via the `@Test` annotation's `successPercentage` attribute.

Its not meant to getting the pass percentage as what you are expecting.

Now coming back to pass percentage evaluation that you are trying to do. Its not clear what you mean by pass percentage of "passed tests".

Either ways I would suggest that you please create a full fledged example and add more details in terms of what you are trying to do and post it as a question on the `testng-users` google forums.

Closing this issue with resolution as *Working as designed*

**Closed by krmahadevan** 2020-02-19 03:52 UTC
