### ISSUE TITLE
Error in test case method which has a parameter.

### ISSUE THREAD

**Issue by noviceamateur** [cbeust/testng#1762] opened 2018-04-20 05:48 UTC
### TestNG Version
> Note: only the latest version is supported

I have a TestNG test case - 

```java
   @Test(enabled = false)
   public void testSignPutUrlWithTimeExpired() throws Exception {
       testSignPutUrlWithTime(-getSignedUrlTimeout());
   }

   public void testSignPutUrlWithTime(final long timeout)  {
//Some code
}
```

I am getting an error -
> Cannot inject @Test annotated Method [testSignPutUrlWithTime] with [long].

If it is disabled then why is it giving this error in the first place?

This used to work in version 6.8.21. This error is coming since we switched to the latest 6.14.3 version.

### Is the issue reproductible on runner?

- [ ] Shell
- [Yes ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ Yes] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment] 2018-04-21 04:13
@noviceamateur - I don't quite understand your sample. Your error is suggesting that the method was `testSignPutUrlWithTime` but it doesn't have any annotation on it. Please provide a clear sample that can be used to reproduce this issue.

**Comment by juherr** [comment] 2018-04-21 22:09
I suppose the annotation is on the class, so `testSignPutUrlWithTime` is considered as a test method and it fails because TestNG is not able to understand how to inject the param.

If true, the error message is not explicit enough.

**Comment by krmahadevan** [comment] 2018-04-23 03:59
@juherr 

> If true, the error message is not explicit enough.

Why do you say the error message is not explicit enough? The error states that the test method is expecting a `long` to be injected into it, but its not happening. What do you think should be changed here?

**Comment by juherr** [comment] 2018-04-23 08:12
First, `Cannot inject @Test annotated Method` is wrong here.
Then, we may explain what is the expected fix (define a dataprovider or a parameter).

**Comment by krmahadevan** [comment] 2018-04-23 08:24
@juherr - Nope. That doesn't recreate the error as well.

**Test class**

```java
import org.testng.annotations.Test;

@Test
public class ErrorTest {
  @Test
  public void testSignPutUrlWithTimeExpired() throws Exception {
    testSignPutUrlWithTime(100);
  }

  @Test(enabled = false)
  public void testSignPutUrlWithTime(final long timeout) {
    // Some code
  }
}
```

Same test runner as before.

**Output**

```
===== Invoked methods
    ErrorTest.testSignPutUrlWithTimeExpired()[pri:0, instance:com.rationaleemotions.github.issue1762.ErrorTest@16022d9d] 369241501
=====
PASSED: testSignPutUrlWithTimeExpired

===============================================
    Command line test
    Tests run: 1, Failures: 0, Skips: 0
===============================================


===============================================
Command line suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

===== Invoked methods
    TestRunner.testMethod()[pri:0, instance:com.rationaleemotions.github.issue1762.TestRunner@cb51256] 213193302
=====
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by juherr** [comment] 2018-04-23 10:51
My supposed sample

```java
@Test
public class ErrorTest {

  @Test(enabled = false)
  public void testSignPutUrlWithTimeExpired() throws Exception {
    testSignPutUrlWithTime(100);
  }

  public void testSignPutUrlWithTime(final long timeout) {
    // Some code
  }
}
```

**Comment by krmahadevan** [comment] 2018-04-24 12:44
@juherr - How is the sample that you shared an example of a broken functionality in TestNG ?
The `@Test` is added at the class level. So all methods in the class are basically test methods. Since `enabled=false` is not added on top of `testSignPutUrlWithTime()`. Its being considered as a test method. And since its missing either a data provider or a `@Parameters` annotation and since there's no native injection involved here, the error comes up. Please let me know what I am missing here ?

**Comment by juherr** [comment] 2018-04-24 12:46
It's not a broken functionality and it is working as expected but the error message may be more explicit.

**Comment by krmahadevan** [comment] 2018-04-24 12:49
@juherr - So you are basically saying that we need to improve the error verbiage when Tests fail due to parameter injection missing, when the use case doesn't involve a native injection. Correct ? I am just trying to ensure I understand the scope of the issue, so that the fix can be applied properly.

**Comment by juherr** [comment] 2018-04-24 13:32
Yes, check my first message: https://github.com/cbeust/testng/issues/1762#issuecomment-383491384
But we can just close the issue without any 'fix' too.

**Comment by krmahadevan** [comment] 2018-04-24 17:33
@juherr - I am inclined to closing this as *working as designed*.

**Closed** 2018-04-24 17:36 UTC
Labels: Need: sample, Need: user answer
