### ISSUE TITLE
dependsOnMethod works only for immediate inheritance level. chained inheritance not working.

### ISSUE THREAD

**Issue by mridulj17** [cbeust/testng#2309] opened 2020-05-13 02:10 UTC
### TestNG Version
7.1.0 - observed in 6.xx version as well

### Expected behavior
Running the test on the class level and method level should work fine despite dependsOnMethod chaining.

### Actual behavior
On running the code below at class level (TestNg class in the sample test), the dependsOnMethod hierarchy works correctly and all tests pass.

However, on running only method3 it results in

```
/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=50412:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/testng/lib/testng-rt.jar:/Users/stealth/IdeaProjects/TestNg/target/test-classes:/Users/stealth/IdeaProjects/TestNg/target/classes:/Users/stealth/.m2/repository/org/testng/testng/7.1.0/testng-7.1.0.jar:/Users/stealth/.m2/repository/com/beust/jcommander/1.72/jcommander-1.72.jar:/Users/stealth/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0-no_aop.jar:/Users/stealth/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/stealth/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/stealth/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:/Users/stealth/.m2/repository/org/yaml/snakeyaml/1.21/snakeyaml-1.21.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/testng/lib/jcommander-1.27.jar" com.intellij.rt.testng.RemoteTestNGStarter -usedefaultlisteners false -socket50411 @w@/private/var/folders/pc/kwvbxt0x5zzctyy4g9lmh_cc0000gn/T/idea_working_dirs_testng.tmp -temp /private/var/folders/pc/kwvbxt0x5zzctyy4g9lmh_cc0000gn/T/idea_testng.tmp
org.testng.TestNGException: 
TestNg.method2() is depending on method public void TestNg.method1(), which is not annotated with @Test or not included.
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:133)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:277)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:381)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:71)
	at org.testng.TestRunner.initMethods(TestRunner.java:519)
	at org.testng.TestRunner.init(TestRunner.java:338)
	at org.testng.TestRunner.init(TestRunner.java:291)
	at org.testng.TestRunner.<init>(TestRunner.java:179)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1275)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1251)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1100)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

Process finished with exit code 255
```

### Is the issue reproductible on runner?

- [ ] Shell
- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
import org.testng.annotations.Test;

/**
 * independent execution of method 3 throws error
 * unless all the parent methods are explictly called
 * in the dependsOnMethod
 */
public class TestNg {

    @Test
    public void method1(){
        System.out.println("method 1");
    }

    @Test(dependsOnMethods = {"method1"})
    public void method2(){
        System.out.println("invoking this method works as there is only");
    }

    //does not work on invoking this method
    @Test(dependsOnMethods = {"method2"})
    public void method3_fail(){
        System.out.println("invoking method 3 throws exception");
    }

    @Test(dependsOnMethods = {"method1", "method2"})
    public void method3_fix(){
        System.out.println("invoking this method works as all dependsOnMethods are explictly invoked!");
    }
}
```

**Comment by krmahadevan** [comment] 2020-05-13 03:31
When you select a particular `@Test` method, right click it and run it as a TestNG test within an IDE, the IDE creates a suite file on the fly, adds the test method that you selected into it and attempts at running it. TestNG by design will throw an exception if your suite xml file contains a test method that has upstream dependencies and not included.

Try running the below suite and you will see the same behaviour

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="SampleTestSuite" verbose="2" parallel="false" thread-count="1">
  <test name="dataprovider_test" verbose="2">
    <classes>
      <class name="com.rationaleemotions.github2309.TestNg">
        <methods>
          <include name="method2">
          </include>
        </methods>
      </class>
    </classes>
  </test>
</suite>
```

There's nothing much that can be done. You would need to run the test class fully. If you still feel this is a problem, then I would suggest that you file a bug with the IntelliJ IDE which is what triggers this behaviour.

Closing this issue as **Working as designed**

**Closed by krmahadevan** 2020-05-13 03:31 UTC
