### ISSUE TITLE
Can't find method org.testng.xml.XmlSuite.setParallel(Ljava/lang/String;)V when running Maven 3.6.3/TestNG v7.4.0

### ISSUE THREAD

**Issue by PredatorVI** [cbeust/testng#2496] opened 2021-03-13 01:05 UTC
### TestNG Version
v7.4.0
maven-surefire-plugin v3.0.0-M4
Oracle JDK 1.8.0_221
Maven 3.6.3

### Expected behavior
Tests run.

### Actual behavior
Test won't launch and fail w/ exception:

```
cd C:\Projects\Local\ThreadPoolTest; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_221" M2_HOME=C:\\Tools\\apache-maven-3.6.3 cmd /c "\"C:\\Tools\\apache-maven-3.6.3\\bin\\mvn.cmd\" -Dtest=com.test.ParallelTest -Dmaven.ext.class.path=C:\\Tools\\netbeans-12.2\\java\\maven-nblib\\netbeans-eventspy.jar surefire:test"
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...

----------------------< com.test:ThreadPoolTest >-----------------------
Building ThreadPoolTest 1.0-SNAPSHOT
--------------------------------[ jar ]---------------------------------

--- maven-surefire-plugin:3.0.0-M4:test (default-cli) @ ThreadPoolTest ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.test.ParallelTest
org.testng.xml.XmlSuite.setParallel(Ljava/lang/String;)V

Results:

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  2.719 s
Finished at: 2021-03-12T18:01:15-07:00
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-cli) on project ThreadPoolTest: There are test failures.

Please refer to C:\Projects\Local\ThreadPoolTest\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
There was an error in the forked processorg.testng.xml.XmlSuite.setParallel(Ljava/lang/String;)V
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked processorg.testng.xml.XmlSuite.setParallel(Ljava/lang/String;)V
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:675)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:248)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven 3.6.3
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [X] NetBeans (12.2)

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Run the ParallelTest.java (not really parallel.

[ThreadPoolTest.zip](https://github.com/cbeust/testng/files/6133843/ThreadPoolTest.zip)

**Comment by juherr** [comment] 2021-03-13 12:29
Close as duplicate of #2485

**Closed by juherr** 2021-03-13 12:29 UTC
