### ISSUE TITLE
OutOfMemory exception when running many suites

### ISSUE THREAD

**Issue by sebbes** [cbeust/testng#158] opened 2012-01-17 10:01 UTC
When running testng with a lot of suite files testNG runs out of Memory. The culprit is the org.testng.internal.Configuration, with more than 17 million instances of IConfigurationListener (in this case org.apache.maven.surefire.testng.ConfigurationAwareTestNGReporter) in the List m_configurationListeners. 

We had about 20 suite files, we reduced the number to 12, and now the tests run fine. We use TestNG version 6.3.

Let me know if you need more information.

Regards,
Sebastian

**Comment by krmahadevan** [comment] 2018-06-10 05:49
Closing this issue out since its a very old one, there have been a lot of improvements in the areas of managing TestNG listeners and also since there has been no updates on this issue. Please add a comment if this is still a problem. Also please help share a sample that can be executed to reproduce the problem.

**Closed by krmahadevan** 2018-06-10 05:49 UTC
