### ISSUE TITLE
Configuration Listeners added via ServiceLoader are not being run

### ISSUE THREAD

**Issue by alechenninger** [cbeust/testng#491] opened 2014-02-22 02:04 UTC
I can't tell if this is a problem with SuiteRunner or TestRunner or what exactly, but I can't find where either of them are looking at ConfigurationListeners added via ServiceLoader. I can see that ServiceLoader is indeed finding them, and they are being added to the Configuration. Ultimately at line 1862 of Invoker.java, m_notifier.getConfigurationListeners() is not returning the listener added via ServiceLoader.

If I find time I will try to investigate further and submit a pull request.

**Comment by juherr** [comment] 2015-09-19 20:57
I'm not able to reproduce the issue. Could you have a look on #806 where I added a test and tell me if you see something wrong?

**Comment by krmahadevan** [comment] 2018-06-10 13:04
Closing this off based on the above comment. Please comment if this problem continues to exist.

**Closed by krmahadevan** 2018-06-10 13:04 UTC
Labels: Feature: listener
