### ISSUE TITLE
Suit file running 2 suitFiles reorder bug

### ISSUE THREAD

**Issue by andrey-zap** [cbeust/testng#1876] opened 2018-07-25 12:25 UTC
### TestNG Version
> Note: only the latest version is supported

```xml
<suite name="DummyGlobalMultiSuit" >
    <suite-files >
        <suite-file path="DummyMultiSuit1.xml"/>
        <suite-file path="DummyMultiSuit2.xml"/>
    </suite-files>
</suite>

```

```xml
<suite name="DummyMultiSuit1">
    <suite-files>
        <suite-file path="DummySuit1.xml"/>
        <suite-file path="DummySuit2.xml"/>
        <suite-file path="DummySuit1.xml"/>
        <suite-file path="DummySuit3.xml"/>
        <!--<suite-file path="DummySuit1.xml"/>-->
    </suite-files>
</suite>
```

```xml
<suite name="DummyMultiSuit2">
    <suite-files>
        <suite-file path="DummySuit4.xml"/>
        <suite-file path="DummySuit1.xml"/>
    </suite-files>
</suite>
```

### Expected behavior
expected execution order:
first suite:
**DummySuit1**
DummySuit2
**DummySuit1**
DummySuit3

second suite:
DummySuit4
**DummySuit1**

### Actual behavior
actual execution order:
first suite:
DummySuit2
DummySuit3
**DummySuit1**
**DummySuit1**

second suite:
DummySuit4
**DummySuit1**

this is happening only when DummySuit1 exist in the second SuiteFile
cant understand why...

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment] 2018-07-25 13:20
@andrey-zap - Does this issue occur when you use TestNG `6.14.3` (latest released version as of today) ? If yes, then please attach some sample that can be used to reproduce the issue?

**Comment by andrey-zap** [comment] 2018-07-25 15:42
Hey, Just tested with 
```
<dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
        </dependency>
```

and got same result

**Comment by andrey-zap** [comment] 2018-07-25 15:48
Just run DummyGlobalMultiSuit suite in testNG 
[TestNgBug.zip](https://github.com/cbeust/testng/files/2228553/TestNgBug.zip)

**Comment by andrey-zap** [comment] 2018-07-25 15:50
You can see that the execution order  isnt corresponding to xml order

![image](https://user-images.githubusercontent.com/16387879/43211945-6e539d5e-903b-11e8-8196-4c2e85984c6d.png)

**Comment by andrey-zap** [comment] 2018-08-01 09:15
Hi,
Thanks for the help, i think its exactly the same bug as reported on  #1850 .  What is the official  release version that contain the fix? so i can use it

**Comment by andrey-zap** [comment] 2018-08-01 09:26
Thank you!

**Comment by krmahadevan** [comment] 2018-08-01 09:29
Based on comment from the user, closing as a duplicate of #1850

>

**Closed** 2018-08-01 09:30 UTC
Labels: Need: sample
