### ISSUE TITLE
TestNG suite with parallel DataProvider and random order of methods

### ISSUE THREAD

**Issue by langacker** [cbeust/testng#441] opened 2013-09-10 05:47 UTC
I am not sure if it is a bug, but my question did not find any answer on stackoverflow for quite a long time, so I decided to post it here. Please check the following description below:

http://stackoverflow.com/questions/15265771/testng-suite-with-parallel-dataprovider-and-random-order-of-methods-how-to-ach

**Comment by krmahadevan** [comment] 2020-11-16 15:31
AFAIK currently TestNG has 3 sets of thread pools

1. One threadpool which is controlled by `thread-count` attribute of `<suite|test>` tag.(this is applicable only to regular methods)  _and_
2. Another threadpool which is controlled by `data-provider-thread-count` attribute of `<suite|test>` tag (this is applicable only for data driven tests) _and_
3. Another threadpool which is controlled by `threadPoolSize` attribute of `@Test` annotation (this is applicable only when you have an `invocationCount` of more than 1 for the `@Test` method)

Currently its not possible to blend all of them together such that they all work using the same common threadpool.

There's already an issue https://github.com/cbeust/testng/issues/2019 which talks about merging the thread pool for (1) and (2).

Closing this issue as a duplicate of `2019` (We could have done the other way too, but I don't think it really matters as to which becomes a duplicate of which one, as long as the requirement of the issue gets addressed.

**Closed by krmahadevan** 2020-11-16 15:31 UTC
