### ISSUE TITLE
Vast amount of DynamicGraph.Edge during build

### ISSUE THREAD

**Issue by svettwer** [cbeust/testng#1788] opened 2018-05-16 09:47 UTC
### TestNG Version
6.12 to 6.14.3

### Actual behavior
As we updated from 6.11, we recognized memory issues during our build.
Here is what I found out during my investigation in the two issues we had for this problem:
**Issues**
* https://github.com/christophd/citrus/issues/337
* https://github.com/christophd/citrus/issues/379

With TestNG > 6.11, the memory is filling up with a vast amount of DynamicGraph.Edge objects in [certain situations](https://github.com/christophd/citrus/issues/379#issuecomment-389452511). 
![image](https://user-images.githubusercontent.com/25754312/39824421-93f95670-53af-11e8-8a8c-a65a0d1132f5.png)
Unfortunately there situations are not easy to reproduce nor to debug - at least for me.

### Is the issue reproductible on runner?
https://github.com/christophd/citrus/issues/379#issuecomment-389452511

### Questions
* Do you have an idea why so many DynamicGraph.Edge are created?
* Do you know about an effect in surefire that could cause this? 
  * We're using 2.20.1 but even with 2.21.0 and 2.19.1 the issue occurred.

Thx in advance and BR,
Sven

**Comment by juherr** [comment] 2018-05-23 12:10
It looks like a duplicate of #1710 which will be available in the next release (no planned for the moment).

Could you try the SNAPSHOT version and tell us if the problem is fixed?

**Closed by juherr** 2018-05-23 12:10 UTC
Labels: perf/enhancement

**Comment by svettwer** [comment] 2018-05-24 06:43
Hi @juherr!

Thx for your response. An update to 7.0.0-SNAPSHOT fixed the issue!
