### ISSUE TITLE
Parallel classes doesn't respect threadCount when launched with Maven Surefire

### ISSUE THREAD

**Issue by sergejjkim** [cbeust/testng#991] opened 2016-02-24 11:13 UTC
I have the following pom setup:

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <parallel>classes</parallel>
                    <threadCount>30</threadCount>
                    <perCoreThreadCount>false</perCoreThreadCount>
                    <excludes>
                        <exclude>${exclude.tests}</exclude>
                    </excludes>
                </configuration>
</plugin>
```

And I have about 20 tests classes and two groups: 1st contains 2 classes and 2nd contains all of the classes.
When i run the 1st group, i have 5 threads launched with 4 tests from one class and one from another (which is not the expected behavior, the expected would be 2 threads with tests from 2 classes)
When i run the 2nd group, everything seems to be fine.

I traced Surefire plugin to the moment it calls 

```
 testng.setXmlSuites( xmlSuites );
 configurator.configure( testng, options );
 postConfigure( testng, testSourceDirectory, reportManager, reportsDirectory, skipAfterFailureCount, extractVerboseLevel( options ) );
 testng.run();
```

in both cases it passes a suite with all the classes and parallel == classes and threadCount == 30, so i thought it maybe a TestNG issue

I tried TestNG 6.8.8, 6.9.9, 6.9.10

**Comment by juherr** [comment] 2016-02-24 15:46
Duplicate of #987

**Closed by juherr** 2016-02-24 15:46 UTC
Labels: maven, parallel

**Comment by sergejjkim** [comment] 2016-02-26 13:24
the cause seems to be the groups specified.
running the following suite results in same behavior:
```
<suite name="My suite" parallel="classes" thread-count="30">

    <test name="test1">
        <groups>
            <run>
                <include name="smoke"  />
            </run>
        </groups>

        <classes>
            <class name="com.spredfast.qa.mobileauto.ios.tests.publishing.general.TestPublishMessageIOS"/>
            <class name="com.spredfast.qa.mobileauto.ios.tests.TestLoginIOS"/>
        </classes>
    </test>


</suite>
```

**Comment by sergejjkim** [comment] 2016-02-27 00:56
@juherr could you reopen it? it doesn't look like a duplicate of #987

**Comment by juherr** [comment] 2016-02-27 07:44
@sergejjkim I'm not sure to understand the relation between your 2 snippets.

In the first one, you don't have suite file and no groups.
In the second one, you use a suite file with group.

About your second snippet, is it working as expected when you comment the `<groups>` node?
If yes, I propose you to create a new issue which describes the problem with parallel and groups.
