### ISSUE TITLE
Unable to debug test with a chain of dependencies in IDEA

### ISSUE THREAD

**Issue by Itsamna** [cbeust/testng#881] opened 2015-11-18 08:29 UTC
I'm using TestNG `dependsOnMethods` annotation to run my tests in intellij IDEA:

``` java
@Test(priority = 1)
public void test1(){
    Utils.line("test 1");
}

@Test(dependsOnMethods = {"test1"})
public void test2(){
    Utils.line("test 2");
}

@Test(dependsOnMethods = {"test2"})
public void test3(){
    Utils.line("test 3");
}
```

Test3 depends on Test2 and Test2 depends on Test1

All of them pass okay but a strange behavior occurs when I'm trying to debug the Test3 (Right click on method -> debug). I get an TestNG error:

> TestClass1.test2() is depending on method public void TestClass1.test1(), which is not annotated with @Test or not included.

However, when I debug Test2 in the same way, it runs okay. When I set Test3 depends on Test1 its also okay.

It seems like TestNG doesn't see a chain of dependencies in debug mode, or I'm doing something wrong?

**Comment by cbeust** [comment] 2015-11-18 18:22
Does this work fine from the shell? If yes, it might be a bug in the IDEA TestNG plug-in (which you should report on their tracker).

**Comment by juherr** [comment] 2015-11-21 23:42
Reproduced and reported to IDEA: https://youtrack.jetbrains.com/issue/IDEA-148334

**Comment by Itsamna** [comment] 2015-11-22 08:21
Sorry for the delay with answer. Yes, it must be an IDEA 15 issue because it is ok for me in 14 version.

**Comment by krmahadevan** [comment] 2018-05-31 04:12
Closing this issue because its an IntelliJ issue.

**Closed by krmahadevan** 2018-05-31 04:12 UTC
Labels: Feature: dependsOn

**Comment by pkpattabhiraman** [comment] 2019-08-24 09:44
This issue has resurfaced. 
`import org.testng.annotations.Test;

public class testTestng {
  @Test
  public void test1() {
    System.out.println("test1");
  }

  @Test (dependsOnMethods = {"test1"})
  public void test2() {
    System.out.println("test2");
  }


  @Test (dependsOnMethods = {"test2"})
  public void test3() {
    System.out.println("test3");
  }

  @Test (dependsOnMethods = {"test3"})
  public void test4() {
    System.out.println("test4");
  }
  
}
`
`com.myorg.features.mytest.testTestng.test3() is depending on method public void com.myorg.features.mytest.testTestng.test2(), which is not annotated with @Test or not included.
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:123)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:266)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:376)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:65)
	at org.testng.TestRunner.initMethods(TestRunner.java:438)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
`

**Comment by krmahadevan** [comment] 2019-08-28 04:43
@pkpattabhiraman - There's nothing that can be done if this is an intellij bug. You should report it on their bug tracker.

**Comment by Banshs23** [comment] 2024-08-27 11:42
I'm using TestNG dependsOnMethods annotation to run my tests in eclipse IDE:

![Screenshot 2024-08-27 170519](https://github.com/user-attachments/assets/ff919a48-331d-41ee-ba5c-41575dd7fe8c)

All test methods depends on each other
After creating a TestNG.XML for the same i m get error msg "NavigatetoMyInfo(), which is not annotated with @Test or not included."

![image](https://github.com/user-attachments/assets/bd7aed50-7719-4d6e-af51-40a142b6238c)

However, i tried with simple program with same code it works fine but above one throws error.

**Comment by juherr** [comment] 2024-08-27 15:36
@Banshs23 `verifyInfo` depends on `NavigatetoMyInfo` but is not included in `ParameterTest` test. The error is expected.
