### ISSUE TITLE
When <groups tag inserted after <suite tag in 6.9.13 version, it throws NullPointerException at getIncludedGroups(XmlSuite.java:1039)

### ISSUE THREAD

**Issue by TestLeafSel** [cbeust/testng#1216] opened 2016-10-23 06:56 UTC
### TestNG Version
6.9.13

### Expected behavior
When <groups tag introduced after <suite tag, then it executes the classes that have been included in the group.

### Actual behavior
When <groups tag introduced after <suite tag, then it throws NullPointerException with the following stack:

```java
java.lang.NullPointerException
	at org.testng.xml.XmlSuite.getIncludedGroups(XmlSuite.java:1039)
	at org.testng.xml.XmlTest.getIncludedGroups(XmlTest.java:138)
	at org.testng.TestRunner.initRunInfo(TestRunner.java:364)
	at org.testng.TestRunner.init(TestRunner.java:247)
	at org.testng.TestRunner.init(TestRunner.java:222)
	at org.testng.TestRunner.<init>(TestRunner.java:171)
	at org.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:28)
	at org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_10.java:61)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:604)
	at org.testng.SuiteRunner.init(SuiteRunner.java:170)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1359)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1346)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
```
But if I move the groups tag inside <test, then it runs as expected. 

### Is the issue reproductible on runner?
- [ ] Eclipse

### Test case sample
Here is the sample XML:
```xml
<suite name="Suite">
	<groups>
		<run>
			<exclude name="smoke"></exclude>
			<include name="sanity"></include>
		</run>
	</groups>
	<test name="Test">
		<classes>
			<class name="test.DeleteLead" />
			<class name="test.CreateLead" />
			<class name="test.EditLead" />
		</classes>
	</test> 
```
</suite>

**Comment by email2vimalraj** [comment] 2016-10-23 18:14
Unable to view your suite xml. Could you please attach it again?

**Comment by juherr** [comment] 2016-10-24 08:59
Duplicate of #1180

**Closed by juherr** 2016-10-24 08:59 UTC
