### ISSUE TITLE
Before Suite is not executed in the code.

### ISSUE THREAD

**Issue by TejasOm** [cbeust/testng#1816] opened 2018-06-07 18:02 UTC
### TestNG Version - 6.14
> Note: only the latest version is supported

### Is the issue reproductible on runner?
Yes
- [x] Maven
- [x] Eclipse

### Test case sample
public static ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(
			"E:\\Selenium Java\\com.crm.test\\src\\test\\TestReports\\LoginReport.html");

	public static ExtentReports extent = new ExtentReports();

	public static ExtentTest test;

	@BeforeSuite(alwaysRun=true)

	public void startReport() {
		extent.attachReporter(htmlReporter);

		extent.setSystemInfo("OS", "Windows 10");
		extent.setSystemInfo("Host Name", "Tejas");
		extent.setSystemInfo("Environment", "Selenium TestNG");
		extent.setSystemInfo("User Name", "Tejas Gupta");

		htmlReporter.config().setChartVisibilityOnOpen(true);
		htmlReporter.config().setDocumentTitle("DigitalCRM test Report");
		htmlReporter.config().setReportName("Login Test Report");
		htmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
		htmlReporter.config().setTheme(Theme.DARK);

	}

	@AfterMethod
	public void GetResult(ITestResult Result) throws Exception {
		if (Result.getStatus() == ITestResult.FAILURE) {
			test.log(Status.FAIL, MarkupHelper.createLabel(Result.getName() + "Test Case Failed", ExtentColor.RED));

			test.fail("Test case failed screenshot",
					MediaEntityBuilder.createScreenCaptureFromPath("Error1.png").build());
		}

		else if (Result.getStatus() == ITestResult.SUCCESS) {
			test.log(Status.PASS, MarkupHelper.createLabel(Result.getName() + "Test Case passed", ExtentColor.GREEN));
		}

		else {
			test.log(Status.SKIP, MarkupHelper.createLabel(Result.getName() + "Test Case Skipped", ExtentColor.AMBER));

			test.skip(Result.getThrowable());
		}

	}

	@AfterSuite(alwaysRun=true)

	public void EndReport()

	{
		extent.flush();

	}

}

I have the same code for another project and it is working fine for it, But here it does not go inside the BeforeSuite annotation

**Comment by krmahadevan** [comment] 2018-06-08 02:57
@TejasOm - This is a very basic use case for TestNG. Can you remove off all references to `extent reports` and just run a plain vanilla test such as the below one and let us know what you see

```java
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class Example {
  @BeforeSuite
  public void beforeSuite() {
    System.err.println("beforeSuite");
  }

  @Test
  public void test() {
    System.err.println("test");
  }

  @AfterSuite
  public void afterSuite() {
    System.err.println("afterSuite");
  }
}
```

If this sample runs, then the issue is most probably in your test code.

**Comment by TejasOm** [comment] 2018-06-08 03:33
Hi,

I have run the sample code which you asked me to run and it worked.
But no idea why my code is not working. Can you help me out with that?

**Comment by krmahadevan** [comment] 2018-06-08 03:36
Based on above comments from user, closing this issue. 

@TejasOm - Please create a sample that can be executed by anyone and post it on the testng-users google forum ( here : https://groups.google.com/forum/#!forum/testng-users). This is really not a TestNG question to be honest, but I have seen folks using extent reports. So you may get an answer from someone.

Please make sure that its a simple standalone, its complete and anyone can run it.  

Alternatively, I would also recommend that you please post your question on the extent reports relevant forum as well.

**Closed by krmahadevan** 2018-06-08 03:36 UTC

**Comment by TejasOm** [comment] 2018-06-08 03:38
Okay Thanks
