### ISSUE TITLE
Version 7.1.0, @BeforeGroups and @AfterGroups Annotations are not working

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [cbeust/testng#2229] opened 2020-01-21 20:02 UTC
I believe that this issue is a regression as they are working normally on version 7.0.0 

### TestNG Version
7.1.0

### Expected behavior
The @BeforeGroups and @AfterGroups should be working properly when triggering the execution from a TestNG class, xml file or surefire plugin.

### Actual behavior
The @BeforeGroups and @AfterGroups are not working when executing the the run from a TestNG class or from the surefire plugin, only works when the test is triggered from a testng.xml file **when I include the group name in the run parameter**.

### Is the issue reproductible on runner?

I'm running the test class directly via the IDE  [Eclipse] and via the cmd using surefire plugin .
- When running the test class directly via the IDE >> the issue happens and the Groups annotations doesn't work.
- When running from the xml file while including the groups names in the run parameter >> the Groups annotations works fine.

Same happens with maven surefire plugin.

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [x] IntelliJ
- [x] NetBeans
- [x] Surefire plugin

### Sample code to reproduce:

```xml
package testNG;

import org.testng.annotations.AfterGroups;
import org.testng.annotations.BeforeGroups;
import org.testng.annotations.Test;

public class TestGroupsAnnotations {

	@BeforeGroups(groups = "testGroup1")
	public void beforeGroups1() {
		System.out.println("Test Before Groups Annotation");
	}
	
	@AfterGroups(groups = "testGroup1")
	public void afterGroups1() {
		System.out.println("Test After Groups Annotation");
	}


	@Test(groups = "testGroup1")
	public void test1() {
		System.out.println("Test #1");
	}
	@Test(groups = "testGroup2")
	public void test2() {
		System.out.println("Test #2");
	}
	@Test(groups = "testGroup1")
	public void test3() {
		System.out.println("Test #3");
	}
	@Test(groups = "testGroup2")
	public void test4() {
		System.out.println("Test #4");
	}
	
	
	@BeforeGroups(groups = "testGroup2")
	public void beforeGroups2() {
		System.out.println("Test Before Groups Annotation #2");
	}
	
	@AfterGroups(groups = "testGroup2")
	public void afterGroups2() {
		System.out.println("Test After Groups Annotation #2");
	}
	
}
```

**Version 7.1.0 behavior**
![Ec7 1 0](https://user-images.githubusercontent.com/46620378/73267767-56a09400-41e2-11ea-96b8-da7c8689ec03.png)
![7 1 0](https://user-images.githubusercontent.com/46620378/73266087-ddec0880-41de-11ea-8671-f70ee44e42ed.png)

**Version 7.0.0 behavior**
![Ec7 0 0](https://user-images.githubusercontent.com/46620378/73267817-68823700-41e2-11ea-9f04-1ffc8ba4c9ab.png)
![7 0 0](https://user-images.githubusercontent.com/46620378/73266105-e47a8000-41de-11ea-991e-bc7353f63197.png)

**Comment by MohabMohie** [comment] 2020-01-21 20:08
I can reproduce the same issue on my environment as well.
Eclipse (12-2019) + JDK 13 + Maven

Working on TestNG 7.0.0
Not working on TestNG 7.1.0

**Comment by krmahadevan** [comment] 2020-01-27 09:51
@MahmoudElSharkawy - Can you please help with the following:

1. Please provide a sample that can be used to recreate this issue.
2. Please share information on how are you running the test. Is it via the IDE or is it via maven surefire plugin that uses a testng suite xml file.

**Comment by MahmoudElSharkawy** [comment] 2020-01-27 10:25
> 
> 
> @MahmoudElSharkawy - Can you please help with the following:
> 
>     1. Please provide a sample that can be used to recreate this issue.
> 
>     2. Please share information on how are you running the test. Is it via the IDE or is it via maven surefire plugin that uses a testng suite xml file.

@krmahadevan 
I'm running the test class directly via the IDE  [Eclipse] (Right click >> Run As TesNG Test) .
- When running the test class directly via the IDE >> the issue happens and the Groups annotations doesn't work.
- When running from the xml file (sample below) >> the Groups annotations works fine.

Same happens with maven surefire plugin.


### Sample code:
`package testNG;

import org.testng.annotations.AfterGroups;
import org.testng.annotations.BeforeGroups;
import org.testng.annotations.Test;

public class TestGroupsAnnotations {

	@BeforeGroups(groups = "testGroup1")
	public void beforeGroups1() {
		System.out.println("Test Before Groups Annotation");
	}
	
	@AfterGroups(groups = "testGroup1")
	public void afterGroups1() {
		System.out.println("Test After Groups Annotation");
	}


	@Test(groups = "testGroup1")
	public void test1() {
		System.out.println("Test #1");
	}
	@Test(groups = "testGroup2")
	public void test2() {
		System.out.println("Test #2");
	}
	@Test(groups = "testGroup1")
	public void test3() {
		System.out.println("Test #3");
	}
	@Test(groups = "testGroup2")
	public void test4() {
		System.out.println("Test #4");
	}
	
	
	@BeforeGroups(groups = "testGroup2")
	public void beforeGroups2() {
		System.out.println("Test Before Groups Annotation #2");
	}
	
	@AfterGroups(groups = "testGroup2")
	public void afterGroups2() {
		System.out.println("Test After Groups Annotation #2");
	}
	
}
`

### Sample xml file:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite">
	<test name="Test">
		<groups>
			<run>
				<include name="testGroup1"></include>
				<include name="testGroup2"></include>
			</run>
		</groups>
		<classes>
			<class name="testNG.TestGroupsAnnotations" />
		</classes>
	</test> 
</suite> 
`

**Comment by krmahadevan** [comment] 2020-01-27 10:35
@MahmoudElSharkawy - Looks like this is a problem with the TestNG eclipse plugin.

You might want to log this issue in https://github.com/cbeust/testng-eclipse/issues 

> Same happens with maven surefire plugin.

I didn't quite understand this part. Does this mean that you are using `mvn clean test -Dtest= TestGroupsAnnotations` ? If yes, then this wont work like that because you aren't specifying what groups to be run. In that case, the group mode won't be even selected.

**Comment by MahmoudElSharkawy** [comment] 2020-01-27 10:52
> 
> 
> @MahmoudElSharkawy - Looks like this is a problem with the TestNG eclipse plugin.
> 
> You might want to log this issue in https://github.com/cbeust/testng-eclipse/issues
> 
> > Same happens with maven surefire plugin.
> 
> I didn't quite understand this part. Does this mean that you are using `mvn clean test -Dtest= TestGroupsAnnotations` ? If yes, then this wont work like that because you aren't specifying what groups to be run. In that case, the group mode won't be even selected.

@krmahadevan 
I mean the behavior is the same when I run from the IDE and the test class directly and wehn I run from the surefire plugin.
If I uderstand this right, using the @BeforeGroups & @AfterGroups annotations should be working when I run from the test class or surefire plugin with the same behavior.. It will however work as you said if I'm not using those annotations and only specify the groups names for the @Test test cases only; Here I need to specify what groups to be run run via the xml file.

**Please find below two screenshots from both TestNG version from the surefire plugin execution (Both and from the same sample provided in the previous comment)**

7.1.0
![7 1 0](https://user-images.githubusercontent.com/46620378/73168767-2df59d00-4103-11ea-8b00-710c3c5f1e0c.png)

7.0.0
![7 0 0](https://user-images.githubusercontent.com/46620378/73168791-3cdc4f80-4103-11ea-953a-8222de6e7a0e.png)

**Comment by Nikasan** [comment] 2020-03-02 10:20
Reproduced the same issue: TestNG (7.1.0) +Gradle
sample code:
` @BeforeGroups(groups = "IT Department")
    public void before_it()
    {
        System.out.println("This method will be executed before the execution of IT Department group");
    }
    @Test
    public void testcase1()
    {
        System.out.println("HR");
    }
    @Test(groups= {"IT Department"})
    public void testcase2()
    {
        System.out.println("Software Developer");
    }
    @Test(groups= {"IT Department"})
    public void testcase3()
    {
        System.out.println("QA Analyst");
    }`

Expected behavior: 
HR
This method will be executed before the execution of IT Department group
Software Developer
QA Analyst

**Actual:**
HR
Software Developer
QA Analyst

Run from IDEA (last version)

**Comment by MikeLaptev** [comment] 2020-04-23 17:17
Looks like I've faced a similar issue after upgrading to 7.1.0

**Comment by EyalSooliman** [comment] 2020-06-03 15:26
I get the same issue after upgrading to 7.1 on maven. org.testng fail to load the dependency files.

**Comment by krmahadevan** [comment] 2020-06-18 08:43
Folks,
The behavior of TestNG was changed as part of `7.1.0` via this PR https://github.com/cbeust/testng/pull/2167

By default group selection is not applicable until and unless its explicitly chosen via the suite xml file.

Prior to TestNG `7.1.0` if there was a `@BeforeGroups`/`@AfterGroups` annotation, that  method was getting executed irrespective of whether group selection was applied or not.

This behavior has been changed and now `@BeforeGroups`/`@AfterGroups` annotated methods would get executed only when group filtering is turned on via the suite xml file.

So if this behavior is needed to be enabled, please create a suite xml file, resort to selection of groups adding 

```xml
<groups>
      <run>
        <include name="group-one"/>
      </run>
</groups>
```

in suite xml file and then using it.

Closing this issue.

**Closed by krmahadevan** 2020-06-18 08:43 UTC
Labels: Need: sample

**Comment by MohabMohie** [comment] 2020-06-18 23:47
@krmahadevan is there another way for those of us who don't use a suite xml?
My solution is built on top of using the surefire plugin, and passing the tests parameter to create a suite in the runtime... so is there a way to do something by code to get the old behavior? like a property that I can set or something?

**Comment by krmahadevan** [comment] 2020-06-19 03:42
@MohabMohie - This wasn't a regression to begin with. This was a bug that always existed in TestNG which was fixed. So there's no way of doing this, unless and until, you know what the groups are. If that knowledge is there, then you can very well use an implementation of `IAlterSuiteListener` wherein you can weave in the group information programmatically into the suite and then work with it. There's no property that can be used to toggle this.

On a side note, I would be curious to know as to what exists within these `@BeforeGroups` and `@AfterGroups` ? It sounds like they perhaps are in the wrong place to begin with. If its a setup/tear down that you would like to be executed all the time, you can perhaps put them within an implementation of `IInvokedMethodListener` which you can wire in via a SPI mechanism ?

If you can add more details (please feel free to be as elaborate as possible) I can suggest some alternatives.

**Comment by MahmoudElSharkawy** [comment] 2021-10-20 16:35
> 
> 
> Hi,
> 
> I think we also have phased this issue now when we Testing TestNg 7.5, we are using 6.14 at the moment and are working on uplifting to latest TestNg, but it seems not possible due to this change. We have over 500 Projects and thousands of test cases in different organizations and thousands developers. It will never be possible to adapt all of the Test and as I see it is not even a possible alternative to this change.
> 
> In many Test Cases we using groups to run different Before/After methods/class and we have test within the same test class with different groups and without groups. As I understand now we must specify the groups in the suite, but that will not work for us.
> 
> I don't think this was a bug correction, I think that removing a very useful feature from TestNg that simplifies test cases allot.

Thank you for stating this. I totally agree; It was a very useful feature and it's removed without introducing any useful alternatives. For what I know and understand, Annotations are meant to run in the class and no need for suits to be configured.

**Comment by martinaldrin** [comment] 2021-10-20 16:53
We have been working hard for long time to get correction on master and PR merged and then I suddenly met this issue and adapt to other Non backward compatible changes.  I'm surprised that a very nice feature is treated as a bug and removed. this makes it extremely hard to do an uplift now. We using groups in plenty places without specify them in a suite, and for regular unit tests we don't even have suites but still uses groups.

**Comment by martinaldrin** [comment] 2021-10-21 13:53
Hi, 

Here is an simple test example on a unit test without a suite, there might be many more cases.  

```
public class Demo {

	boolean valueA = false;
	boolean valueB = false;
	
	@BeforeGroups(groups = "groupA")
	public void beforeGroupA() {
		valueA = true;
	}
	
	@BeforeGroups(groups = "groupB")
	public void beforeGroupB() {
		valueB = true;
	}
	
    @Test
    public void testA() {
        System.out.println("TestA");
    }
    
    @Test
    public void testB() {
        System.out.println("TestB");
    }
    
    @Test
    public void testC() {
        System.out.println("TestC");
    }
    
    @Test(groups = "groupA")
    public void testGroupA() {
       Assert.assertTrue(valueA, "BeforeGroupA was not executed");
    }
    
    @Test(groups = "groupB")
    public void testGroupB() {
    	Assert.assertTrue(valueB, "BeforeGroupB was not executed");
    }
    
    @AfterGroups(groups = "groupA")
	public void afterGroupA() {
		valueA = false;
	}
	
    @AfterGroups(groups = "groupB")
	public void afterGroupB() {
		valueB = false;
	}
    

    @AfterClass
    public void afterClass() {
    	Assert.assertFalse(valueA, "AfterGroupsA was not executed");
    	Assert.assertFalse(valueB, "AfterGroupsB was not executed");
    }
    
}
```

Test result: 6.14.x
![image](https://user-images.githubusercontent.com/3080866/138291458-a5c94264-3789-4be7-bc2a-7ca18e50c43d.png)


Test result: 7.5
![image](https://user-images.githubusercontent.com/3080866/138291801-386bb47c-af48-4c31-944e-f0af95753655.png)
