### ISSUE TITLE
Getting: "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project <Project Name>: There are test failures." 

### ISSUE THREAD

**Issue by nvphaneendra** [cbeust/testng#1724] opened 2018-03-18 17:19 UTC
### TestNG Version
TestNG version : 6.13.1

### Expected behavior
Maven surefire plugin should run successfully. 

### Actual behavior
Getting an [ERROR] message as, "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project <Project Name>: There are test failures."

### Is the issue reproductible on runner?

- [YES] Maven
- [ YES] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
My project repo, https://github.com/nvphaneendra/JiveProductAutomation

### Console log,
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:45 min
[INFO] Finished at: 2018-03-18T22:29:39+05:30
[INFO] Final Memory: 13M/179M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project jive-gui-tests: There are test failures.
[ERROR]
[ERROR] Please refer to F:\Selenium_Neon\jive-gui-tests\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_131\jre\bin\java" -jar C:\Users\Phani\AppData\Local\Temp\surefire9154197824704133889\surefirebooter2568059204345921658.jar C:\Users\Phani\AppData\Local\Temp\surefire9154197824704133889 2018-03-18T22-27-58_555-jvmRun1 surefire7771638459190427293tmp surefire_06359485536493426076tmp"
[ERROR] Process Exit Code: 0
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_131\jre\bin\java" -jar C:\Users\Phani\AppData\Local\Temp\surefire9154197824704133889\surefirebooter2568059204345921658.jar C:\Users\Phani\AppData\Local\Temp\surefire9154197824704133889 2018-03-18T22-27-58_555-jvmRun1 surefire7771638459190427293tmp surefire_06359485536493426076tmp"
[ERROR] Process Exit Code: 0
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by nvphaneendra** [comment] 2018-03-18 17:22
Note : When I execute my project, my Chrome browser is not closing properly. For each test, it is launching with new browser.

**Comment by krmahadevan** [comment] 2018-03-19 03:18
@nvphaneendra - The project involves selenium and your project doesn't run out of the box on a Non Windows machine. Can you create a sample that doesn't involve anything outside of Java and share it, which we can use to reproduce the issue ? You seem to be experiencing a JVM crash. See [here](http://maven.apache.org/surefire/maven-surefire-plugin/faq.html#vm-termination) for some pointers.

**Comment by nvphaneendra** [comment] 2018-03-19 04:28
Hi @krmahadevan , I am executing my selenium with Java project on Windows 10 machine.

**Comment by krmahadevan** [comment] 2018-03-19 04:30
@nvphaneendra - That is fine. But am pretty sure, you can create a sample that is OS agnostic. Not sure if its practical for us to sift through your sample, fix the problems to make it work in OSX and then try and figure out what is going wrong. 

So until you can help provide us a sample that can show that the crash is due to TestNG, not sure what can be done here.

**Comment by nvphaneendra** [comment] 2018-03-19 04:43
@krmahadevan , Is it possible to discuss on this issue on Skype? How to resolve this ?
My Skype ID: nvphaneendra.

Thank you in advance.

**Comment by krmahadevan** [comment] 2018-03-19 04:46
@nvphaneendra - I am not sure if I have that much time to spend on this. For now I am going to have to close this issue. Please feel free to request for a re-open or create a new issue, once you can share a sample that can be used to reproduce the issue.

On a side note, I would recommend that you perhaps should post your query on `selenium-users` google forum and seek help. But even there, I would recommend that you please create a project which anyone can run and which is OS agnostic.

**Closed by krmahadevan** 2018-03-19 04:46 UTC

**Comment by davisvitate** [comment] 2020-08-18 20:36
@nvphaneendra could you solve the problem? is that I have the same problem. Could it be because of the Operating System? or how to fix it?
Thank you in advance.
