### ISSUE TITLE
Display Running Test Cases

### ISSUE THREAD

**Issue by nathanila** [cbeust/testng#797] opened 2015-09-10 22:48 UTC
I am running TestNG tests cases via an Eclipse Debug Configuration. The configuration specifies to run a Suite file named testng.xml. Here's the contents.

<suite name="All" verbose="1" parallel="methods" thread-count="100">
  <test name="All">
    <packages>
      <package name=".*"/>
    </packages>
  </test>
</suite>

Eclipse will show the Results of running suite window. In the window under the All Tests tab, I see a tree of tests that have finished. I don't see any of the tests which are pending or running. How do I cause Eclipse to show the tests which are pending or running?

Furthermore, the progress bar at the top says Tests: 0/1 Methods: 80 at the top. The progress bar is drawn at a 100%. As test cases finish, the number of methods increases and the bar still stays at 100%. How do I cause Eclipse to show the actual progress?

Setting verbose to 10 doesn't fix the problem. Removing parallel and thread-count options doesn't fix the problem.

**Comment by juherr** [comment] 2015-09-19 20:31
Duplicate of #794

**Closed by juherr** 2015-09-19 20:31 UTC
Labels: eclipse
