### ISSUE TITLE
Disabled test still runs

### ISSUE THREAD

**Issue by madhead** [cbeust/testng#1015] opened 2016-04-04 11:06 UTC
I have a very simple test:

```
import org.testng.Assert;
import org.testng.annotations.Test;

@Test(enabled = false)
public class DisabledTest {
	@Test
	public void testMath() {
		Assert.assertEquals(2 + 2, 5, "Something is wrong");
	}
}
```

I run it with Gradle like `./gradlew test`. I expect this one not to run, but it runs and fails the build. I've created a [demo repo](https://github.com/madhead/testng-enabled-test) which shows the issue and debug output in `README.md`. I've tested TestNG version `6.8.8` and `6.9.10` - they both behave the same. Am I missing something?

**Comment by juherr** [comment] 2016-04-04 14:27
Duplicate of https://github.com/cbeust/testng/issues/151

**Closed by juherr** 2016-04-04 14:27 UTC
