### ISSUE TITLE
AfterSuite method selection depends on test xml order dealing with Groups

### ISSUE THREAD

**Issue by EugeneYushin** [cbeust/testng#1583] opened 2017-10-26 16:36 UTC
### TestNG Version
6.11, 6.12

### Expected behavior
I expect to see valid candidate of ConfigurationMethod instance to be checked for AfterSuite call when groups are applied.

### Actual behavior
ConfigurationMethod stores instance of the first test from xml config. If this test is not a part of included groups, it will result in incorrect behavior of AfterSuite method.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ x] IntelliJ
- [ ] NetBeans

### Test case sample
Config:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Hello Groups">
    <test name="Groups test">
        <groups>
            <run>
                <include name="sanity"/>
            </run>
        </groups>
        <classes>
            <class name="com.test.tests.InsanityTest"/>
            <class name="com.test.tests.SanityTest"/>
        </classes>
    </test>
</suite>
```

Main.class:
```
public class Main {
    public static void main(String[] args) {
        TestNG runner = new TestNG();
        XmlSuite xmlSuite = new XmlSuite();
        xmlSuite.setSuiteFiles(Collections.singletonList("src/main/resources/dummy_test.xml"));
        runner.setXmlSuites(Collections.singletonList(xmlSuite));
        runner.run();
    }
}
```

Parent test with AfterSuite:
```
public class MyTest {
    private String s;

    public MyTest(String str) {
        this.s = str;
    }

    @AfterSuite(alwaysRun = true)
    public void shutdown() {
        System.out.println("s = " + s);
        System.out.println("Bye-bye");
    }
}
```

Actual tests:
```
public class InsanityTest extends MyTest {
    public InsanityTest() {
        super("insanity");
    }

    @Test(groups = {"insanity"})
    public void test() {
        System.out.println("I'm INSANITY test");
    }
}

public class SanityTest extends MyTest {
    public SanityTest() {
        super("sanity");
    }

    @Test(groups = {"sanity"})
    public void test() {
        System.out.println("I'm sanity test");
    }
}
```

Result log:
```
I'm sanity test
s = insanity
Bye-bye

===============================================
Hello Groups
Total tests run: 1, Failures: 0, Skips: 0
===============================================


===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

As you can see, instance of InsanityTest was selected to call AfterSuite method (log: **s = insanity**).
I expect to see **"s = sanity"**.

**Comment by krmahadevan** [comment] 2017-10-26 16:49
@EugeneYushin - Can you please try this once again with TestNG 6.12 and let us know the results ? 
TestNG 6.12 is published in JCenter (https://jcenter.bintray.com/org/testng/testng/6.12/) and is not available in Maven Central

**Comment by EugeneYushin** [comment] 2017-10-27 09:45
@krmahadevan The same behavior for 6.12 version. I've added 6.12 to Version section

**Comment by juherr** [comment] 2017-11-03 21:21
It works as designed. 

Currently, TestNG create instances from test classes, select tests and run them. It found classes according to the order in the xml file.

If `InsanityTest` is first, then TestNG will instantiate it, exclude `test` but keep `shutdown`. After that, TestNG will find and instantiate `SanityTest`, include `test` and skip `shutdown` because only one after suite is possible.

**Comment by juherr** [comment] 2017-11-03 21:24
I close the issue because it is not one but we can continue to discuss if you still think something should be fixed.

**Closed by juherr** 2017-11-03 21:24 UTC
Labels: Feature: before/after, Feature: groups
