### ISSUE TITLE
Execution order is incorrect for single-threaded test class when priority and dependsOnMethods are used simultaneously

### ISSUE THREAD

**Issue by selenareneephillips** [cbeust/testng#851] opened 2015-11-01 20:20 UTC
I have some tests which I want to run in  a particular order, but when combining 'dependsOnMethods' feature with 'priority, the execution order is incorrect.

Here is a test class to reproduce the bug. I am using TestNG 6.9.9.

    import org.testng.annotations.Test;

    @Test(singleThreaded = true)
    public class ExecutionOrderBug {

        @Test(priority = 0 )
        public void test1()  {
            System.out.print("Test 1");
        }

        @Test(priority = 1)
        public void test2() {
            System.out.print("Test 2");
        }

        @Test(priority = 2, dependsOnMethods = "test2")
        public void test3()  {
            System.out.print("Test 3");
        }

       @Test(priority = 3)
        public void test4()  {
            System.out.print("Test 4");
        }

        @Test(priority = 4)
        public void test5() {
            System.out.print("Test 5");
        }
    }

Expected order: test1, test 2, test3, test4, test5
Actual order: test1, test2, test4, test5, test3

**Comment by juherr** [comment] 2015-11-01 21:59
Duplicate of #474

**Closed by juherr** 2015-11-01 21:59 UTC
Labels: dependsOn, priority
