### ISSUE TITLE
Listener in multi-test context

### ISSUE THREAD

**Issue by gjuillot** [cbeust/testng#1130] opened 2016-08-31 15:45 UTC
Hi,

I have a listener which both implements ISuiteListener and IClassListener.

```java
public class MyListener implements ISuiteListener, IClassListener {
  
  public MyListener() {
    System.out.println("Instantiate new MyListener");
  }

  public void onStart(ISuite suite) {
    System.out.println("onStart of " + this);
  }

  public void onBeforeClass(ITestClass testClass) {
    System.out.println("onBeforeClass of " + this);
  }

  public void onTestStart(ITestResult result) {
  }
  public void onTestSuccess(ITestResult result) {
  }
  public void onTestFailure(ITestResult result) {
  }
  public void onTestSkipped(ITestResult result) {
  }
  public void onTestFailedButWithinSuccessPercentage(ITestResult result) {
  }
  public void onStart(ITestContext context) {
  }
  public void onFinish(ITestContext context) {
  }
  public void onFinish(ISuite suite) {
  }
  public void onAfterClass(ITestClass testClass) {
  }
}
```

and two test classes that use this listener via a common mother class

```java
@Listeners(MyListener.class)
public class CommonTest {
}

public class ATest extends CommonTest {
  @Test
  public void testA1() {
    System.out.println("A1");
  }
}

public class BTest extends CommonTest {
  @Test
  public void testB1() {
    System.out.println("B1");
  }
}
```

I run these two classes in separate <test>

```xml
<suite name="Suite with two tests">
  <test name="ATest">
    <classes>
      <class name="ATest" />
    </classes>
  </test>
  <test name="BTest">
    <classes>
      <class name="BTest" />
    </classes>
  </test>
</suite>
```

I got the following output

> onStart of MyListener@b101344
> onBeforeClass of MyListener@1f3f668d
> onBeforeClass of MyListener@b101344
> A1
> onBeforeClass of MyListener@1f3f668d
> onBeforeClass of MyListener@b101344
> B1

There's something illogical to me here: why is onStart called only for one of the intances while both instances have their onBeforeClass called twice.

I am not sure about expected behavior, but the following solutions would sound at least logical

- only one listener is instantiated
- one listener per class, onStart called for each, onBeforeClass only called once per listener

**Comment by juherr** [comment] 2016-08-31 15:56
Thanks for the report. 

I agree something looks wrong.

Is this output more acceptable for you?

> onStart of MyListener@b101344
> onBeforeClass of MyListener@1f3f668 (or @b101344)
> A1
> onBeforeClass of MyListener@b101344 (or @1f3f668)
> B1

**Comment by gjuillot** [comment] 2016-09-01 07:45
It would look more logical. But again why only one onStart ?

**Comment by juherr** [comment] 2016-09-01 08:05
Only one `onStart` because it follows the `@BeforeSuite` behavior.

For example, if you add a `@BeforeSuite` method in your `CommonTest`, then the method will be only called once, even if you have more than 1 instance (here: `ATest` and `BTest`).
People are often complaining about it but it works like that for years.

I don't know if we should change this behavior for listeners and/or configuration methods. 
@cbeust what do you think?

**Comment by juherr** [comment] 2016-09-01 08:08
And maybe the issue is having 2 instances here.

Will it be ok for you if:

> onStart of MyListener@b101344
> onBeforeClass of MyListener@b101344
> A1
> onBeforeClass of MyListener@b101344
> B1

**Comment by gjuillot** [comment] 2016-09-01 09:08
That's what I was going to say. If testNG runs only one @BeforeSuite if it is in a common class, then why does it add two listeners ?

For sure the last would be the best for me.

**Comment by juherr** [comment] 2016-09-01 22:53
I fixed the first problem (too many calls of methods) but it is not yet pull-requested/merged.

To fix the second problem, it will take more time because I think all listener management should be reworked. For example, `@Listeners` is only looked by the `TestRunner` but not at `SuiteRunner` and the `TestRunner` will add appropriate listeners into the suite.
In your case, as you have 2 ` <test>`, the listener is instantiated twice. We don't have twice call on `onStart` because it is not expected and some tricks were made.

I think runners should only be concerned by their own listeners and pass the others to the lower levels (ie: suite -> test), and not the opposite.

**Closed** 2016-09-04 17:15 UTC
Labels: Feature: listener

**Comment by gjuillot** [comment] 2016-09-06 13:19
I now have

> Instantiate new MyListener
onStart of MyListener@331c9ba1
onBeforeClass of MyListener@331c9ba1
A1
onBeforeClass of MyListener@331c9ba1
B1

Thank you
