### ISSUE TITLE
Assert.assertNotSame reports confusing message

### ISSUE THREAD

**Issue by VladRassokhin** [cbeust/testng#350] opened 2013-03-04 14:47 UTC
Currently reported is `expected not same [testng-6.8.jar] but found [testng-6.8.jar]`.

But since expected and actual object same, why both written?
I think better variant is `expected objects are not same but both are [testng-6.8.jar]` or something similar.

**Comment by krmahadevan** [comment] 2020-03-13 04:52
Closing this issue since TestNG is working as designed. Here the comparison is if the two references are to two different objects object and not the equality clause that is being checked.

**Closed by krmahadevan** 2020-03-13 04:52 UTC
