### ISSUE TITLE
TestNG Version 6.13.1 does not perform parallel execution

### ISSUE THREAD

**Issue by dpradhan79** [cbeust/testng#1664] opened 2018-01-11 12:26 UTC
### TestNG Version
> 6.13.1

### Expected behavior
Parallel execution with parallel = "tests"

Below testng.xml was used for testing purpose with test methods for addition and subtraction. One test method testAdd kept on incrementing variable with a condition to stop and another test method kept in decrementing variable with a condition to stop. All methods are supposed to print variable values. This has to happen in asynchronous way, if parallel attribute is set to test in suite tag in testng.xml. With 6.13.2, this does not happen. With 6.11, parallel tests work.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" parallel="tests" thread-count="5">
	<parameter name="testSum1" value="1" />
	<parameter name="testSum2" value="2" />
	<parameter name="expectedSumResult" value="3" />
	<parameter name="testSub1" value="3" />
	<parameter name="testSub2" value="2" />
	<parameter name="expectedSubResult" value="1" />
	  <test name="Test1">
		  <classes>
		  	<class name="learntestng.TestSubstract" />  
		  </classes>
	  </test>
	  <test name="Test2">
		  <classes>
		  	<class name="learntestng.TestSum" />  
		  </classes>
	  </test>
</suite> 

### Is the issue reproductible on runner?

Yes
[learntestng.zip](https://github.com/cbeust/testng/files/1622491/learntestng.zip)

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment] 2018-01-11 14:01
Duplicate of https://github.com/cbeust/testng/issues/1636

This has been fixed in TestNG `6.14-SNAPSHOT`. Please try using that version.

**Closed by krmahadevan** 2018-01-11 14:01 UTC
