### ISSUE TITLE
TestNG version number differs in pom.xml and in execution log

### ISSUE THREAD

**Issue by plaidshirtakos** [cbeust/testng#1802] opened 2018-05-28 09:11 UTC
### TestNG Version
6.14.3

### Expected behavior
I just wondering, why isn't version 6.14.3 in use?

### Actual behavior
I added TestNG dependency in pom.xml file.

```
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.14.3</version>
    <scope>compile</scope>
</dependency>
```
I see following during execution of test:

> ... ... TestNG 6.8.9beta by Cédric Beust (cedric@beust.com) ...

### Is the issue reproductible on runner?

- [ ] Shell
- [x ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ x] IntelliJ
- [ ] NetBeans

Question on [SO](https://stackoverflow.com/questions/50562569/testng-version-number-differs-in-pom-xml-and-in-execution-log)

**Comment by krmahadevan** [comment] 2018-05-28 15:16
I cannot reproduce this issue.

I am using the following 

* IntelliJ version : 
```
IntelliJ IDEA 2018.1.4 (Ultimate Edition)
Build #IU-181.5087.20, built on May 17, 2018
```

* TestNG-J version : 8.0

I see the following when trying to execute a test

```
...
... TestNG 6.14.3 by Cédric Beust (cedric@beust.com)
...
com.rationaleemotions.googleforums.groupdeps.jeff.TestGroup1_Class1
com.rationaleemotions.googleforums.groupdeps.jeff.TestGroup2

===============================================
336_Suite-MySuite-InVM
Total tests run: 2, Failures: 0, Skips: 0
===============================================

```

**Comment by juherr** [comment] 2018-05-28 21:55
It could be an issue an issue of IntelliJ if you run the maven via the IDE.
IntelliJ has an old embedded TestNG version and I suppose it is the version you are seeing.

Could you try a run outside IntelliJ and tell us if the problem still exists.
If it still the case, please provide a full runnable project that will help us to reproduce.

You should update your SO question with the IntelliJ aspect and appropriate tags because

**Comment by krmahadevan** [comment] 2018-05-29 02:02
@juherr 

> You should update your SO question with the IntelliJ aspect and appropriate tags because Jetbrain is doing some support on SO.

Done on behalf of the user

**Comment by krmahadevan** [comment] 2018-05-30 02:12
@plaidshirtakos - Were you able to simulate the problem when you run from the command line (for e.g., via a build tool such as Maven/gradle) ?

**Comment by plaidshirtakos** [comment] 2018-05-30 07:55
@krmahadevan : I executed it, but TestNG version number doesn't show up in this case.

**Comment by krmahadevan** [comment] 2018-05-30 07:57
@plaidshirtakos <https://github.com/plaidshirtakos>
You will see the version number if you have set the attribute verbose="2"
or higher in your <suite> tag of your xml.
Can you please do that and post back the results ?

**Comment by plaidshirtakos** [comment] 2018-05-30 08:04
@krmahadevan : It is already defined in `testng.xml`. `<suite name="My_Test_Suite" verbose="2" parallel="methods" thread-count="1">`

**Comment by krmahadevan** [comment] 2018-05-30 08:06
@plaidshirtakos

Just to be elaborate, can you please do the following :

1. Share the complete contents of your suite xml file ?
2. Share the plugin configuration of maven-surefire-plugin from your pom
file ?
3. Share the command output of how you are running the tests from command
line using maven ?

That should basically clear out all the ambiguities.

**Comment by krmahadevan** [comment] 2018-06-01 02:27
ping @plaidshirtakos - Any updates ?

**Comment by krmahadevan** [comment] 2018-06-05 08:14
ping @plaidshirtakos - Any updates ?

**Comment by krmahadevan** [comment] 2018-06-07 15:58
Closing this issue since there's no updates from the user. Please comment with needed details if this is still a problem.

**Closed by krmahadevan** 2018-06-07 15:58 UTC

**Comment by plaidshirtakos** [comment] 2018-06-22 10:44
@krmahadevan  : 
**1.**
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Levelezes_Suite" verbose="2" parallel="methods" thread-count="1">
    <listeners>
        <listener class-name="utils.TestNGListener"></listener>
    </listeners>
    <test name="Regression" parallel="false" >
        <classes>
            <class name="test.RegressionTest" />
        </classes>
    </test>
</suite>
```
**2.** 
I just deleted this plugin from pom.xml, but problem still persists.

**3.**
output of mvn test command:
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for groupId:MySuite:jar:1.
> 0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line
>  79, column 21
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> [INFO]
> [INFO] ----------------------< groupId:MySuite >-----------------------
> [INFO] Building MyTest 1.0-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- build-helper-maven-plugin:1.10:add-source (add-source) @ MySuite ---
> [INFO] Source directory: C:\Users\kovacsako\Documents\MySuite\appmodels added.
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MySuite ---
> [WARNING] Using platform encoding (Cp1250 actually) to copy filtered resources, i.e. build is platform depende
> nt!
> [INFO] Copying 3 resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ MySuite ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ MySuite ---
> [INFO] Not copying test resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ MySuite ---
> [INFO] Not compiling test sources
> [INFO]
> [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ MySuite ---
> [INFO] Tests are skipped.
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 5.779 s
> [INFO] Finished at: 2018-06-22T12:29:57+02:00
> [INFO] ------------------------------------------------------------------------

output of mvn install command:
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for groupId:MySuite:jar:1.
> 0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line
>  79, column 21
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> [INFO]
> [INFO] ----------------------< groupId:MySuite >-----------------------
> [INFO] Building MyTest 1.0-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- build-helper-maven-plugin:1.10:add-source (add-source) @ MySuite ---
> [INFO] Source directory: C:\Users\User\Documents\MySuite\appmodels added.
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MySuite ---
> [WARNING] Using platform encoding (Cp1250 actually) to copy filtered resources, i.e. build is platform depende
> nt!
> [INFO] Copying 3 resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ MySuite ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ MySuite ---
> [INFO] Not copying test resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ MySuite ---
> [INFO] Not compiling test sources
> [INFO]
> [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ MySuite ---
> [INFO] Tests are skipped.
> [INFO]
> [INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ MySuite ---
> [INFO]
> [INFO] --- maven-dependency-plugin:3.0.1:copy-dependencies (copy-dependencies) @ MySuite ---
> [INFO] log4j:log4j:jar:1.2.17 already exists in destination.
> [INFO] org.testng:testng:jar:6.14.3 already exists in destination.
> [INFO] com.beust:jcommander:jar:1.72 already exists in destination.
> [INFO] org.apache-extras.beanshell:bsh:jar:2.0b6 already exists in destination.
> [INFO] org.hamcrest:hamcrest-core:jar:1.3 already exists in destination.
> [INFO] commons-io:commons-io:jar:2.6 already exists in destination.
> [INFO] com.hp.lft:sdk:jar:14.0.0 already exists in destination.
> [INFO] com.hp.lft:report:jar:14.0.0 already exists in destination.
> [INFO] com.hp.lft:unittesting:jar:14.0.0 already exists in destination.
> [INFO] com.hp.lft:verifications:jar:14.0.0 already exists in destination.
> [INFO] javax:javaee-api:jar:7.0 already exists in destination.
> [INFO] com.sun.mail:javax.mail:jar:1.5.0 already exists in destination.
> [INFO] javax.activation:activation:jar:1.1 already exists in destination.
> [INFO]
> [INFO] --- maven-assembly-plugin:3.0.0:single (make-assembly) @ MySuite ---
> [INFO] Reading assembly descriptor: src/main/assembly/leanft-assembly.xml
> [ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with
>  slash) /
> [ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with
>  slash) /lib
> [ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with
>  slash) /config
> [ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with
>  slash) /
> [INFO] Building zip: C:\Users\User\Documents\MySuite\target\MySuite-1.0-SNAPSHOT.zip
> [INFO]
> [INFO] --- maven-install-plugin:2.4:install (default-install) @ MySuite ---
> [INFO] Installing C:\Users\User\Documents\MySuite\target\MySuite-1.0-SNAPSHOT.jar to C:\U
> sers\User\.m2\repository\groupId\MySuite\1.0-SNAPSHOT\MySuite-1.0-SNAPSHOT.jar
> [INFO] Installing C:\Users\User\Documents\MySuite\pom.xml to C:\Users\User\.m2\repository\gr
> oupId\MySuite\1.0-SNAPSHOT\MySuite-1.0-SNAPSHOT.pom
> [INFO] Installing C:\Users\User\Documents\MySuite\target\MySuite-1.0-SNAPSHOT.zip to C:\U
> sers\User\.m2\repository\groupId\MySuite\1.0-SNAPSHOT\MySuite-1.0-SNAPSHOT.zip
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 10.895 s
> [INFO] Finished at: 2018-06-22T12:31:41+02:00
> [INFO] ------------------------------------------------------------------------

**Comment by plaidshirtakos** [comment] 2018-06-27 10:30
I cannot re-open this issue, but maybe you got notification about new comment.

**Comment by krmahadevan** [comment] 2018-06-27 11:20
Yes I have got the notification about your comment. I will get to this at
the earliest. A bit swamped by other stuff. My humble apologies for the
delay.

**Comment by krmahadevan** [comment] 2018-06-28 03:06
@plaidshirtakos - Your logs indicate that you have `[INFO] org.testng:testng:jar:6.14.3 already exists in destination.` in your pom file. So where did you say the mismatch was coming from ? 
Is it from the IDE ? 

I also would request you to please do the following. Download the project that I attached [kungfu-panda.zip](https://github.com/cbeust/testng/files/2143563/kungfu-panda.zip)  and then run the below command from a prompt 

You should see 

```shell
[INFO]
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ kungfu-panda ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 6.14.3 by Cédric Beust (cedric@beust.com)
...

Executing :com.rationaleemotions.MasterOogway.testOne()
Executing :com.rationaleemotions.MasterOogway.testTwo()
Executing :com.rationaleemotions.MasterShifu.testOne()
Executing :com.rationaleemotions.MasterShifu.testTwo()
Executing :com.rationaleemotions.MasterTigress.testOne()
Executing :com.rationaleemotions.MasterTigress.testTwo()
```

You can import the same project into IntelliJ and/or eclipse and run the suite file and tell us what you see.

**Comment by juherr** [comment] 2018-06-29 07:48
6.8 is the embedded version of TestNG into IntelliJ. If you want more details, you should post on https://youtrack.jetbrains.com/issues?q=%23%7BUnit%20Testing.%20TestNG%7D%20
