### ISSUE TITLE
I have to edit the file “TestHtmlReporter.java”.

### ISSUE THREAD

**Issue by ruberzhu** [cbeust/testng#1043] opened 2016-05-12 12:30 UTC
I have to edit the file “TestHtmlReporter.java”.
I thought it would be better to send mail.
`private static final String HEAD =
    "\n<style type=\"text/css\">\n" +
    ".invocation-failed,  .test-failed  { background-color: #DD0000; } \n" +
    ".invocation-percent, .test-percent { background-color: #006600; } \n" +
    ".invocation-passed,  .test-passed  { background-color: #00AA00; } \n" +
    ".invocation-skipped, .test-skipped { background-color: #CCCC00; } \n" +
    ".main-page { \n" +
    "   font-size: x-large; \n" +
    "} \n" +
    ".log { display: none;} \n" +
    ".stack-trace { display: none;} \n" +`

**Comment by cbeust** [comment] 2016-05-12 14:17
Can you explain what the problem is and what this fixes?

**Comment by ruberzhu** [comment] 2016-05-17 03:59
I want to send reports by email, but I found the report needs to be specified. The CSS file

**Comment by juherr** [comment] 2016-05-17 08:34
@ruberzhu It is difficult to fit to all needs. What do you think to have your own reporter for your needs?

**Comment by krmahadevan** [comment] 2017-09-18 11:14
It should be possible to do this currently by building one's own `IReporter` implementation. Closing off this issue.

**Closed by krmahadevan** 2017-09-18 11:14 UTC
Labels: Feature: report
