### ISSUE TITLE
TestNg AnnotationTransformer listener does not work when defined on class level

### ISSUE THREAD

**Issue by debugger89** [cbeust/testng#2738] opened 2022-03-10 06:44 UTC
### Expected behavior
As a developer, I need an IAnnotationTransformer for manipulating the @Test annotation during runtime. Also, I want to define this annotation on the class level instead of the TestNG XML.

```
@Listeners(MyAnnotationTransformer.class)
public class TestClass {
   ...
}
```

MyAnnotationTransformer.java:

```
public class MyAnnotationTransformer implements IAnnotationTransformer {

    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {

        System.out.println("Gotcha!!");
    }
}
```

### Actual behavior
The problem is the MyAnnotationTransformer's transform method is not called during execution.
However, if I provide the MyAnnotationTransformer Listener at the XML level, this is successful.

```
<listeners>
        <listener class-name="com.debugger89.testng.MyAnnotationTransformer" />
</listeners>
```

### Test case sample, Example code to reproduce
**TestClass.java :**

```
@Listeners(MyAnnotationTransformer.class)
public class TestClass {
        @Test
        public void tesMethod()  {
		//DO test
	}
}
```

**MyAnnotationTransformer.java :**

```
public class MyAnnotationTransformer implements IAnnotationTransformer {

    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {

        System.out.println("Gotcha!!");
    }
}
```

**testng.xml**

```
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Test Suuite" verbose="1">
         <listeners>
                  <listener class-name="com.debugger89.testng.MyAnnotationTransformer" />
         </listeners>
	<test name="POC Tests">
		<classes>
			<listener class-name="com.debugger89.scripts.TestClass" />
		</classes>
	</test>
</suite>
```

**Comment by krmahadevan** [comment] 2022-03-10 06:48
> Also, I want to define this annotation on the class level instead of the TestNG XML.

Can you please elaborate as to why do you need this at the class level ? The annotation transformer by design cannot be added at the class via the `@Listeners` annotation because it needs to be executed even before anything else is processed and that can't happen when its added via the `@Listeners` annotation.

Have you considered using a Service Loader approach for wiring in this listener so that the listener works even when you are trying to execute a test from within an IDE (Wherein usually the suite xml file is NOT involved) ?

**Comment by debugger89** [comment] 2022-03-10 07:00
The main reason to require this at the class level is to execute the test case without creating an XML file when a user needs to execute a test. 
Can you please elaborate on the "Service Loader" approach?

**Comment by krmahadevan** [comment] 2022-03-10 07:06
Please refer to the official documentation 
TestNG using SPI : https://testng.org/doc/documentation-main.html#listeners-service-loader
What is SPI in Java: https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html

**Comment by krmahadevan** [comment] 2022-03-10 07:07
Closing this issue with resolution as _question answered_

**Closed by krmahadevan** 2022-03-10 07:07 UTC
Labels: Need: user answer
