### ISSUE TITLE
Jdk9 Early Access Build 99 issue

### ISSUE THREAD

**Issue by nhojpatrick** [cbeust/testng#938] opened 2016-01-02 19:54 UTC
Installed Java 9 Early Access Build 99, trying to build JUnit and identified issue with maven-javadoc-plugin 2.10.3. Will raise with maven-jar-plugin and then submit pull request with updates so TestNG builds with Java 9.

**Comment by cbeust** [comment] 2016-01-02 20:01
Thanks!

**Comment by nitinverma** [comment] 2016-01-03 07:08
Gave a try to build plexus-archiver; many tests fail on jdk9
```
Tests run: 120, Failures: 0, Errors: 33, Skipped: 0
```
The one that's surfacing in our build is where it's assumed version would always be like 1.6, 1.7, 1.8, 1.9 but system property java.version=9-ea (boom boom!).

```java
private static final boolean isJava7OrLower = Integer.parseInt(System.getProperty("java.version").split("\\.")[1]) <= 7;
```

Considering this we'll have to wait for plexus-archiver to migrate to jdk9 or use something else.

**Comment by nitinverma** [comment] 2016-01-03 07:14
All the 33 tests were failing because of this single line.

Not a prover fix just hack.
```
Tests run: 120, Failures: 0, Errors: 0, Skipped: 0
```
```diff
diff --git a/src/main/java/org/codehaus/plexus/archiver/zip/AbstractZipArchiver.java b/src/main/java/org/codehaus/plexus/archiver/zip/AbstractZipArchiver.java
index 574d67e..63fc4ab 100755
--- a/src/main/java/org/codehaus/plexus/archiver/zip/AbstractZipArchiver.java
+++ b/src/main/java/org/codehaus/plexus/archiver/zip/AbstractZipArchiver.java
@@ -113,7 +113,19 @@
         * Java versions from 8 and up round timestamp up.
         * s
      */
-    private static final boolean isJava7OrLower = Integer.parseInt(System.getProperty("java.version").split("\\.")[1]) <= 7;
+    private static boolean isJava7OrLower() {
+      final String javaVersion = System.getProperty("java.version");
+      final String[] splitVersion = javaVersion.split("\\.");
+      int jdkVersion;
+      if (splitVersion.length > 1) {
+        jdkVersion = Integer.parseInt(splitVersion[1]);
+      } else {
+        jdkVersion = Integer.parseInt(System.getProperty("java.version").split("-")[0]);
+      }
+      return jdkVersion <= 7;
+    }
+    private static final boolean isJava7OrLower = isJava7OrLower();
+

        // Renamed version of original file, if it exists
     private File renamedFile = null;
```

**Comment by cbeust** [comment] 2016-01-03 07:29
Doesn't surprise me, let's not waste too much time on this until things
stabilize on the JDK 9 front.

Thanks for looking!


-- 
Cédric

**Comment by cbeust** [comment] 2016-01-03 07:30
Looks reasonable, mind sending a PR?



-- 
Cédric

**Comment by juherr** [comment] 2016-01-03 07:38
It worked with b91 and gradle (the current supported build tool for TestNG): https://adopt-openjdk.ci.cloudbees.com/job/TestNG/

This Jenkins is down for the moment, but it should be updated to the latest jdk9 build for sure :) 
Ping @neomatrix369

**Comment by nitinverma** [comment] 2016-01-03 09:21
@juherr 
Did you do differently? following is my output
```
github/nitinverma/testng master $ ./gradlew --stacktrace clean

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9-ea'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '9-ea'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:63)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:72)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:520)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:520)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

@cbeust 
Sure, I can send a PR. After few validations.

**Comment by nhojpatrick** [comment] 2016-01-03 10:51
The reason I raise this issue was to highlight the issue so if anyone checks open issues with TestNG they are aware it's a know issue with a dependency of TestNG.

Could it please be reopened.

Regarding the error with gradle, that is the exact same error I get with maven.

Regarding it works for b91 great, I'm using b99.

I've email the OpenJDK mailing lists and get some answers, it looks like the structure will change in Java 9 and also "1." will be dropped.

Regarding Java 9 isn't stable, yep I agree but technically it should be feature complete in a few days now. I want to make Java 9 impact on the community better than that of Java 8. Lots of people I know say only use Java 8 update 40 or later. I would Java 9 to be a much lower update, ideally single digit.

**Comment by nitinverma** [comment] 2016-01-03 11:54
JEP 223: New Version-String Scheme
https://bugs.openjdk.java.net/browse/JDK-8061493

So Oracle/OpenJDK would have 9* format vs 1.9* format now onwards.

```
             Existing                Proposed
Release Type    long           short    long           short
------------    --------------------    --------------------
Early Access    1.9.0-ea-b19    9-ea    9-ea+19        9-ea
Major           1.9.0-b100      9       9+100          9
Security #1     1.9.0_5-b20     9u5     9.0.1+20       9.0.1
Security #2     1.9.0_11-b12    9u11    9.0.2+12       9.0.2
Minor #1        1.9.0_20-b62    9u20    9.1.2+62       9.1.2
Security #3     1.9.0_25-b15    9u25    9.1.3+15       9.1.3
Security #4     1.9.0_31-b08    9u31    9.1.4+8        9.1.4
Minor #2        1.9.0_40-b45    9u40    9.2.4+45       9.2.4
```

**Comment by nitinverma** [comment] 2016-01-03 11:57
@nhojpatrick +1
>>> The reason I raise this issue was to highlight the issue so if anyone checks open issues with TestNG >>> they are aware it's a know issue with a dependency of TestNG.

**Comment by juherr** [comment] 2016-01-03 12:31
The issue is just noise in the backlog and it's still available if someone looks for it. 

The problem is we are not able to fix it (or maybe I missed something?) and we didn't plan to make too much efforts on ea releases.

**Comment by nhojpatrick** [comment] 2016-01-03 12:41
Okay, but doesn't closing the default indicate the issue with dealt with...I raised a similar issue with JUnit which just thanked me for checking and

**Comment by juherr** [comment] 2016-01-03 13:31
Could you link the openjdk issue or your message on its mailing list?

**Comment by nhojpatrick** [comment] 2016-01-03 14:50
http://openjdk.java.net/jeps/223 is the link to the JDK Enhancement Proposal for Java 9

**Comment by nhojpatrick** [comment] 2016-01-03 14:52
https://bugs.openjdk.java.net/browse/JDK-8061493 and https://bugs.openjdk.java.net/browse/JDK-8085822 are the issues tracking the change going into Java 9

**Comment by cbeust** [comment] 2016-01-03 14:54
@juherr Thanks for reopening.

@nitinverma Thanks for the version chart, very useful.

**Comment by nhojpatrick** [comment] 2016-01-03 19:06
Fixes awaiting release;
https://issues.apache.org/jira/browse/MJAR-206
https://issues.apache.org/jira/browse/MJAVADOC-443

Pull request into maven-plugin;
https://github.com/apache/maven-plugins/pull/76

**Comment by nhojpatrick** [comment] 2016-01-03 19:34
See pull request https://github.com/cbeust/testng/pull/941

**Comment by juherr** [comment] 2016-01-04 20:20
About gradle, it seems to be fixed with 1.12 and later: https://discuss.gradle.org/t/java-lang-illegalargumentexception-could-not-determine-java-version-from-1-9-0-ea/1944

Could someone test it?

BTW, I still don't understand the need of compiling with jdk9 when we've just dropped the support of java6.

**Comment by nitinverma** [comment] 2016-01-04 20:30
our current gradle version is 2.5 and the error stays `Could not determine java version from '1.9.0-ea'.` not `Could not determine java version from '9-ea'.`

**Comment by juherr** [comment] 2016-01-04 20:42
Oops

**Comment by juherr** [comment] 2016-01-04 20:45
2.10 instead: https://discuss.gradle.org/t/jdk9-jigsaw-build-problem/13054/3

**Comment by nitinverma** [comment] 2016-01-04 21:03
Yup, gradle 2.10 recognizes jdk9b99; but does not like our build.gradle ;)

https://github.com/nitinverma/testng/commit/a8f2d5e3d9bb593dde55d32090f3d2a35c25b940

```
$ ./gradlew --stacktrace clean test
Creating Version file: 6.9.11-SNAPSHOT in /Users/nitin.verma/Codes/git/github/nitinverma/testng/src/generated/java/org/testng/internal
[buildinfo] Not using buildInfo properties file for this build.
:clean
:myDir UP-TO-DATE
:createVersion
:compileGeneratedJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

:processGeneratedResources UP-TO-DATE
:generatedClasses
:compileJava
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Authentication scheme 'all'(Authentication) is not supported by protocol 'file'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compile'.
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:70)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:45)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:367)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:342)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:335)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:661)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:288)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTreeConverter.convertInto(DefaultFileCollectionResolveContext.java:200)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:107)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileTrees(DefaultFileCollectionResolveContext.java:78)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTreeConverter.convertInto(DefaultFileCollectionResolveContext.java:186)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:102)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileTrees(DefaultFileCollectionResolveContext.java:78)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.visitFiles(DefaultFileCollectionSnapshotter.java:85)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:54)
	at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:56)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:132)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.InvalidUserDataException: Authentication scheme 'all'(Authentication) is not supported by protocol 'file'
	at org.gradle.api.internal.artifacts.repositories.transport.RepositoryTransportFactory.validateConnectorFactoryCredentials(RepositoryTransportFactory.java:127)
	at org.gradle.api.internal.artifacts.repositories.transport.RepositoryTransportFactory.createTransport(RepositoryTransportFactory.java:88)
	at org.gradle.api.internal.artifacts.repositories.transport.RepositoryTransportFactory.createTransport(RepositoryTransportFactory.java:79)
	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.getTransport(DefaultMavenArtifactRepository.java:124)
	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createResolver(DefaultMavenArtifactRepository.java:111)
	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createRealResolver(DefaultMavenArtifactRepository.java:102)
	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createResolver(DefaultMavenArtifactRepository.java:93)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ResolveIvyFactory.create(ResolveIvyFactory.java:91)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.createComponentSource(DefaultArtifactDependencyResolver.java:114)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.access$100(DefaultArtifactDependencyResolver.java:56)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:81)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:78)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:137)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:78)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:41)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:39)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:91)
	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyConfigurationResolver.resolve(SelfResolvingDependencyConfigurationResolver.java:40)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolve(ShortCircuitEmptyConfigurationResolver.java:52)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:43)
	... 76 more



BUILD FAILED

Total time: 7.032 secs

```

**Comment by juherr** [comment] 2016-01-04 21:16
Feel free to fix it :)

**Comment by nitinverma** [comment] 2016-01-04 21:58
isolated: `gradle/publishing-jcenter.gradle`
still no clue while line number. hate gradle for this.

**Comment by juherr** [comment] 2016-05-29 07:22
@nitinverma The Gradle issue will be fixed with #1051 if you want to continue to test testng and java9

**Comment by kopax** [comment] 2017-06-06 06:26
Hey guys, did you resolve this ? I am hitting the same error in a totally different project and I can't find what to do.

**Comment by juherr** [comment] 2017-09-03 19:32
@krmahadevan If you want to have a look on it. The latest gradle release is supposed to work with java9 now.

**Comment by krmahadevan** [comment] 2017-09-04 03:00
@juherr - Sure. As soon as I am done with all the current PRs and have gotten them merged I will take a look at this one. Kind of hard to toggle between multiple issues.

**Comment by juherr** [comment] 2018-09-23 18:39
Java 9 is not a target but it should be possible to run test on this platform.
We will check it with https://github.com/cbeust/testng/issues/1808 (in fact, we already check it https://travis-ci.org/cbeust/testng)

**Closed by juherr** 2018-09-23 18:39 UTC
Labels: 3rd-party-issue
