### ISSUE TITLE
beforeInvocation method don't get called for skipped tests

### ISSUE THREAD

**Issue by sbabcoc** [cbeust/testng#1602] opened 2017-11-09 22:43 UTC
### TestNG Version
> 6.10, 6.11

### Expected behavior
Invoked method listener `beforeInvocation` methods should be called even if the test method gets skipped.

### Actual behavior
Invoked method listener `beforeInvocation` methods aren't called for skipped tests.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
* Create a simple invoked method listener that emits a message from `beforeInvocation` and `afterInvocation` if the invoked method is a test.
* Create a test class with a @BeforeMethod configuration method that will fail
* Create a simple test method
* Run the test method

EXPECT: Both `beforeInvocation` and `afterInvocation` should emit messages
ACTUAL: Only `afterInvocation` message will appear

**Comment by sbabcoc** [comment] 2017-11-10 17:17
Looks like this might be the same issue that I reported previously (https://github.com/cbeust/testng/issues/1465)

**Comment by krmahadevan** [comment] 2017-11-14 02:58
@sbabcoc - If its the same as #1465 then have you tried reproducing this problem using the current codebase because the fix I have put in, I don't think its been released yet (It will be part of `6.13` only)

@juherr - Do you know if we publish snapshots to Bintray ? If yes, can you please help share that information here so that @sbabcoc can use that to quickly retest ?

**Comment by juherr** [comment] 2017-11-14 08:16
Snapshots are on https://oss.sonatype.org/content/repositories/snapshots/ (should be documented somewhere)
For example: https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/6.9.14-SNAPSHOT/

**Comment by krmahadevan** [comment] 2017-11-14 08:36
@sbabcoc - You should be trying out with `6.11.1-SNAPSHOT`. See [here](https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/6.11.1-SNAPSHOT/)
The version number for the snapshot is currently messed up. We will be rectifying it pretty soon.

@juherr - I think the versioning is perhaps messed up for snapshots. We are currently moving towards a TestNG `6.13` release, but the version of the gradle file still shows [6.11.1-SNAPSHOT](https://github.com/cbeust/testng/blob/master/build.gradle#L51) I guess we should be changing to `6.13-SNAPSHOT` this right ?

**Comment by juherr** [comment] 2017-11-14 08:43
@krmahadevan Related to #1521

**Comment by krmahadevan** [comment] 2017-11-15 05:31
@sbabcoc - Scott, we have resolved the snapshots version mess up. Can you please revisit this issue using TestNG `6.13-SNAPSHOT` [snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/6.13-SNAPSHOT/)

**Comment by sbabcoc** [comment] 2017-11-28 23:25
I get a different incorrect behavior with 6.13-SNAPSHOT
If @BeforeMethod fails, or if SkipException is thrown from @BeforeMethod, the afterInvocation() method of the @Test method is not called.

**Comment by krmahadevan** [comment] 2017-11-30 04:32
@sbabcoc - Can you please help share a sample that we can execute using TestNG `6.13.1` (the latest released version) to reproduce the issue ?

**Comment by sbabcoc** [comment] 2017-11-30 21:50
I have an open-source project here: https://github.com/Nordstrom/TestNG-Foundation
Update the <testng.version> property in the POM to 6.13.1, followed by Maven clean install.
Three unit tests fail: 

- ExecutionFlowControllerTest.testSkipFromBefore
- ListenerChainTest.verifyBeforeFailed
- ListenerChainTest.verifyBeforeSkipped

Switch back to TestNG 6.10 and all unit tests pass as expected.

**Comment by krmahadevan** [comment] 2017-12-01 01:21
@sbabcoc - It would be really great if you could please help share a sample than having us clone your codebase and running the unit tests.

**Comment by sbabcoc** [comment] 2017-12-01 20:15
package org.example;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

import java.io.File;
import java.lang.reflect.Method;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestContext;
import org.testng.ITestNGListener;
import org.testng.ITestResult;
import org.testng.SkipException;
import org.testng.TestNG;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.internal.IResultListener;
import org.testng.xml.XmlSuite;

public class Issue1602ReproTest {
    @Test
    public void reproduceIssue() {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{ExampleClass.class});
        testNG.setConfigFailurePolicy(XmlSuite.FailurePolicy.CONTINUE);
        MethodListener methodListener = new MethodListener();
        ResultListener resultListener = new ResultListener();
        testNG.addListener((ITestNGListener) methodListener);
        testNG.addListener((ITestNGListener) resultListener);
        testNG.run();
        String file = TestNG.class.getProtectionDomain().getCodeSource().getLocation().getFile();
        System.out.println("TestNG v" + new File(file).getParentFile().getName());
        assertEquals(methodListener.skippedTest, resultListener.skippedTest);
    }

    static class ExampleClass {

        @BeforeMethod
        public void beforeMethod(Method method) {
            if ("test1".equals(method.getName())) {
                System.out.println("beforeSkipped");
                throw new SkipException("beforeSkipped");
            }
        }

        @Test
        public void test1() {
            assertTrue(true);
        }

        @Test
        public void test2() {
            assertTrue(true);
        }
    }

    static class MethodListener implements IInvokedMethodListener {
        ITestResult skippedTest = null;

        @Override
        public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
            if ("test1".equals(method.getTestMethod().getConstructorOrMethod().getName())) {
            	skippedTest = testResult;
            }
        }

        @Override public void afterInvocation(IInvokedMethod method, ITestResult testResult) { }
    }
    
    static class ResultListener implements IResultListener {
    	
    	ITestResult skippedTest = null;

		@Override
		public void onTestSkipped(ITestResult arg0) {
			skippedTest = arg0;
		}

		@Override public void onFinish(ITestContext arg0) { }
		@Override public void onStart(ITestContext arg0) { }
		@Override public void onTestFailedButWithinSuccessPercentage(ITestResult arg0) { }
		@Override public void onTestFailure(ITestResult arg0) { }
		@Override public void onTestStart(ITestResult arg0) { }
		@Override public void onTestSuccess(ITestResult arg0) { }
		@Override public void onConfigurationFailure(ITestResult arg0) { }
		@Override public void onConfigurationSkip(ITestResult arg0) { }
		@Override public void onConfigurationSuccess(ITestResult arg0) { }
    }
}

**Comment by sbabcoc** [comment] 2017-12-01 20:21
The issue with 6.13.1 is that the test result that's passed to the result listener is not the same as the result that's passed to the invoked method listener. 

The invoked method listener appears to be handed a test result object that was just created to satisfy the contract of the method, not the actual test result that's used everywhere else.

Running this code against TestNG 6.10 produces the expected behavior.

**Comment by kool79** [comment] 2017-12-07 00:06
Below results for different public versions of testng (6.10 to 6.13.1)
``` java
@Listeners(Listener.class)
public class ListenersTests1602 {
	@BeforeMethod public void beforeMethod() {
		System.out.println("RUN: beforeMethod");
		throw new RuntimeException();
	}

	@Test public void testMethod() {
		System.out.println("testMethod");
	}
}

public class Listener implements IInvokedMethodListener {

	@Override
	public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
		System.out.println("BeforeInvocation: " +
		                   method.getTestMethod().getMethodName() + ": " +
		                   intToStatus(testResult.getStatus()));
	}

	@Override
	public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
		System.out.println("AfterInvocation: " +
		                   method.getTestMethod().getMethodName() + ": " +
		                   intToStatus(testResult.getStatus()));
	}

	private String intToStatus(int status) {
		switch (status) {
		// ITestResult.CREATED introduced in v9.11
		case -1                 :  return "CREATED";  
		case ITestResult.SUCCESS: return "SUCCESS";
		case ITestResult.SKIP   : return "SKIP";
		case ITestResult.FAILURE: return "FAILURE";
		case ITestResult.STARTED: return "STARTED";
		case ITestResult.SUCCESS_PERCENTAGE_FAILURE:
			return "SUCCESS_PERCENTAGE_FAILURE";
		}
		return " ??? " + String.valueOf(status);
	}
}
```

v6.10 (Expected)
```
BeforeInvocation: beforeMethod: SUCCESS
RUN: beforeMethod
BeforeInvocation: beforeMethod: FAILURE
BeforeInvocation: testMethod: STARTED
BeforeInvocation: testMethod: SKIP
Test ignored.
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================
```

v6.11
```
BeforeInvocation: beforeMethod: SUCCESS
RUN: beforeMethod
BeforeInvocation: beforeMethod: FAILURE
Test ignored.
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================
```

v6.12
```
BeforeInvocation: beforeMethod: SUCCESS
RUN: beforeMethod
BeforeInvocation: beforeMethod: FAILURE
Test ignored.
AfterInvocation: testMethod: CREATED
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================
```
v6.13, v6.13.1
```
BeforeInvocation: beforeMethod: SUCCESS
RUN: beforeMethod
BeforeInvocation: beforeMethod: FAILURE
Test ignored.
BeforeInvocation: testMethod: CREATED
BeforeInvocation: testMethod: CREATED
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================
```
When status is "CREATED" (new since v6.11) we have mostly uninitialized object in testResult:

![img1602](https://user-images.githubusercontent.com/4625317/33691648-de0c0ef6-daf1-11e7-8133-cd914c80d041.png)

It breaks existing implementations of InvokedMethodListener/InvokedMethodListener2 which try to call getTestClass(), getName() etc (to perform logging etc).

**Comment by sbabcoc** [comment] 2017-12-12 16:53
@krmahadevan - What is the status of this issue? The current incorrect behavior is apparently related to the revisions that were made to address the original incorrect behavior. Does this new defect need to be reported in a new issue report?

**Comment by krmahadevan** [comment] 2017-12-13 14:59
@sbabcoc - I haven't gotten around to taking a jab at this one. Kind of held up with stuff at work and not finding time.

**Comment by sbabcoc** [comment] 2018-03-30 17:51
@krmahadevan Any status update? I'd like to upgrade to the latest release, but this issue breaks my implementation.

**Comment by krmahadevan** [comment] 2018-03-30 17:58
@sbabcoc - This is still not addressed. Trying to get to the long list of issues that are pending in my plate. Will try to take a look at it over this weekend.

**Closed** 2018-04-09 16:55 UTC
Labels: Feature: listener, Feature: skip test
