### ISSUE TITLE
Not honoring test group configurations [6.0.1 -> 6.1.x]

### ISSUE THREAD

**Issue by ben-manes** [cbeust/testng#69] opened 2011-07-18 21:24 UTC
When updating the Maven dependency from v6.0.1 to v6.1.1, the test suite fails due to the parameters not being supplied. This occurs because the tests are being run outside of their test group and the params are selectively configured in the YAML file.

See,
http://code.google.com/p/concurrentlinkedhashmap/source/browse/trunk

Configuration:
http://code.google.com/p/concurrentlinkedhashmap/source/browse/trunk/src/test/resources/testng.yaml

All tests are run regardless of what group is requested to be executed, such as by executing the command:
$ mvn -P caliper test
should run a benchmark inside of a sub-package. Instead it fails as below.

Note that this works correctly in v6.0.1, but not in v6.1.x. Please see the README.md file if you want to build the project.

Thanks,
Ben

---
##  T E S T S

Running TestSuite
org.apache.maven.surefire.booter.SurefireExecutionException: 
Parameter 'iterations' is required by @Parameters on method public com.googlecode.concurrentlinkedhashmap.MultiThreadedTest(int,int,int)
but has not been marked @Optional or defined in /usr/local/google/bmanes/clients/lru/src/test/resources/testng.yaml; nested exception is org.testng.TestNGException: 
Parameter 'iterations' is required by @Parameters on method public com.googlecode.concurrentlinkedhashmap.MultiThreadedTest(int,int,int)
but has not been marked @Optional or defined in /usr/local/google/bmanes/clients/lru/src/test/resources/testng.yaml
org.testng.TestNGException: 
Parameter 'iterations' is required by @Parameters on method public com.googlecode.concurrentlinkedhashmap.MultiThreadedTest(int,int,int)
but has not been marked @Optional or defined in /usr/local/google/bmanes/clients/lru/src/test/resources/testng.yaml
    at org.testng.internal.Parameters.createParameters(Parameters.java:144)
    at org.testng.internal.Parameters.createInstantiationParameters(Parameters.java:52)
    at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:315)
    at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:284)
    at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:109)
    at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:181)
    at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:120)
    at org.testng.TestRunner.initMethods(TestRunner.java:402)
    at org.testng.TestRunner.init(TestRunner.java:228)
    at org.testng.TestRunner.init(TestRunner.java:198)
    at org.testng.TestRunner.<init>(TestRunner.java:147)
    at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:525)
    at org.testng.SuiteRunner.init(SuiteRunner.java:156)
    at org.testng.SuiteRunner.<init>(SuiteRunner.java:110)
    at org.testng.TestNG.createSuiteRunner(TestNG.java:1235)
    at org.testng.TestNG.createSuiteRunners(TestNG.java:1222)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1074)
    at org.testng.TestNG.run(TestNG.java:999)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
    at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
    at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.813s
[INFO] Finished at: Mon Jul 18 14:12:06 PDT 2011
[INFO] Final Memory: 5M/79M
[INFO] ------------------------------------------------------------------------

**Comment by krmahadevan** [comment] 2017-09-17 04:06
This doesn't seem to be a problem anymore with TestNG 6.12. 

Here's what I have

**Github69TestClass.java**
```java
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

@Test(groups = {"github69"})
public class Github69TestClass {
    private String name;
    private int age;

    @Parameters({"name", "age"})
    public Github69TestClass(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public void testMethod() {
        System.err.println(String.format("[%s is %d years old]", name, age));
    }
}
```

**Yaml file used is as below**

```yaml
name: ConcurrentLinkedHashMap

tests:
  - name: Stress Tests
    parameters:
      name: "Old Monk"
      age: 65
    classes:
      - com.rationaleemotions.github.issue69.Github69TestClass
```

**Maven surefire plugin looks like below**
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.19.1</version>
    <configuration>
        <groups>github69</groups>
        <suiteXmlFiles>
            <suiteXmlFile>src/test/resources/github69.yaml</suiteXmlFile>
        </suiteXmlFiles>
    </configuration>
</plugin>
```

**Selective Output looks like below**
```bash
✔ ~/githome/PlayGround/testbed 
09:27 $ mvn clean test
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building testbed 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ testbed ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
...
... TestNG 6.12 by Cédric Beust (cedric@beust.com)
...

[Old Monk is 65 years old]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.351 sec - in TestSuite

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.741 s
[INFO] Finished at: 2017-09-17T09:29:28+05:30
[INFO] Final Memory: 36M/328M
[INFO] ------------------------------------------------------------------------
✔ ~/githome/PlayGround/testbed 
```

**Comment by ben-manes** [comment] 2017-09-17 04:29
Cloning the github repo and making changes to run on Java 8 (removing the CHM backport), it fails when upgrading to 6.11 (latest on Central). This isn't blocking me as I don't use this format in Caffeine, the successor.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project concurrentlinkedhashmap-lru: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException:
[ERROR] Parameter 'threads' is required by @Parameters on method public com.googlecode.concurrentlinkedhashmap.MemoryLeakTest(int,long) but has not been marked @Optional or defined
[ERROR] in /Users/ben/projects/concurrentlinkedhashmap/src/test/resources/testng.yaml
[ERROR] 	at org.testng.internal.Parameters.createParameters(Parameters.java:199)
[ERROR] 	at org.testng.internal.Parameters.createInstantiationParameters(Parameters.java:88)
```

**Comment by krmahadevan** [comment] 2017-09-17 04:31
@ben-manes - Can you please help share a small project which can be executed to recreate the problem ?

**Comment by ben-manes** [comment] 2017-09-17 04:41
You can clone the repository, download the [patch file](https://github.com/cbeust/testng/files/1308834/testng.txt), and use `git apply testng.txt`. Probably that's the easiest since I haven't looked at this problem for 6 years (and fine it closed as too old to revisit).

**Comment by krmahadevan** [comment] 2017-09-17 04:42
@ben-manes - I will give this a try and let you know how it goes. If its a problem, I would like to try and fix it, than close it off as _too old to revisit_ :) If I can reproduce it, I will re-open the issue.

**Comment by ben-manes** [comment] 2017-09-17 04:45
Thanks. FYI, in the `NOTES` it has build instructions as there was a dependency not on Central (I think it later became JBoss Railgun)

```
mvn install:install-file \
    -Dfile=lib/cache-benchmark/benchmark-fwk.jar \
    -DpomFile=lib/cache-benchmark/pom.xml
```

**Comment by krmahadevan** [comment] 2017-09-17 04:48
Able to reproduce the issue using TestNG 6.12 using the information and patch that @ben-manes has shared.

**Comment by krmahadevan** [comment] 2017-09-17 08:03
@ben-manes - I spent sometime trying to debug the problem and it looks like it boils down to the below section in your suite yaml file

```yaml
tests:
  - name: Standard Tests
    parameters:
      capacity: 100
    packages:
      - name: com.googlecode.concurrentlinkedhashmap
        exclude:
          - RingBufferTest
          - MemoryLeakTest
          - MultiThreadedTest
```
Here TestNG is expecting that you provide with a package name in the `exclude` list, but you have provided class names. That is why when TestNG is initializing itself for the `test` `Standard Tests` it is not excluding these three classes. TestNG tries to instantiate `MemoryLeakTest` and finds that it has a `@Parameters` annotated constructor, but there are no parameters called `"threads", "statusInterval"` being passed from the `<test>` which explains the failures.

You should be passing in a valid package name for `exclude:` 
I tried relocating those tests to another package called `special`

```bash
✔ ~/githome/OpenSource/concurrentlinkedhashmap/src/test/java/com/googlecode/concurrentlinkedhashmap [master|●3✚ 9…55]
13:30 $ tree special/
special/
├── MemoryLeakTest.java
└── MultiThreadedTest.java
```
And then I reran the tests with the same command and the tests run (of-course the JVM crashes but I don't think its related to the current problem )

**Here's how the modified section of the yaml file looks like**
```yaml
tests:
  - name: Standard Tests
    parameters:
      capacity: 100
    packages:
      - name: com.googlecode.concurrentlinkedhashmap
        exclude:
          - com.googlecode.concurrentlinkedhashmap.special.*
```

**Here's the execution output**

```bash
13:30 $ mvn -P caliper test
[INFO] Scanning for projects...
[WARNING] The project com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4.3-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ConcurrentLinkedHashMap 1.4.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ concurrentlinkedhashmap-lru ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ concurrentlinkedhashmap-lru ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/krmahadevan/githome/OpenSource/concurrentlinkedhashmap/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ concurrentlinkedhashmap-lru ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /Users/krmahadevan/githome/OpenSource/concurrentlinkedhashmap/target/classes
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.13:check (check-java16-sun) @ concurrentlinkedhashmap-lru ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16-sun:1.0
[INFO]
[INFO] --- maven-bundle-plugin:2.5.3:manifest (bundle-manifest) @ concurrentlinkedhashmap-lru ---
[WARNING] Manifest com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4.3-SNAPSHOT : Unused Import-Package instructions: [sun.misc.*]
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ concurrentlinkedhashmap-lru ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ concurrentlinkedhashmap-lru ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.18:test (default-test) @ concurrentlinkedhashmap-lru ---
[INFO] Surefire report directory: /Users/krmahadevan/githome/OpenSource/concurrentlinkedhashmap/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite

[Caliper Benchmark]
Running GetPutBenchmark
Experiment selection:
  Instruments:   [allocation, micro]
  User parameters:   {cache=[Guava, ConcurrentHashMap, LinkedHashMap_Lru_Lock, ConcurrentLinkedHashMap]}
  Virtual machines:  [default]
  Selection type:    Full cartesian product

This selection yields 16 experiments.
Starting experiment 1 of 16: {instrument=allocation, method=Get, vm=default, parameters={cache=Guava}}
The worker exited without producing data. It has likely crashed. Run with --verbose to see any worker output.

Results :




Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.131 s
[INFO] Finished at: 2017-09-17T13:31:00+05:30
[INFO] Final Memory: 25M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project concurrentlinkedhashmap-lru: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/krmahadevan/githome/OpenSource/concurrentlinkedhashmap && /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -jar /Users/krmahadevan/githome/OpenSource/concurrentlinkedhashmap/target/surefire/surefirebooter2031855192755535703.jar /Users/krmahadevan/githome/OpenSource/concurrentlinkedhashmap/target/surefire/surefire6877731661671688379tmp /Users/krmahadevan/githome/OpenSource/concurrentlinkedhashmap/target/surefire/surefire_02971522054735753782tmp
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```


Please let me know if that makes sense.

**Closed by krmahadevan** 2017-09-17 08:03 UTC
Labels: Issue: Confirmed

**Comment by ben-manes** [comment] 2017-09-17 08:12
Interesting. It was nice to be able to exclude classes. Do you know why that feature was dropped in 6.1?

**Comment by juherr** [comment] 2017-09-17 11:57
Ping @cbeust
What is the expected behavior?
