### ISSUE TITLE
Does Factory annotation with Data provider  supports for sequential way of dataSet execution without using any workaround in any latest testNG version?

### ISSUE THREAD

**Issue by ManjuTech** [cbeust/testng#1871] opened 2018-07-23 07:09 UTC
### TestNG Version
We tried in latest Version TestNG -6.14.0 . Expected behaviour is not supported yet.
Please reconfirm 

### Expected behavior
During Execution it should go in the same order sequentially using Factory with dataProvider

Example 
TestCase1
TestCase2
TestCase3
TestCase4
TestCase5

### Actual behavior
DataSets Given -> TestCase1 ,TestCase2,TestCase3,TestCase4,TestCase5

Execution 
TestCase5
TestCase2
TestCase3
TestCase1
TestCase4

### Is the issue reproductible on runner?
- testNG Latest Version- 6.14.0

Could you please suggest ?

**Comment by krmahadevan** [comment] 2018-07-23 13:09
@ManjuTech - This sounds more like a question than a bug. Can you please help add a simple standalone that can be used to reproduce the problem ? Please exclude any third party library references and keep it simple (perhaps using a bunch of system.out.println statements). Also please retry using the latest version of TestNG `6.14.3` as of today.

**Comment by ManjuTech** [comment] 2018-07-24 07:33
@krmahadevan - Thanks for the response .
 
As suggested i tried the same scenario in 6.14.3 latest release . Sequential way of Dataprovider execution is working but one more issue .

As i observed -  during 1st , 3rd , 5th execution output is coming as expected  ,  but during 2nd , 4th , 6th execution  , there is an issue with multiple test methods .

**Steps to Followed** 
**1) Java Code** 
package comFactory;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class TestTest {
    private int num;

    @Factory(dataProvider = "data")
    public TestTest(int n) {
        num = n;
    }

    @DataProvider
    public static Object[][] data() {
        return new Object[][]{{1}, {2}, {3}, {4}};
    }

    @Test
    public void test1() {
        System.out.println("Test1 -> "+num);
    }
    
    @Test
    public void test2() {
        System.out.println("Test2 -> "+num);
    }
    
    @Test
    public void test3() {
        System.out.println("Test3 -> "+num);
    }

    @Override
    public String toString() {
        return Integer.toString(num);
    }
}

2)**xml** 
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="Sample_Test_Suite" group-by-instances="true" data-provider-thread-count="2" parallel="false" allow-return-values="true" preserve-order="true">
	
  <test name="Sample_Test1">	
	    <classes>
	      <class name="comFactory.TestTest">
	          <methods>   
				      <include name="test1"/> 
				      <include name="test2"/>  
				      <include name="test3"/>
 			   </methods>	
	      </class>
	    </classes>
  </test>
  
  <test name="Sample_Test2">	
	    <classes>
	      <class name="comFactory.TestTest">
	          <methods>   
				      <include name="test1"/> 
				      <include name="test2"/>  
 			   </methods>	
	      </class>
	    </classes>
  </test>
  
</suite>

3) Execute 1st time - Will get proper output in both console and testNG report
    Execute 2nd time - TestNG Report will be as in the screenshot ( will be keep on in the same state)

   To reproduce the issue ( try Vice Versa Scenarios).
 
**Issue in TestNG Report**
![image](https://user-images.githubusercontent.com/23966691/43123388-a24067f0-8f41-11e8-9f34-ccf429ecf33e.png)


Could you please suggest the workaround to proceed furthur?

**Comment by ManjuTech** [comment] 2018-08-08 09:08
@krmahadevan ,
Hi ,  Is there is any workaround for the above issue ?

**Comment by juherr** [comment] 2018-08-09 08:17
What if you use `data-provider-thread-count=1`?

**Comment by juherr** [comment] 2018-08-09 08:17
Do you reproduce the same issue with another runner (like maven or command line?)

**Comment by krmahadevan** [comment] 2018-12-10 17:04
Unable to reproduce this using `TestNG 7.0.0-beta1` on IntelliJ. Closing this issue. If this is still a problem please let us know how the tests are being run and where the problem exists.

**Closed by krmahadevan** 2018-12-10 17:04 UTC
Labels: Feature: data-provider, Feature: factory
