### ISSUE TITLE
6.9.12 missing dependencies

### ISSUE THREAD

**Issue by leerho** [cbeust/testng#1141] opened 2016-09-06 22:00 UTC
I'm not sure if this has been reported but 6.9.12 is missing some dependencies in its POM and Maven is unable to resolve them.  I get this trace:

java.lang.NoClassDefFoundError: com/google/common/primitives/Ints
	at org.testng.internal.annotations.JDK15TagFactory.createDataProviderTag(JDK15TagFactory.java:335)
	at org.testng.internal.annotations.JDK15TagFactory.createTag(JDK15TagFactory.java:59)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:217)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:111)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:326)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:261)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:418)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1240)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:165)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:78)

**Comment by juherr** [comment] 2016-09-06 22:02
Duplicate of #1085 and fixed by #1086

**Closed by juherr** 2016-09-06 22:02 UTC
