### ISSUE TITLE
Lot of test start to be runned slowly after 150 (approximately) has been launched

### ISSUE THREAD

**Issue by samixchoumi** [cbeust/testng#2011] opened 2019-01-30 13:45 UTC
### TestNG Version
6.11 and tried the latest (7 beta-3)

### Expected behavior
All my test should run well.

### Actual behavior
Only the first tests run well, then it start to bug.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
The test are launched on a docker container.
I've a package with a lot of package, in these packages i've some Selenium test.
Some test have the annotation "dependsOn" and they're not runing on parallel case.

- First of all on some package i've a workflowTestCase with some test in it and a specificTestCase with other test in it, normally it should run the workflowTestCase, then the specificTestCase but actually it launch all the workflowTestCase from each package, then the specificTestCase.
- Secondly, after that some package has been executed, all the other test who have the dependsOn annotation will not be executed for no reason.
- Finally, after a moment, the test take a lot of time to switch to a testCase (at the start it's fast, then after 150 test (approximately) it start to take 1 / 2 / 10 / 100 / 3600 (and more) seconds to close a test)
When i stop while the testCase is finish but the testRunner isn't stopped as it should be, i appear to be on `DynamicGraph.getNode()`

The problem is that before i've got 0 problem and, for an unknown reason, i've all these problem now (and 0 error are showing)

**Comment by krmahadevan** [comment] 2019-01-30 13:54
Please help share a sample project that can be used to reproduce the problem. Without a sample it's hard to even say what could be wrong.

**Comment by samixchoumi** [comment] 2019-01-30 14:07
> Please help share a sample project that can be used to reproduce the problem. Without a sample it's hard to even say what could be wrong.

I will try to find a way to create a sample project

**Comment by samixchoumi** [comment] 2019-02-01 13:12
Hello @krmahadevan, 
So i've tried to find a way to give you a sample project but it's a strong project so i will explain you what i did and what i've found.

Firstly, all my test are on different classes (approximately 10 tests for each classes) ==> i've 73 classes for 292 tests.
They have no dependency on each classes except that on some classes where 2/3 test depends from each other (b depends of a  and c depends of b). (the problem seem to be not here)
Only 1 classes use the annotation `@priority` (we've found this classes who use the priority annotation cause the problem)
Here is the graph created with `toDot()`, all the classes including the one with priority annotation : [test.txt](https://github.com/cbeust/testng/files/2821622/test.txt)
Here is the graph created with `toDot()`, all the classes excluding the one with priority annotation : [test_sans_form.txt](https://github.com/cbeust/testng/files/2821623/test_sans_form.txt)

As you can see more than 1 000 lines was removed.

When we remove the class with the priority annotation, all test run fine. When we add it, `setStatus()` from DynamicGraph.java is iterating a lot and it's taking more and more time for each test classes done.

_PS : I've verified on the latest version but on the 6.11 of TestNG `DynamicGraph.getName()` is wrongly done_

**Comment by krmahadevan** [comment] 2019-02-01 16:03
@samixchoumi - Unfortunately I can't use this information to zero in on the issue. So unless you can please help share a sample, not sure if I can do much here.

**Comment by samixchoumi** [comment] 2019-02-01 16:16
You can just reproduce it with one big package, some specific package for your classes, put 300 tests distributed into 75 classes and only one classes of test will have the @Priority annotation one all included test. Then you should see that some weight from value `m_allEdges` in `DynamicGraph.setStatus(T node, Status status)` are strangely too big. ![image](https://user-images.githubusercontent.com/22171928/52134652-4fcd5880-2644-11e9-8875-8f9c2c4218ee.png)

**Comment by krmahadevan** [comment] 2019-02-01 16:17
Since you have better idea on what the issue is, why not create that sample and share it here ?

**Comment by juherr** [comment] 2019-02-22 20:07
@samixchoumi Any update?

**Comment by krmahadevan** [comment] 2019-09-02 15:24
No updates on this issue. Closing this issue. If this is still a problem with `7.0.0` please help share a standalone sample that can be used to reproduce the problem.

**Closed by krmahadevan** 2019-09-02 15:24 UTC
Labels: Need: sample, perf/enhancement
