### ISSUE TITLE
HTML Colours are not getting reflected in the report in TestNG 6.8 release

### ISSUE THREAD

**Issue by Ramnathan** [cbeust/testng#403] opened 2013-07-10 12:48 UTC
When we give HTMLcode in the Reporter.Log function, generally that particular colour will be reflected for whatever we have given in the HTML report we get, till TestNG 6.7 release but the color is not getting applied from TestNG 6.8 releases. We get some weird error messages if we give the HTML Color code. This is an important aspect which helps to filter the log report(emailable report) with different colours

Yes the issue persists in 6.8.5 also ..

Actually if we give a code "Reporter.log("

"+message+"");", we lll get the message in red color but it does not happen in 6.8 releases. it just prints the contents present in the reporter.log function instead of printing it in red....."Font Color tag given inside the reporter.log method "

**Comment by juherr** [comment] 2015-05-13 14:58
Duplicate of #375

**Closed by juherr** 2015-05-13 14:58 UTC
