### ISSUE TITLE
@Factory method is executing before @BeforeSuite method

### ISSUE THREAD

**Issue by virendrachaudhary06** [cbeust/testng#1836] opened 2018-06-20 06:14 UTC
### TestNG Version
6.14.3

### Expected behavior
The beforesuite method should be executed before factory method in my opinion.
### Actual behavior
Reverse of expected behavior.

### Is the issue reproductible on runner?

Yes, through Maven

### Test case sample

```java
public class TestClass {
    int data ;
    public TestClass(){};
    public TestClass(int data){
        this.data = data;
    }
    @BeforeSuite
    public void beforeSuite(){
        System.out.println(" in before suite method");
    }
    @Test
    public void testMethod(){
        System.out.println(data);
    }
    @Factory
    public Object[] getData(){
        System.out.println("in factory method");
        return new Object[]{new TestClass(1)};
    }
}
```

**Comment by krmahadevan** [comment] 2018-06-20 08:56
@virendrachaudhary06 - Not sure what the confusion here is.
You have a test class which houses both the `@Test` method and also the `@BeforeSuite` method. But for TestNG to instantiate this class so that `@BeforeSuite` can be executed, it needs to instantiate the class. Even though you have provided a default constructor, since you have a `@Factory` annotation, TestNG would invoke it to instantiate your class object, and only then invoke the `@BeforeSuite` method using the newly created instance.

I dont think there's any problem here. Its more to do with how you are using these two annotations.
If you need to ensure that your `@BeforeSuite` gets invoked before anything else, and you want to keep your `@Factory` annotation, then I would suggest that you leverage the `ISuiteListener` TestNG listener instead.

Closing this issue as *Working as designed*

**Comment by krmahadevan** [comment] 2018-06-20 14:19
@virendrachaudhary06 - Can you please help explain what is the use case that you are trying to solve? I took a closer look at TestNG. Object instantiation happens first and only then different lifecycle events such as listener invocation etc., happens. So there's no way this can be changed without TestNG undergoing some major fundamental changes (which I doubt is going to happen). So if you could please help explain your use case maybe we can suggest something accordingly. 

Why is it mandatory for you that the `@Factory` method get called at a later point in time. What is being done in your actual Factory method?

**Comment by juherr** [comment] 2018-06-20 18:42
For me, it is the expected behavior because factories are used for the test suite creation.
Then, the suite is started.

**Comment by virendrachaudhary06** [comment] 2018-06-21 02:12
@krmahadevan -
In @Factory method I am reading a data file. Path of the data file is dependent on one of the parameter which is in testng.xml file. 

Below is my testng.xml file having a parameter with name environment. So before starting the @Factory method. I need a way to read my env parameter.

<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Test Suite" verbose="1" >
    <parameter name="environment"  value="test"/>
    <listeners>
        <listener class-name="com.domain.CustomListener"/>
    </listeners>
    <test name="Test Name" group-by-instances="true">
        <classes>
            <class name="com.domain.TestClass" />
        </classes>
    </test>
</suite>

**Comment by krmahadevan** [comment] 2018-06-21 02:47
@virendrachaudhary06 

You should be able to leverage something like this (notice how we are injecting an `ITestContext` object into the `@Factory` annotated method), with the upcoming release of TestNG viz., 7.0.0.

**Sample class**

```java
package rationale.emotions.issue1836;

import org.testng.ITestContext;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class SampleTest {
  private int data;

  public SampleTest(int data) {
    this.data = data;
  }

  @Test
  public void testMethod() {
    System.err.println(data);
  }

  @Factory
  public static Object[] getObject(ITestContext context) {
    return new Object[] {
      new SampleTest(Integer.parseInt(context.getCurrentXmlTest().getParameter("data")))
    };
  }
}
```

**Suite xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="1836_Suite" parallel="false" verbose="2">
  <test name="1836_test">
    <parameter name="data" value="100"/>
    <classes>
      <class name="rationale.emotions.issue1836.SampleTest"/>
    </classes>
  </test>
</suite>

```

**Closed by krmahadevan** 2018-06-21 02:47 UTC
Labels: Feature: before/after, Feature: factory, Feature: listener

**Comment by juherr** [comment] 2018-06-21 07:44
@krmahadevan `XmlTest` injection could help here ;p

**Comment by krmahadevan** [comment] 2018-06-21 07:48
@juherr,
We can get access to the XmlTest via the ITestContext object.

**Comment by juherr** [comment] 2018-06-21 07:51
@krmahadevan Yes, sure! But some sugar syntax could be helpful.

**Comment by virendrachaudhary06** [comment] 2018-06-21 08:19
@juherr @krmahadevan 
Sorry to say but these are not a good solution for me.  These solutions are specific to a test class file. But for a complete test suite, we need some method which is being executed before starting tests. BeforeSuite is actually helping out here . However, we are losing this feature if there is any @Factory method. 
Even keeping @BeforeSuite method in a separate file is also not solving the purpose.
I moved @BeforeSuite method in Base class-

```java
public class Base {
    @BeforeSuite
    @Parameters({"environment"})
    public void beforeSuite(String environment){
        System.out.println(" in before suite method" + environment);
    }
}

```
Now trying to run suite again with following testng file. In this case, also @Factory method is being executed first.

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Test Suite" verbose="1" >
    <parameter name="environment"  value="test"/>   
    <test name="Test Name" group-by-instances="true">
        <classes>
           <class name="com.deomain.Base" />
            <class name="com.domain.TestClass" />
        </classes>
    </test>
</suite>
```

**Comment by krmahadevan** [comment] 2018-06-21 08:28
@virendrachaudhary06 

> These solutions are specific to a test class file. 

What do you mean its test class specific? I didn't quite understand that. I believe I have already clarified to you that its not possible to have the `@Factory` method called later because its responsible for object instantiation and that is what has to happen first before anything else (even before listener invocation). So if you have multiple `@Factory` methods in your codebase, then you would need to add this parameter to every method (if that's what you mean). 

There are alternatives to reading environment values within an `@Factory` method. You can read it via a `System.getProperty("environment")` which can be set via a `-Denvironment=test` when running the tests from a command line.

I dont have anything else to offer as alternatives. I will side step and let either @juherr or @cbeust help you out here!

**Comment by juherr** [comment] 2018-06-21 08:32
@virendrachaudhary06 You should find all you need in ITestContext.

**Comment by virendrachaudhary06** [comment] 2018-06-21 08:41
Yeah, I know. I will look for alternatives not to use @Factory method. 
Thank you so much for the support.
